* [Preface]
FRANCISCI SALINAE BVRGENSIS IN libros de Musica Praefatio.

INter omnium animantium voces meritò vox humana principem locum
obtinere censetur: quoniam ea sola loquendi & canendi facultate
praedita est. Vnus enim homo verè ac propriè dicitur capere & loqui:
caetera verò animalia per analogiam quandam & similitudinem, yt prata
atque aquæ ridere dicuny tur. Quae duo munera vt exactius ac
perfectius exercere posset, obseruatio cum ratione coniuncta
Grammaticam & Musicam artium antiquissimas inuenit: quarum alteram
antiqui rectè loquendi, alteram benè modulandi scientiam esse
dixerunt. Sunt autem ab ipsis primordijs adeò similes, vt non sorores
modò, sed pene gemellae fuisse censeantur. Nam quemadmodum Grammatica
initium sumit à literis, à quibus nomen accepit: deinde per syllabas,
quae ex literarum permixtionibus fiunt; ac per dictiones, quae ex
syllabarum coniunctione conflantur, ad orationem perficiendam
peruenire contendit: sic etiam Musica à Musis, quibus omnimodam
canendi peritiam tribuebat antiquitas, nuncupata, ex sonis ac
interuallis ex sonorum permixtione sactis, & ex consonantijs, quae
fiunt ex interuallorum coniunctione, melos siue cantum conficit atque
componit. Et sicut loquutio subsistere non potest, nisiratio in ea, &
in dictionibus accentum, & in syllabis quantitatis habeatur, vt per
alterum sublatio vocis ac depressio, per alterum exacta syllabarum
breuitas & longitudo seruetur: ita etiam & multò (vt ita dicam)
naturaliùs ac veriùs id in musica custoditur: ex quibus illud ad
harmoniam, hoc ad rhythmum duas musicae partes, quae totam ipsius vim
intra se continent, spectare dignoscitur. Differunt tamen nihilominis
Grammatica & Musica, quòd illius disciplina ex veterum, qui bene
loquuti sunt, vsu collecta, sola nititur autoritate dicentis: huius
verò doctrina ex ipso rationis aeternae fonte procedens, veritatem
suarum assertionum ineluctabi libus argumentis, & mathematica semper
ratione demonstrat. Inter præecipuas autem disciplinas, quibus antiqui
sapientes philosophantium animos excultos esse debere censuerunt,
honoratissimum semper musicae doctrina locum obtinuit: cuius
euidentissimo est argumento, quod ex Philosophis, quorum vitae
literarum monumentis mandatae sunt, nullus ferè est, qui non in musica
praeceptorem habuisse dicatur. Cuius scientiam atque vsum non minus
viro ciuili, quàm philosopho necessarium esse multis de causis
Aristoteles toto ferè libro Polyticorum octauo determinat. Primum, vt
pulcherrimis valeat gaudere melodijs ac rhythmis, non communi quodam
sensu, qui omnibus innatus est musicae, vt pueri ac serui faciunt: sed
vt arte ac ratione de ijs, quae sunt artis, iudicium serre, & praua
possit à rectis dignoscere. Deinde, cum in duo tempora vita diuisa
sit, alterum negotij, alterum otij, ad negotia quidem cum dignitate
obeunda, alias disciplinas necessarias magis atque vtiles autumat. Ad
vitam verò liberaliter in otio degendam, non ludum aptum esse
contendit, vt plerique propter similitudinem, quam vita voluptuosa cum
felici videtur habere, putant. Sed Mulicam necessariam esse decernit
propter honestatem, quam habet cum voluptate coniunctam. Non enim
solùm, inquit, in negotio nos rectè gerere oportet, sed danda etiam
opera est, yt in otio bene beateque viuamus. Beata verò vita non in
honestate solum, neq; in voluptate, sed in honesta voluptate
consistit. Musicam autem esse de numero iucundissimarum rerum omnes
asserit cosentire. Quod etiam Musei vatis antiquissimi testimonio
confirmat, qui

[Greek]

Hoc est

#+begin_quote
Iucundißsimum, ait, cantum mortalibus esse.
#+end_quote

Sed praeter hanc voluptatem, quam suapte natura omnibus praebet, ob
quam omni homi num aetati, & conditioni, & moribus sensus eius est
iucundus, honoratiorem eam locum habere dicit: plurimum enim posse ad
virtutes in anima ingenerandas. Per eam nanque quadam animi qualitate,
quae ad mores pertinet, afficimur. Quoniam, vt Boëtius etiam Seuerinus
ait, praeter hoc, quòd quemadmodum caeterae mathematicae, circa
inuestigationem veritatis laborat, moralitati etiam coniuncta est:
talis enim efficitur vnusquisque, quales harmonias ac rhythmos audire
consueuit. Proponendam autem imprimis eam pueris esse censet: vt per
illam ab ipsa inde pueritia rebus optimis laetari assuescant, & ab
illiberalibus inhonestisque iocis arceantur. Nec è musica viro ciuili
tam vtile quàm delectabile petendum esse, ait. Non enim, inquit,
ingenuum virum decet, omnibus in rebus semper vtilitatem quaerere; sed
potior apud eum illa debet esse delectatio, quae voluptate non
poenitenda, qualis ex musica percipitur, ipsius animum
afficiat. Quanquam ego nescio, quae maior esse possit vtilitas, quàm
ea, quae prouenit ex musica: siquidem efficimur ab ipsa humaniores,
religiosiores, & doctiores. Humaniores quidem, quoniam, vt Plato ait,
quemad modum gymnastica corpus optimè reddit affectum; ita musica plus
aequo efferatum animum mansuesacit, atque mollit: quod in iuuene
quodam Taurominitano Pythagoram expertum esse D. Aug. & Boëtius
Ciceronem in consiliorum suorum expositione scripsisse tradunt. Cui,
cùm ad pudicae mulieris aedes expugnandas vino calidus & amore
percitus, tibiarum etia & cytharae cantibus incitatus ire contenderet,
neque vllis verbis à tanto facinore posset auerti, cytharistae
Pythagoras imperauit, vti rhythmum mutaret, ac spondeum caneret, quo
ille facto, mansuetior effectus, re infecta domum redijt. Nec vtique
ob aliud poëtas Orpheum & Amphionem finxisse credendum est, illum

#+begin_quote
Arte mat erna rapidos morantem
Fluminum lapsus, celeresq ventos
Blandum & auritas fidibus canoris
Ducere quereus.
#+end_quote

Hunc Thebanx conditoremarcis
#+begin_quote
/Saxa mouere sono testudinis, &er prece blanda/
/Ducere quo vellet./
#+end_quote

Nisi quod homines vagos ac dispersos, quo nihil est ab humanitate
alienius, cantus suauitate delinitos ad societate n humanam, vitamque
ciuilem reduxerunt. Religiosiores autem à musica nos reddi manifestum
est: valde enim erigimur ad rerum caelestium contemplationem
modulationibus & canticis, quae in templis audiuntur; quod in sacris
solennibus experimur, in quibus maiori cum artificio & suauitate
cantatur. Nec alia de causa choros monachorum, aut canonicorum in
terris institutos fuisse credibile est, nisi, vt, quemadmodum
caelestibus in choris angeli Deo semper assistunt, pulcherrimis eius
laudes melodijs ac rhythmis celebrantes, vbi, vt sancta canit
Ecciesia,

#+begin_quote
Nouas semper harmonias voxe meloda concrepat.
#+end_quote

Sic etiam terrenis in hus choris viri religiosi semper Hymnis ac
Pfalmis canendis inuigilarent, & quo meliore possent modo Deum
Optim. Maximumque laudarent. Id quod mali etiam demones, cum sicuti
dij colerentur, appetiuerunt. Nulla enim tam barbara gens vnquam
inuenta est, quae deos, quos coleret, non metris ac canticis
veneraretur. Quod maximae curae fuisse Graecis & Romanis, eorum
narrant historici: sed multò magis id populum Hebraeum, qui verum Deum
agnouit & coluit, curasse compertum est. Nam Salomonis in templo non
pauciores, quàm ducentos & triginta octo cantores, inter quos nouem
erant archipsaltae, & genus omne musicorum instrumentorum sacrae
paginae fuisse testantur. Christianus autem populus non dubium, quin
Hebraeum Ecclesiasticorum cantuum grauitate ac dulcedine superarit: de
quo Cythara psallendi peritissimus Dauid prophetico sermone dixisse
videtur in Psalmis, Beatus populus, qui scit iubilationem. Quae verba
Diuus Hilarius enarrans, Necessaria ergo, inquit, est homivi
Christiano musica, quandoquidem eius beatitudinem in ipsius scientia
consistere propheta decantat. Diuus etiam August. qui sex de Musica
libros omnigena refertos eruditione matura iam aetate conscripsit, se
mirum in modum antequàm ad orthodoxam Christi fidem conuerterotur,
musica delectatum esse di:it: sed post conuersionem vehementer eius
auditione copungi, & valde Hymnis Ecclesiae suauè resonantis
acquiescere. Et Diuo Hieronym.o scribens musi cam, ostendit ad rei
magnae admonitionem hominibus Dei largitate fuisse concessam. Atque
eius ignorationem in libris de doctrina Christiana multarum
intellectum scripturarum asserit impedire. Et duo Ecclesiae lumina
Gregorius, & Ambrosius quantum musicam ad religionis augmentum
prodesse iudicauerint, plurimis canticis Hymnorum à se compositis
testati sunt, quae adhuc alterius Mediolani, & alterius Romae canuntur
Doctiores musicae disciplina nos effici nemo ambigit, qui vel minùs,
quàm mediocriter in mathematicis e ercitatus sit: siquidem vna ex
quatuor mathematicis semper est habita, quae inter disciplinas primum,
vt dicunt, gradum certitudinis obtinent. Cuius veritas à nobis septem
his libris, quos ea de re multis annis, & maximis laboribus tandem ad
finem perduximus, patefacienda est. Quod opus vt aggrederer, non
paucis, nec parui momenti rationibus adductus sum. Primum enim venit
in mentem illius veteris sententiae, qua monemur, vt in ea, quam
nouimus, arte tempus conteramus. Ego verò ab ipsa propè infantia per
totum vitae meae curriculum rebus musicis operam impendi. Nam cum à
nutricis vberibus caecitatem infecto cum lacte suxissem, nec adhibitis
vndique remedijs vlla visus recuperandi spes affulgeret, non alia
parentibus ars vel honestior, vel vtilior visa est, in qua me
potissimum institui vellent, quam ea, quae per auditum, alterum animae
ratione pollentis optimum ministrum, aptissimè posset addisci. Nec
solum in cantu, qui humana voce conficitur, sed multò magis in ea
musicae parte, quae manuum vsu in practicis nstrumentis, quae per
antonomasiam organa vocant, exercetur, omne ferè tempus insumpsi; in
quo quantum profecerim, aliorum esto iudicium. Hoc tamen affirmare
ausim, eum, qui Aristoxeni, Ptolemaei, Boëtij, atque aliorum maximi
nominis musicorum intelligere doctrinam exactè volet, hac in parte
musicae multum diuque exercitatum esse debere: quandoquidem omnes hi
de priori musicae parte, quae Harmonica nuncupatur, & ad
instrumentalis harmonię compositionem pertinet, scripserunt. De qua,
qui versatus fuerit in musicis, quibus vtimur instrumentis, multò
faciliùs ac perfectiùs poterit iudicare. Caeterum ne de aliorum etiam
meorum studiorum ratione nihil omninovidear attigisse: fortè, dum
adhuc puer essem, venit in patriam faemina quaedam honestis orta
natalibus, quae linguae Latinae cognitione pollebat, & vt virgo sacra
fieret, artem organa pulsandi mirum in modum addiscere cupiebat: cuius
addiscendae gratia, cum domi nostrae mansisset, & illa musicam à me, &
ego vicissim ab ipsa Grammaticam didici, quam ab alio fortasse nunquàm
didicissem. Quia vel nunquam id patri venisset in mentem, vel quia
vulgus practicorum ei, nocituras musicae literas per¬ suasisset. Huius
ego disciplinae degustatione discendi cupidior effectus persuasi
parentibus vti me Salmanticam mitterent, vbi linguae Graecae & artium
ac philosophiae studijs per aliquot annos operam dedi. Sed inde
reifamiliaris inopia proficisci coactus in regiam curiam me contuli, &
à Petro Sarmento Archiepiscopo Composte. lano peramanter exceptus, cum
eo paulò post in numerum Cardinalium assumpto, discendi potiùs, quàm
ditescendi gratia Romam veni;, vbi dum inter eruditos viros versarer,
quorum illic magna copia semper fuit, pudere me coepit eius artis,
quam prositerer, ignarum esse, nec eorum, quae tractarem, afferre
posse rationem. Et tandem intellexi non minus in musica, quàm in
architectura verissimum esse illud Vitruuij, quòd ij, qui sine literis
contenderunt, vt manibus essent exercitati, non potuerunt efficerè, vt
haberent pro laboribus autoritatem. Qui autem ratiocinationibus &
literis solis confisi fuerunt, vmbram, non rem persequuti videntur. At
qui vtrumque perdidicerunt, vti omnibus armis ornati, citiùs cum
autoritate, quod fuit propositum, sunt assequuti. Quare cum ex
Aristotele cognouissem, numerorum rationes, consonantiarum &
interuallorum harmonicorum exemplares esse causas, nec omnes
consonantias aut interualla minora in suis legitimis constituta
rationibus inuenirem, veritatem ipsam ad sensus & rationis iudicium
inuestigare conatus sum. Qua in re me plurimùm adiuuerunt, praeter
Boëtium, quem omnes in ore musici habent, Gręcorum antiquorum libri
manu scripti, nec adhuc Latinitate donati; quorum etiam illic magnam
inueni copiam, sed ante alios Claudij Ptolemaei, cui nescio plus
Astronomia debeat, an musica, harmonicorum libri tres ex Bibliotheca
Vaticana, & Porphirij in eos conmentarij maximis diuitijs ex
antiquorum lectione collectis instructissimi: quorum mihi copiam fecit
Cardinalis Carpensis: & Aristoxeni de Harmonicis elementis libri duo,
& Nicomachi, quem Boëtius sequutus est, etiam libri duo, Bachaei vnus,
Aristidis libri tres, itidem Briennij tres, quos Cardinalis Burgensis
Venetijs ex Diui Marci Bibliotheca sibi transcribendos
curauerat. Quorum ijs, quae bene dixerunt, doctior, & quae secus,
cautior effectus, ad huius disciplinae cognitionem exactam potui
peruenire. In cuius inquisitione & examinatione plures viginti tribus
annis consumpsi; & tandem multis calamitatibus, praesertim duorum
Cardinalium & Proregis Neapolitani, qui me magis amarunt, quam
ditarunt, mortibus oppressus, & tribus fratribus bello amissis, maximo
natu tribuno militum, & altero eius signifero sub vrbe Metensi, tertio
ad conducendum militem ab Albano duce misso in itinere interfecto,
paucis contentus, quae tenuem admodum victum suppeditare possent, ad
Hispanias redire decreui.Statueram autem id, quod mihi vitę tempus
superesset, intra meos me continere parietes, & otiosam vitam in
honesta paupertate degentem, mihi tantùm & musis canere:

#+begin_quote
Nam nec diuitibus contingunt gaudia solis,
Nec vixit male, qui natus moriensque fefellit.
#+end_quote

Sed aliter Deo Opt. Maximo visum esse arbitror, qui me ex Italia,
postquam in ea viginti ferè annos non prorsus ignotus impenderam, ad
Hispanias reuocauit: & ex alijs Hispaniarum vrbibus, in quibus artem
musicam praemijs satis amplis exercere poteram, ad Academiam
Salmanticensem post triginta fere annos, ex quo ab ea profectus
fueram, tandem redire concessit. In qua vna, praemia satis honesta
proposita sunt musicae doctrinam, tamquae speculatur, quam quae
operatur, prositenti. Intellexit enim Alphonsus Castellae Rex huius
nominis Decimus cognomento Sapiens, qui vel primus eam instituit, vel
in meliorem formam redegit, non minus musicae disciplinam, quàm
caeterarum mathematicarum, in quibus ille maximè excelluit, disci
oportere: nec solum illius vsum, sed speculationem etiam esse
necessariam ci, qui musici nomine dignus merito iudicandus esset. Quam
ob rem inter primas & antiquissimas cathedram illius erexit, quae cùm
Doctore vacaret, quaereretur que, qui musices vtranque partem in ea
rite docere posset, ego Salmanticam veni, vt huius disciplinae peritos
sui periculum in ea facientes, audirem. Vbi cum aliquod meorum in
musica studiorum specimen dedissem, iudicatus suin ad id munus
obeundum idoneus: & cathedram ipsam duplicato ferè adauctam praemio,
ipsa etiam regia maiestate probante, sum consequutus. Et de me quidem
haec, fortasse plura, quàm opus erat, dicere volui, solum ob hoc, ne
prorsus omni destitutus auxilio rem tantam aggressus esse
viderer. Nuno ad reliquas instituri nostri rationes prosequendas
reuertar. Et possem equidem ostendere, si vellem, nullam esse earum
artium, quae circulum doctrinae constituunt, quae ab eo fastigio, in
quò veterum beneficio fuerat collocata, lapsu miserabili non
deciderit. Sed non libet mala nostra querelis nihil proficientibus
augere: longè enim praestat gaudere, quòd dudum non Romani modò, &
Itali, sed Hispani, Germani, Galli, & Britani illi toto orbe diuisi
hanc tantam bonarum artium ruinam certatim fulcire contendunt. Ac eò
rem paulatim iam perduxerunt, vt non modò ad eloquentiam, sed ad
omnium prorsus bonarum artium scientiam latior ac minùs impedita via
patere videatur. Quod vna in musica facti adhuc non esse, vehementer
conqueror: nulla namque disciplina ab altiori gradu deiecta, & minus
in nitorem antiquum restituta quàm musica reperitur. quotus enim
quisque est eorum, qui professores illius haberi volunt, qui eius
disciplinae vestigium vnquam animad uerterint! Nec quemadmodum, qui
caeteras artes profitentur earum scientiam ex causi ac principijs
adipisci conantur, sic etiam musici huius temporis musicae disciplinae
causas usque ad elementa scire concupiscunt, sed tantum ipsius
operationi dediti quod ad scientiam attinet, omnino contemnunt. Nam si
quaeras ab eis, quid sit tonus: illum diapente ad diatessaron excessum
esse respondebunt: sed quanam in proportione sit constitutus, ignorare
non erubescent. Sexcentaque sunt id genus alia, quae non tam gloriosum
erat eis scire quàm turpe nescire. Fatemur autem apud Italos & Gallos
non solum, qui caeterarum bonarum artium, sed huius etiam disciplinae
ruinam fulcire contendant, aliquos reperiri. Inter nostrates etiam
quosdam nouimus, id esse conatos; sed potiùs optasse, quàm re
praestitisse. Qiod ego cum non sine iusta animi indignatione sępe
mecum agitarem, mei nescio quo pacto me paenitere coepit. Dolebam
enim, quòd totam prope modum aetatem ita consumpsissem, vt nihil de
posteritate cogitans, in solo eorum profectu, qui à me discere
voluissent, mei periculum fecissem. Nec vnquam si quid in me ingenij &
eruditionis esset, aliter, quàm alios docendo probare
tentassem. Pręsertim cum propter exiguum quęstum, qui ex huius
disciplinę scientia prouenire solet

#+begin_quote
Pauci, quos aquus amauit luppiter.
#+end_quote

eam addiscere ac audire velint: & ex his, quorum eius doctrinam maximi
scire intererat vix vnus aut alter, qui gymnasium ei praecipiendae
dicatum adeat, inueniatur. Itaque mutato in melius, nisi me spes
fallit, proposito, coepi velle absentibus etiam & posteris prodesse,
si possem. Quod effecturum me putaui, si ex his, quae scripseram,
didascalicon aliquid, atque id non inutile publicassem: statimque
animum conuerti ad libros, quos hac de re multis abhinc annis
inchoatos, postea propemodum abieceram, non inutiles quidem illos
ratus, sed veritus ne malè feriati homines priùs negligerent, quàm
intellex issent, & consilium meum statim reprehenderent, & clamarent
me post tot Graecos & Latinos autores, & illos quidem grauissimos, in
re toties agitata, toties scripta, nihil aliud posse, quàm quod veteri
prouerbio vetamur, actum agere. Hac ego re, atque alijs, quas obijci
mihi posse intelligebam, nihil deterritus, sed magis magisque
incitatus, quoscunque vel antiquorum, vel recentiorum tractatus ea de
re inuenire potui, diligenter euolui. Et vt quosdam ex eis musica
peritissimos fuisse negare non ausim, ita illud, nihil reluctante
conscientia, affirmauerim, neminem eorum, quos huius disciplinae
scriptores habere contigit, in eius doctrina praecipienda omnes, quod
aiunt, verè numeros expleuisse. Cuius euidentissimo est argumento,
quòd, cum vnam atque eandem musicam semper fuisse, semperque futuram
esse necesse sit, eaedemque consonantiae tam apud Graecos, quàm apud
Persas sensus ac rationis iudicio deprehendantur, non aliter quam in
arithmetica bis duo christianis & barbaris sunt quatuor, non idem in
hac scientia videtur accidere. Nam aliter Pythagoras & Nicomachus
atque alij Pythagorei, aliter Ptolemaeus, & qui eum sequuti sunt, &
multò secus Aristoxenus atque eius sequaces circa consonantias &
dissonantias, & circa diatessaron diuisionem, in cuius exacta
partitione huius scientiae cardo consistit, opinati sunt. Vt cum eorum
atque aliorum maximi nominis musicorum assertiones inueniendae potiùs
veritatis, quàm tantorum virorum aestimationis minuendae causa
diligenter examinabimus, apparebit. Iuniores verò & nostri seculi
homines tantùm absunt à culpa, vt non modò digni venia, sed etiam
laude sint. Nam eorum plerique nullos ex antiquis Graecis huius
disciplinae scriptoribus habere potuetunt, quia nondum aut in Latinum
sermonem versi, aut sub praelo fuerunt, vt in manus hominum facilius
venire possent. Et si quis eorum aliquos legit, legisse potius, quàm
intellexisse videtur. Quidam autem quanquàm ingenio valuerunt, & suo
marte plurimis in rebus veritatem inuenerunt, non tamen omnia propter
abstrusam huius rei scientiam & multiplicem difficultatem assequi
potuerunt. Veruntamen hi multa in suos commentarios contulerunt,
quibus nonnihil hic labor noster adiuuatur, & in eo quoque nos eorum
doctrina delectat, quod huius disciplinae cognitionem sciendi cupidis
non honestam modò, sed vtilem esse consentiunt. Quae ratio nos mouit,
vt cum alij pro se quisque rem literariam, qua parte possent, iuuare
tentarent: idque multis ac magnis in rebus iam praestitissent: nos
quoque, quoniam maiora non possumus, experiremur, an hac in parte ab
alijs neglecta, ab alijs quasi percipi nullo pacto queat, deposita ac
desperata, à multis desiderata, à paucis intellecta, aliquid opis
afferre possimus. Atque id maiori fiducia aggressisumus, quòd nunquàm
in magnis ita fuimus occupati, vt minora negligeremus: nec vnquàm
sumus ita speciosa sectati, vt non vtilia praeferremus. Ad haec nullus
me successus aut fauor vnquam ita potuit inflare, vt

#+begin_quote
Artem puderet proloqui, quam factitem.
#+end_quote

Quamobrem nihil inuidiosum mihi sumo, si multa, quae quamuis vtilia ac
prope necessaria, caeteri contemnunt, collegisse me dico; & ea in
communem eorum, qui nesciunt, vsum proferre non erubesco. Nec me adeò
tenet scribendi cacoëthes, vt hunc laborem assumere voluissem, nisi
valde necessarium ac vtilem esse certo certius intellixissem, aut si
ab alijs ea, quae ad disciplinae huius integram perfectamque
cognitionem requiri cognoueram, excogitata vel literis pro rei
dignitate madata reperissem. Nec mirum id cuiquam videri debebit: nan
praeter hoc, quòd acutissimam & speculationibus aptissimam ingenij
perspicacitatem haec doctrina desiderat, oportet etiam, qui notitiam
ipsius exactam habere volet, eum in omni propè disciplinarum genere
versatum esse. Necessaria enim est ei musicae practicae cognitio; vt
non in cantu modò, sed in arte factis instrumentis, vt supra diximus,
exercitatus sit. Habere etiam debet artem numerandi, tam
speculatricem, quàm operatricem maximè perspectam. Principia enim
huius disciplinae ab arithmetica sumuntur, & in ea vt ipsius
conciusiones probantur. & facilitas in numerando mirum in modum
prodest speculationem rerum musicalium intelligere aut facere volenti:
contràverò tarditas, dici non potest, quamtum huiusmodi cogitationibus
officiat. Nec geometricę volumus eum ignarum esse: omnis nanque
matheseos disciplina, vt Boëtius ait, amat alterna probatione
constitui, quae multum ei prodesse poterit in participatione, ut
vocant, musicorum, quibus vtimur, instrumentorum facienda ad ditonum
in duo, & tritonum in tria spatia aeque proportionalia diuidenda. Opus
est etiam ei linguae Graecae cognitione: quoniam omnia vocabula huius
artis Graeca sunt. Et pręterea euoluendi sunt ei scriptores huius
artis, qui fere omnes Graeci fuerunt, praeter Boëtium & Diuum
Augustinum quorum ille harmonicam, hic rhythmicam à Graecis ortas
parentibus Latino sermone loqui docuerunt. Nam cęteri Latini antiqui
quàm paucissima, recentiores verò plura quidem, sed parum dilucide
tradiderunt. Et imprimis ad eam musicae partem, quae ad rhythmum
pertinet, intelligendam, eum in poëtica non parum exercitatum esse
conuenit, vt de metrorum ac versuum multiplici varietate ex varijs
poëtarum exemplis faciliùs ac perfectiùs valeat iudicare.

Quidquid igitur ad huius scientiae perfectam cognitionem pertinere
sumus arbitrati, quanta potuimus cura vndique conquisiuimus, & quae
non solùm apud musicos, philosophos, rhetores ac grammaticos
inuenimus, sed à doctis hominibus audiuimus, vel ipsi excogitauimus,
id totum in septem libros contulimus, ac eos in duas classes, alteram
quatuor, alteram trium primò diuisimus, ita vt quatuor priores prioris
etiam partis musicae, quae ad harmoniam spectat, integram exactamque,
mi fallor, doctrinam contineant. Tres autem posteriores partis quoque
posterioris, quae ad rhythmum attinet, omnia, quę necessario musicum
scire visa sunt, habere deprehendantur. Et quatuor quidem priores ita
digessimus, vt in primo à musicae vniuersè acceptae diuisione & partis
ipsius, quade agimus, definitione orsi, omnia, quae de numeris tam per
se constantibus, quam ad alios relatis, ab arithmetica petere musicum
oportere cognouimus, eôdem congessimus, vt humerorum & proportionum,
quae ex illorum collationibus oriuntur, scientia, quantum satis est ad
demonstrationes harmonicae musicae faciendas, instructus accedat. In
altero de sonis seorsum acceptis, & de eisdem inter se collatis, vnde
interualla harmonica consonantiaeque pro creantur, eodem ordine, quo
de numeris in primo & eorum collationibus, ea, quae harmonicum scire
debere, rati sumus, posita sunt. In tertio, quonam ordine iuxta veram
harmonicae rationis exigentiam, disponi, locarique soni debeant, in
tribus melodiarum generibus exactè perfecteque, ita vt nihil addi,
detrahiue possit, ostendimus. Quorum omnium typos oculis subiecimus,
vt veritatis optima constitutio sensu etiam ac ratione perpendi
queat. Atque ibidem de vero situ commatis in vno quoque trium generum
iuxta mirabile harmonicae rationis artificium non minus ingeniosam,
quàmveram ratiocinationem apposuimus. Et de diuersa artificialium
instrumentorum à perfecto deriuata imperfectione, altera organorum ac
cymbalorum, altera testudinum aut lyrarum multa scitu digna & vtilia
factu, quae nemo adhuc scripsit, nec, vt arbitror, cogitauit,
addidimus. In quarto verò de speciebus consonantiarum multo aliter,
quàm adhuc considerata sunt: de systematis & de sex antiquorum
harmonijs ac tropis, à quibus duodecim recentiorum modi fluxerunt: &
de tonis quot numero sint, & quo pacto à modis differant, ex Graecorum
doctrina, quando Latinorum ante hac id animaduertit nemo, Ptolem aei
testimonijs adductis, tractationem instituimus. Et in huius libri fine
Graecorum & Latinorum, tam antiquorum quam recentiorum, qui de musica
benemeriti sunt, assertiones, qua maiori fide ac diligentia potuimus,
recitauimus, ac examinauimus: vt quaenam earum vera esset, aut proxime
veritatem accederet, exquireremus; & in quibus bene aut secus opinati
sunt, sensu nuncio, & iudice ratione deprehenderemus. In quinto, qui
primus de altera musicae parte, quae rhythmica nominatur, institutus
est, initio quoque à rhythmi definitione sumpto numerum oratorium &
poëticum à musici rhythmi puritate seiuntimus: & de temporibus, ex
quibus pedes constant: & de pedibus seorsum acceptis, & inter se
legitimè copulatis: & de rhythmis, qui ex eorum singulis conficiuntur,
plurima scitu digna tractauimus. In cuius fine fuerit ne apud antiquos
cantus plurium vocum consideratur, & Aristotelis testimonio, ac
efficacibus argumentis apud eos in vsu fuisse, confirmatur. In sexto
de metris per eorum genera, & singulorum generum species, latè
diffuseque tractauimus: & à metricis scriptoribus, quae ad musicam
institutionem necessaria videbantur, desumpsimus. In septimo tandem de
versuum constitutione ac perfectione, ex D. Aug. & Terentiano, & Mario
Victorino, & Hephestione Graeco, atque alijs nobilibus scriptoribus,
quidquid cognitione dignum inuenimus, ad huius operis consummationem
afferre curauimus: examinatione tamen adhibita, vt, dum per veritatem
liceret, illis assentiremur. Scribendi verò stylus nó potuit esse non
varius, vt. potè qui fuerit ex nimis varia Graecorum ac Latinorum
lectione coflatus. Ex quibus pręcipui, qui nos hoc in labore iuuerunt,
plerique sunt Afri, atque eius aetatis cum iam à natiuo candore lingua
Romana valde declinauerat. Et eò maximè diuersum esse necesse fuit,
quòd ipsorum autorum no sententias modò, sed eadem verba multis in
locis, praesertim in libro septimo, ponere voluimus: cum vt operi
nostro maior autoritas accederet, tum etiam vt inspectis illorum
positionibus, ex eorum verbis syncera fide transcriptis, si quid in
eis inesset mendi, vel librarioru negligentia, vel iniuria temporis,
aut ex alijs autoribus, aut ex ipsa disciplinae ratione
corrigeremus. Vel si quid ab illis parum animaduersum ob scientiae
subtilitatem, aut minus exactè consideratum humanae naturae parum
cautae incuria fuisset, ex nostrorum tum illis collatione doctrinae
veritas dilucidior appareret. Accedit ad hoc, quod aliqua nunc sunt in
vsu instrumenta, quę vel antiqui non habebant, vel, quod verius esse
reor, quibus ea nominibus appellarent, nescimus: vt illud, quod ab
hale utica forma, quam habet, Lautuin vocatum esse creditur; & Viola,
cuius chordae tam pectine, quam manu pulsantur. Quod nomen apud
neminem Beda Sacerdote antiquiorem inueni: & multa nunc à practicis
aliter, qua ab antiquis docentur. Quorum cum ad hunc modum non fuerit
antiqua descriptio, heri non potuit, vt sermonem è medio vulgi
fugeremus; aut enim confictis nouis nominibus, cum vetera non
haberemus, arrogantiae crimen subeundum fuit, aut aliquid tot iam
annorum usui concedendum erat. Subiunximus etiam metra vulgaria
Hispanica, Gallica, & Itala Grecis ac Latinis, vt ostenderemus versus
ac metra ad omnes pertinere linguas, vel potius nullius idiomatis esse
propria, quandoquidem in modulationibus absque verbis inueniuntur: &
modos quibus vulgò canuntur, apposuimus, notis & figuris à practicis
recentioribus inuentis delineatos, cùm vt ab omnibus in arte canendi
vel mediocriter exercitatis intelligi possemus; tùm vt vulgarium
linguarum syllabae, in quibus quantitatem fixam non habent, sed omnes
communes sunt, ex ipso cantu longa ne an breues essent,
dignoscerentur. Quod in Graecis ac Latinis fieri necesse non fuisset,
nisi proptereos, qui cum canere sciant, syllabarum tamen quantitatem
ignorant. Quocirca quemadmodum in harmonica per numeros, ac eorum
proportiones veritatem opus fuit demonstrare, sic etiam in rhythmica
per notas cantuum & figuras eam ostendere, coacti sumus: qui cantus
etiam numeri per metaphoram accepti dicuntur, vt apud Maronem Orpheus

#+begin_quote
Obloquitur numeris septem discrimina vocum.
#+end_quote

Qua omnia ex totius operis lectione manifesta cuiuis esse poterunt:
interim satis erit haec pramisisse. Et ne praefatio prologi modum
excedat, ac in libri magnitudinem excrescat, hie prafandifinem
faciemus: si prius, quàm ad operis initium accedamus, auxilium
Omnipotentis Dei poposcerimus, qui laudes suas harmonijs ac rhythmis
varijs ornatas in terris pariter ac in caelis semper ab orbe condito
voluir decantari.

IOANNIS SCRIBONII IN ACADEmia Salmanticensi Graecae linguae Professoris Dodecatechon Græecum.

#+begin_quote
Hulayogas rè nadas dinaiun ixrrioar (xdeus
roruious noeu ioxa tidonin.
Eira d agiootiros ouotior nealo nudot
Movrixis inxiis niçinuiorárov.
Kai piyas onlodunios aiioten iadagns,
Eundioous s aua ro, cvno i d' e loue voge
Kovivridiunos ir apiigvione yuinoro xdtires.
Bovotos in junnaontror didtre adéog.
Touso vrvennéiligt niy aupoliene e Sadunant
xai veagir nogion, rixuitd rs xparson.
Pulposs dacuegun vodvydureave reirines ourus
Jadure weulais, ruri ravsopivois.
#+end_quote

EIVSDEM LATINVM.

#+begin_quote
Tiresie quondam ceco pensauerat auctor
Naturae damnum munere fatidico.
Luminis amißsi iacturam cacus Homerus
Pignore diuini sustinet ingeny.
Democritus visu cernens languescere mentis
Vires, tunc oculos eruit ipse sibi.
His ita dum docte mentis constaret acumen,
Corporis equanimi damna tulère sui.
Vnus at hie magnus pro maltis ecce SALIN AS,
Orbatus visu præstat ptrunq simul.
Cernit in hoc opere id, quod lynceus ille nequiret,
Iigenio quantum nullue in orbe pidet.
#+end_quote

HE visto ellibro de Musica, què compuso el Maestro Francisco de
Salinas, y no hallo enel cosa porqueno se pueda imprimir, y assi me
parecequesedeue dar Licencia, porque es obra muy auentajada de lo que
hasta agora esta escrito en la facultad, y sera muy vtil a todos los
Musicos Theoricos y Practicos, que se qui sieren aprouechar del. En
Madrid r7. de Septiembre 1575.

Iuan Lopez de Velasco.


LVDOVICI CHAZARETAE in laudem autoris

EPIGRAMMA.

#+begin_quote
Dum te virgineos, ò nostri gloria secli
Aoniae fidicen, docte Salina, lyra,
Vrget inaccessi nemoris penetrare recessus
Audacem tantæ laudis anhelus amor:
Exuperas montis secreta biuerticis antra,
Antra, nec humano limina pulsa pede;
Limina qua riguas obliquis flexibus vmbras,
Vmbrosumqu, rigat (astalis vnda nemus.
Hic tum fortè sacros adytis penetralibus artus
Rorabant nudae vitreo in amne Deae.
Hue inopina pago flectens vestigia gressu
Deprendis nudas vitreo in amne Deas.
Vertere nec dum acieni licuit,cùm numine Dinum
lam subita sentis lumina nocte premi.
O sed quæ, o rapta succedunt pramia luci,
Quàm sie à detito Sole carere inuat.
Ductrix accedit cetu comitata sororum,
Et regina sui Calliopea chori:
Ipsa chelyn tradens, facundag plectra, fidesq,
Et meritam incingens birgine fronde comam,
His, antistes, ait, nostris dignande choreis,
Dulcia iacturae damna repende tuæ.
Hae tibi erunt artes, vulgare arcana per orbem
Nostra, & Bistoniae fila nouare lyrae.
#+end_quote

YO Iuan Fernandez de Herrera Secretario del consejo de su Magestad doy
fe que auiendose visto por los Señores del vn libro que con licencia
de los dichos Señores hizo imprimir el Maestro Francisco de Salinas
Cathedratico de propriedad de la facultad de Musica en la Vniuersidad
de Salamanca intitulado de Musica especulatiuale dieron licencia para
que pudiesse vender cada volumen de los del dicho libro en papel a
seyscientos marauedis con que antes, y primero que le veda haga
imprimir en la primera hoja del este testimonio de tassa: fecho en
Madrid, a seys dias del mes de nouiembre, de mil y quinientos y
setenta y siete anos.

Iuan Fernandez de Herrera.

* [Book 1]
** [Chapter 1.1]
DE MVSICA LIB. I.

DE MVSICAE UNIVERSALIS DVPLICI DIVISIONE, ALTERA IVXTA POSItiones antiquorum, altera nuper excogitata.

CAPVT PRIMVM.

E Musica dicere nobis instituentibus, quoniam ipsius vis adeò latè per
vniuersa diffunditur, yt nihil sine illa costare credatur, necesse
erit, eam in partes diuidere, vt quaenam ipsius pars sit, de qua
disputare velimus, faciliùs intelligatur. Musicam ergo antiqui ferè
omnes triplicem esse dixerunt: Mundana, Humanam, &
Instrumentalem. Mundanam quidem eam appellauerunt, quę in dissimilium
motuum caelestium mira coaptatione, & concordi temporumvarietate, ac
elementorum proportionabili permixtione, & denique in harmonica totius
mudi constructione consistit. Humanatem  esse dixerut, que in hominis
opificio, presertim in animae, & corporis coniunctione, & in ipsius
animae partiu dispositione versatur; & in artium omnium, ac
scientiarum ordine; & regnoru, ac rerumpublicarum constitutionibus; &
tandem in his omnibus, quae propriè ad homine pertinent,
inuenitur. Instrumentalen verò illam vocauerunt, quę in vocibus, aut
in Musicis instrumentis, vt in Cithara, & tibijs constituta est. Nos
auten vt hanc Musicae diuisionem non aspernamur, quippe quae magnos
habeat autores, sic etiam alteram, ex ipsius rei natura depromptam, &
ad pręsentem institutionem accommodatiorem afferri posse
censemus. Quae etiam erit trimembris, vt alia Musica sit, quę sensum
tantùm mouet, alia quae intellectum tantùm, alia quae sensum, &
intellectum simul. Quae sensum tantùm mouet, solo auditu percipitur,
neque ab intellectu consideratur; cuiusmodi sunt cantus auium, qui
audiuntur quidem cum voluptate, sed quoniam à nullo mentis sensu
proficiscuntur, non harmonica ratione constant, per quam ab intellectu
valeant considerari. Vnde nullas consonantias, aut dissonantias
efficiunt, verùm innata quadam vocum suauitate delectant. Quod si in
eis aliquando harmonica interualla deprehenduntur, id casu potiùs, aut
ex aptitudine, ad imitandum sibi naturaliter insita, prouenire
censendum est, perquam assuefactae discunt cantus hominum imitari, vt
Psittaci, qui ex nimia audiendi frequentia loquelam imitantur
humanam. Veruntamen haec Musica irrationalis est, vt sensus ipse,
quoniam solùm ab irrationalibus animantibus conficitur, nec propriè
Musica dici potest. non enim aliter aues canere, quàm aquae, &
prataridere dicuntur : & Musica in genere rationalium constituitur, vt
suo loco dicetur. Sed eam inter Musicae genera placuit adnumerare,
propter vsitatissimum loquendi modum, iuxta quem semper apud omnes
nationes Musicae nomen obtinuit. Quę intellectum tantùm mouet,
intelligi quidem potest, audiri verò non potest: sub qua duæe
antiquorum Mundana, & Humana comprehenduntur, cuius harmonia non
aurium voluptate, sed intellectus consideratione percipitur. Siquidem
non in permixtionibus sonorum, sed in rationibus deprehenditur
numerorum. Quanquam enim non inficiamur in maxima disparium motuum
caelestium concordia ratum modulationis ordinem inueniri, vt, exempli
gratia, in signiferi constitutione, consonantiarum, & toni rationes:
id tamen propter harmonicam numeri duodenarij naturam, in quo
signiferum ipsum constitutum est, dicimus euenire. Ob quam Brienius
autor Gręcus eum numerum abAristotele M.να, hoc est, valde musicum
asserit appellari. Neque motus caelestes vllos omnino ciere sonos
opinamur, vel subiecto, vel efficiente causa, vt Phy sicis placet. Nam
praeter Aristotelicas rationes, quas nos huc transferre noluimus, ne
potiùs Physicam, quàm Musicam docere velle videremur, illa certè
probabilis esse videtur, mundanae fabricae conditorem, vt in
necessarijs non defecisse, ita nihil superuacaneum fecisse. Cuiusmodi
futurus erat sonus ille caelestis, qui à nemine posset audiri. Non ab
hominibus, quoniam multis de causis fieri necesse aiunt, vt ad nostras
aures sonus ille non perueniat. Non ab intelligentijs, quae caelos
mouent, quandoquidem neque aures habent, neque auribus
egent. Quamobrem idem iudicium de Musica caelesti, & de elementari
faciendum esse arbitror. Siquidem quae in compage elementorum, & in
temporum varietate perspicitur, non aurium sensu, sed rationis iudicio
perpenditur, qualis est ea, quae in partibus animae inuenitur: in
quibus omnes consonantiarum proportiones inesse dicuntur. Ita vt
facultas rationalis ad irascibilem sesquialteram habeat rationem, in
qua Diapente consonantia constituta demonstratur. Et irascibilis ad
concupiscibilem sesquitertiam, in qua Diatessaron consonantia
reperitur: ex quibus in anima Diapason perfecta consistit. Et
quemadmodum in Musica vocali, siue instrumentali Diapente continet
Diatessaron, & ab ea non continetur, & Diapason habet in se vtramque,
neque ab illis habetur: sic facultas sentiendi continet vegetatricem,
neque ab ea continetur, & facultas rationalis vnica existens habet in
se reliquas duas, neque ab illis habetur: sed in ea tanquam trigonus
in tetragono inesse dicuntur. Praeterea virtutes consonantiae, & vitia
dissonatiae, multis ac iustis de causis ab omnibus communiter
appellantur: quarum rerum cognitio sub auditus sensum cadere non
potest. Non tamen omnino contennenda sunt, quae memoriae consecrauit
antiquitas, quę, quoquo posset modo, semper ad cęlestium rerum amorem,
hominum mentes erigere conata est: quae videndi ac audiendi maximè
delectatione ducuntur. Quae sensum simul, & intellectum mouet, est
inter has media: quia sensu aurium percipitur, & ab intellectu etiam
consideratur. Et haec est, quam antiqui instrumentalem esse dixerunt,
quae non solùm naturali vocum, aut sonorum suauitate auribus est
iucunda: sed etiam harmonica deprehenditur constareratione. Et quia
solus homo inter animantes rationis est particeps, solus etiam omnium
harmoniam intelligit. Quam inter naturalia, & diuina in genere
rationalium reponendam asserit Ptolemaeus. Et soia ea Musica, qua
homines vtuntur, harmonica constat ratione. Ea igitur, quę intellectu
tantùm consideratur, philosophis, & astronomis; &, quae solo au rium
sensu percipitur, vtpote irrationali, irrationalibus animantibus
relicta: hac de Musica, quę sensus & rationis iudicium admittit, & non
solùm propter naturalem vocum, aut sonoru suauitatem, sed propter
consonantias, & reliqua interualla, quae iuxta numerorum harmonicorum
rationes disposita sunt, delectat, ac docet, scribere instituimus, &
ostendere nostri seculi hominibus, vnde tot, ac tam variae sectae
inter eos, qui de Musica scripserunt, ortae sint, vt aliquando tandem
eos, qui eius vsu duntaxat gaudent, cum his, qui ipsius speculationi
dediti sunt, conciliare possimus. Cuius definitionem, ratio atque ordo
doctrinae postulat, vt ante omnia in medium afferre tentemus.

** [Chapter 1.2]
De Musicae instrumentalis definitione, & diuisione.

C A P. II.

AEc ergo Musica, quae sensus, & rationis iudicio perficitur (vt eam
definit Aristides, inter Graecos autor non ignobilis, in principio
suae Musicae) est modulandi, & eorum, quae ad modulandum pertinent,
scientia. Quae definitio non multùm discrepat ab ea, quam tradit
D. Augustinus lib. primo de Musica, vbi illam esse ait, benè modulandi
scientiam. Scientia autem (vt idem asserit Aristides) est, cuius
cognitio firma est, & ab omni errore prorsus aliena: qualia sunt
principia Musicae, quę à Mathematicis (vt ipse ait) apotelesmata
dicuntur, neque alterationem aut mutationem vllam recipiunt. Dicta
autem Musica fuisse videtur à Musis, quibus omnipotentiam canendi
tribuebat antiquitas. Haec igitur Musica instrumentalis prima sui
diuisione diuiditur in Theoreticen, & Practicen. Theoretica est, quae
circa rerum musicalium contemplationem versatur, sola earum cognitione
contenta. Practica verò,quae iuxta artis praecepta artificiosè , & cum
delectatione modulatur. Theoretica rursus diuiditur, in Harmonicam, &
Rhythmicam. Harmonica est (vt definitur à Ptolemaeo primo harmonicorum
libro) facultas, differentias sonorum secundum acutum, & graue
perpendens. Quae tota circa instrumentalis harmoniae compositionem
versatur, & lonos ad harmoniam aptos, reiectis ineptis, considerat. Et
interualla harmonica, quae ex eorum permixtionibus fiunt, vt tonos, &
semitonia; & consonantias vt Diapason, & Diapente; & reliqua, quae
sunt ad eam necessaria; & quibus numerorum proportionibus respondeant,
exacto iudicio rationis inquirit. Quorum vsum docet in praxi Musica,
quam vocant planam, siue vniformem, in qua puer vocem ad harmoniam
aptam formare, & eam per harmonica mouere interualla docetur,nihil
curans multumne an parum temporis in sonorum prolatione consumat; sed
quantum eam attollere, aut ponere debeat. Rhythmica est, quae metitur
diuersas pronunciandi moras, temporum ordine in celeritate, &
tarditate seruato. Quae non quantum vox poni, aut tolli debeat in
harmonicis interuallis considerat: sed quantum, in cuiusque soni, aut
vocis enunciatione, morae faciendum sit, maxima cum ratione
perpendit. In quo primùm tempora considerat; & vnius moram, quae
minima est, breui syllabae, aut notae, duorum verò longae
tribuit. Deinde pedes, qui ex syllabis, aut notis tam breuibus, quàm
longis fiunt, ad Rhythmum aptos, explosis ineptis, examinat. Postremò
Rhythmos ipsos inquirit, qui constant ex pedibus ritè copulatis, & in
celerum, ac tardorum motuum ordine constituti reperiuntur. Quę omnia
in cantu, quem figuratum, aut mensuralem Itali vocant, & in
modulationibus, quae in Musicis fiunt instrumentis, ex figurarum
diuersitate auribus percipiuntur. His autem duabus Antiqui Metricam
adiunxerunt, ea verò est teste Cassiodoro, quae mensuras diuersorum
metrorum probabili ratione cognoscit, vt de heroico,iambico. neque
enim , vt Rhythmica, Rhythmum solùm considerat, qui ex pedibus ritè
copulatis (vt dictum est) sine certo fine quantumlibet in longum
protrahitur, vt fit in modulationibus, in quibus nullus est certus
finiendi modus: sed metrum etiam, quod certo fine clauditur, ad quem
cum peruenit, ad caput redit; vt accidit in vulgaribus cantilenis, &
hymnorum ac psalmorum canticis: & diuersorum metrorum diuersos esse
modulandi modos ostendit. Ex qua omnium metrorum genera ortum habuêre,
quae omnibus linguis, & nationibus, si rectè considerentur, sunt
eadem, vt luce clariùs manifestum erit, cum de hac parte tractationem
instituemus. Et has tres Musicae partes (si credimus Aristidi) qui
perfectionem in cantu assequi volet, obseruare debebit: Harmonicam, vt
sciat vocem à loco ad locum mouere, neque eam aut grauiorem, aut
acutiorem faciat, quàm ratio postulat interualli: Rhythmicam, vt
Rhythmos, & eorum plausum intelligat, & canere ad numerum, quem aërem
recentiores vocant, appositè norit: Metricam,vt modulationem
conuenientem metris coniungat, neque trochaicis iambicorum modos
adaptet; sed verba notis, & notae verbis per omnia conueniant. Vtrùm
autem haec diuisio in tres partes, an potiùs in duas ab antiquis fieri
debuerit, sexto libro, cùm de metris agemus, conuenientiùs
examinabimus. Interim de harmonica quoniam harmonia prior est Rhythmo,
prius quàm de Rhythmica nobis habendus est sermo, & qui sint in ea
iudices, quanto breuiùs poterimus, explicandum.

** [Chapter 1.3]
Quòd non solùm sensus, sed rationis etiam iudicium in Harmonica sit
necessarium. CAP. III.

Vnt autem in Harmonica iudices sensus, & ratio, sed non eodem
modo. Quia, vt Ptolemaeus ait, sensus iudicat iuxta materiam, &
affectionem, ratio verò iuxta formam, & causam. Ex quibus verbis elici
potest, quòd, sicut materia à forma, sic iudicium sensuale perficitur
à rationali. Est autem sensus proprium, per se quod vero proximum est
inuenire, & à ratione integritatem accipere: rationis autem contrà, à
sensu quod verò proximum est accipere, & per se ipsam integritatem
inuenire. Nam quod ille confuse in ipsa materia fluida instabilique
cognoscit, haec a materia denudatum integrè, vt verè est, exactéque
dijudicat. Quare non solùm aurium, sed rationis etiam iudicium in
harmonica necessariu est, neque vnum sine altero potest esse
perfectum. Aurium namque iudicium necessarium est; quia prius est
tempore; ac nisi illud praecedat, ratio munere suo fungi non potest:
imperfectum verò, quia, nisi à ratione adiuuetur, mancum omnino, &
debile reperitur. Rationis autem contrà, videtur enim quodam modo esse
imperfectum, quia ratio pars est intellectus, neque hic cognoscere,
neque illa iudicare quicquam potest: nisi quod per sensus tanquam per
fenestras introierit. sed valde necessarium, quia ad minutissimas
vsque differentias pertingit, quas sensus nequaquam valet
dijudicare. Sensus tamen & ratio sic se habent in harmonica, vt,
quicquid ille probat in sonis, haec ita se habere ostendat in numeris:
ne quicquam auribus, rationique possit esse contrarium. Cum ergo
auditus circa sonos versetur, ratio verò maximè vim suam ostendat in
numeris: priùs, quàm sonos numeris comparemus, ostendamusque, &
numeris sonos, & numerorum proportionibus consonantias, ac reliqua
interualla respondere , aliqua de numeris, ac de eorum inter se
comparationibus necessariò praemittenda sunt. Quandoquidem (vt Boëtius
Seuerinus ait primo de Arithmetica libro) omnia quaecunque a primaeua
rerum natura constructa sunt, numerorum videntur ratione formata. Et,
vt asserit Aristot. 2. physicorum libro, ipsae proportiones sunt
formae, aut causę formales interuallorum, & consonantiarum. Nam, vt
illic ait, illius concentus, qui omnes sonos complectitur, hoc est,
Diapason causa formalis, est ratio duorum ad vnum. Haec autem omnia
latè prosequemur, si priùs breuiter, quod sit ipsius Musicae
subiectum, cuius cognitio valdè necessaria videtur, ostenderimus.

** [Chapter 1.4]
Quod sit Musice facultatis subiectum, & Dtrùm media an Mathematica
dicenda sit, & eam Arithmeticae subalternari.

CAP. IIII.

EX his quae dicta sunt, facilè perspicitur, Musicae subiectum esse non
posse numerum tantùm per se sumptum; cuius iudicium ad rationem, & non
ad sensum spectare videtur: neque sonum seorsùm consideratum, qui
sensus, & non intellectus obiectum est: sed quoddam tertium ex vtroque
conflatum, quod numerus sonorus appellatur. Est autem numerus sonorus,
numerus partium corporis sonori, quod rationem discreti accipiens, &
per numeros in partes diuisum, ducit nos in cognitionem quantitatis
tam soni ab eo producti, quàm diuersorum sonorum ex partibus ipsius
cum eo, & inter se comparatis prouenientium. Vocamus autem corpus
sonorum, siue spatium in Musica chordam, aut neruum, aut cannam, aut
aes tinnulum, & quicquid reperitur, ex quo sonus harmonicus elici
potest. Variatur autem sonus ex variatione numeri, qui chordam, aut
cannam metitur. alius namque sonus est cannae trium palmorum, & alius
sex. Et si chorda ita tensa sit, vt sonum harmonicum efficiat, & in
quinque partes diuidatur aequales, eiusque portio, quae est vt tria, &
ea, quae est vt duo, per ponticulum distinctae simul percutiantur:
sonus partis, quae est vt duo, erit acutior sono partis, quae est vt
tria, in Diapente consonantia. Et si in duas diuidatur medietates, &
primum tota percutiatur; deinde posito in medio digito, vel
ponticulo,altera pulsetur medietas; experiemur ad sensum, sonum
prouenienten ex totius percussione grauiorem esse sono, quem reddet
medietas, & alterum ab altero per Diapason consonantiam distare. Vnde,
cognita per numerum secundum longitudinem quantitate chordae, quae sit
vniformis, ac regularis, statim possunt à nobis soni, iuxta certas ac
determinatas grauis, & acuti differentias, inuicem comparari. quibus
eo modo, quo dictum est, inuestigatis, & à nobis sic primò cognitis,
varias postea de illis demonstramus affectiones. Et quia haec omnia, &
quaecunque alia à Musicis considerantur, ad perfectam potissimùm
numeri sonori cognitionem diriguntur: manifestè apparet, eum esse
verum Musicae facultatis subiectum. Iuxta quam positionem
Aristoteles 2. physicorum, & omnes, qui eum secuti sunt, asserunt,
Musicam nec Mathematicam tantùm, neque Physicam esse; sed mediam inter
vtramque dici oportere. Nam quatenus sonum considerat, ad physicam
spectare videtur: quandoquidem sonus nisi in materia, & sine motu nec
esse,nec definiri potest. vnde ipsius considerationem necesse est, ad
Physicum pertinere. Numerus autem & abstractus à materia, & sine motu
definiri potest, & considerari, quod mathematicarum est
proprium. Nihilominus tamen mathematica videtur esse dicenda; tum quia
Musicus non considerat sonum, quatenus est res naturalis, sed quatenus
est principium cantus, & vt soni sunt elementa, ex quibus harmonia
constat: neque eorum naturas, vt Physicus, sed differentias, quae
inter eos in acumine, & grauitate consistunt, examinat; quod potiùs
est harmonici, quàm Physici. tum etiam quia soni habent se in Musica
vt materia, & in ratione mensurati; & numeri vt forma,& in ratione
mensurantis. Quare à nobiliori, hoc est, à forma nomen accepit; atque
vna ex mathematicis semper est habita. Et cum ex eis quaeda dicantur
subalternantes, vt Arithmetica, & Geometria; quędam subalternatae, vt
Musica, & Astronomia: Musica dicitur Arithmeticae
subalternari. Quoniam Arithmetica considerat numerum absolutè, &
numerus sic acceptus est eius subiectum: Musica verò considerat eum
contractum, vt est in materia sensibili, hoc est, in corpore sonoro
accepto sub ratione discreti. Et dicitur Arithmeticae subalternari,
non solùm quia subiecti sui partem accipit ab ea, sed quia etiam ab ea
sumit omnia principia, & media suarum demonstrationum. Quae quidem
principia non existimare debemus esse omnes conclusiones, quae in
Arithmetica demonstrantur, neque omnes quae in numeris inueniuntur
proportiones: sed eas tantùm conclusiones, per quas omnes de numero
sonoro passiones possunt demonstrari. Et ex proportionibus numerorum
solùm eas assumit, quae ad generationem consonantiarum, & musicalium
interuallorum sunt aptae: quae sunt paucissimae. Quanquam ineptas
nonnunquam considerat, vt reijciat, quod suis locis
demonstrabimus. Sed priùs de priori subiecti parte, quae numerus est,
quam de posteriori videtur agendum. Et de numero tam simplici, quàm
relato breuiter ea, quae ad praesentem attinent institutionem dicenda,
sine quibus Musicae doctrina claudicaret omnino.

** [Chapter 1.5]
De numeri acceptione, & definitione.

CAP. V.

ETquoniam tum naturae ratio certa demonstrat, tum doctissimorum
virorum praecepta nos monent, vt, de quo disputare instituimus, priùs
diligenter exquiramus, quid sit; quàm id, quale sit, explicare
tentemus: de numero harmonico scripturi, ordinem & vi rationis
ostensum, & autoritatum grauitate praescriptum sequemur. Verùm ne in
primo statim limine lector offendat, eum admonendum putauimus, numeri
nomen apud Latinos ambiguum esse. nunc enim quicquid ad numerandi
rationem pertinet, signifieat, yt cum centum, aut decem viros dicimus:
nunc verò per Methaphoram acceptum ad modulandi peritiam, & pedes, &
metra conficienda pertinet: vt cum numerum lambicum, aut Trochaicum
appellamus. In qua significatione accepit eum Maro, cum dixit: numeros
memini, si verba tenerem. Et alibi: Multa vi brachia tollunt in
numerum. Et vox quidem vnica est, notiones vero duae, quas Latini sola
definitione secernere possunt; Graeci verò diuersa etiam appellatione
distinguunt: nam priorem illum Arithmop, posteriorem hunc Rhythmon,
appellare consueuerunt. Et quandoquidem vtriusque consideratio Musico
necessaria est, de priori illo, qui vniuersalior est, priùs erit
considerandum; qui sic à Boëtio definitur: Numerus est vnitatum
collectio. Ex qua definitione ostenditur manifestè, vnitatem non esse
numerum, sed numerandi principium, & ex pluribus vnitatibus numerum
constare. Quae si erunt duae, constituent binarium, qui nil est aliud,
quàm duarum vnitatum nexus, & ternarius trium; ita vt ab vnitate omnis
numerus habeat quod sit vnusqua sublata nullus erit numerus: sublato
tamen numero, non desinit esse vnitas. Diuiditur autem numerus prima
sui diuisione in Parem, & Imparem. Numerus par est, qui potest in duo
aequalia, & duo inaequalia partiri; vt 10. qui potest diuidi,
in 5. & 5. & in 4. & 6. Imparautem est, qui non potest in duo aequalia
partiri: quod accidit propter vnitatis interuentum, quae naturaliter
indiuisa est: & semper in duo inaequalia partitur,
vt 7. in 4. & 3. & 5. & 2. Habent autem hę duę species valde diuersas
proprietates inter se. Nam paris proprium est, vt quocumque modo, siue
in duo ęqualia, siue in duo inaequalia fiat diuisio, si altera pars
sit par, altera necessariò erit etiam par,et si impar, etiam
necessariò erit impar; ita vt nec parilitas imparilitati, neque
imparilitas parilitati misceatur. vt 8. diuiditur in 4. & 4: & 5. & 3:
& in 6. & 2: & 7. & 1. In quibus diuisionibus aut vterque numerus est
par, aut vterque impar. contrà verò imparis proprium est, vt,
quocunque modo diuidatur, necessariò pars aitera sit par, & altera
impar: vt 7. diuiditur in 4. & 3. in 5. & 2. & in 6. & 1. in quibus
diuisionibus neque vtraque pars est impar, sed altera par, altera
impar inuenitur.

** [Chapter 1.6]
De numeri Paris speciebus.

CAP. VI.

RVrsus numeri Paris tres inueniuntur species: quidam enim est pariter
par, quidam pariter impar, & quidam impariter par. Sunt autem pariter
par, & pariter impar veluti oppositi, & impariter par inter eos
medius. Numerus ergo pariter par est, qui pluries in duo aequalia
diuidi potest, donec ad vnitatem naturaliter indiuisam diuisio
perueniat, vt 16. in 8. & 8:8. in 4. & 4:4. in 2. & 2:
& 2. in 1. & 1. Et hi numeri sunt, qui ab vnitate ortum habentes per
duplam progressionem vsque in infinitum procedunt, vt
1.2.4.8. 16.32.64. Pariter impar est ille, qui semel in duo aequa
diuidi potest, vt 6. in 3. & 3. quiam plius in duo aequà diuidi non
possunt. Et hi numeri sunt, qui proueniunt ex duplatione omnium
imparium sine vllo statu in infinitum progredientes. Quod facilè
perspicietur. si disponantur per ordinem ex vna parte omnes impares, &
ex altera omnes pariter impares, vt in hoc typo videre licebit.

|--------------+---+---+----+----+----+----+----+----|
| Impares.     | 1 | 3 |  5 |  7 |  9 | 11 | 13 | 15 |
|--------------+---+---+----+----+----+----+----+----|
| Horum dupli. | 2 | 6 | 10 | 14 | 18 | 22 | 26 | 30 |
|--------------+---+---+----+----+----+----+----+----|

Et sciendum est, quod, quemadmodum pariter pares ortum habent ab
vnitate, quae est omnium numerorum principium; sic pariter impares
oriuntur à binario, qui est omnium parium origo. Et hi omnes semper
inter se vnus post alium quaternario distabunt, vt 2.6. 10.14. In quo
etiam est animaduertendum, quòd sicut vnitas omnes in se continet
virtute numerorum species, & figuras, & diuersis rationibus potest
par, & impar, & quodammodo omnia dici: ita etiam binarius, qui est
illi proximus propter respectus diuersos poterit dici pariter par, &
pariter impar: nam quia eius diuisio vsque ad vnitatem peruenit, & per
duplam progressionem ab vnitate procedit, meritò pariter par
appellatur: et quatenus vnitatis imparis duplus est, & semel in duo
ęqua diuidi potest, inter pariter impares reponi debet. Primus autem
pariter impar sine mistione impariter paris, aut pariter paris
inuenitur esse senarius. Quanquam si propriè loquamur, vnitas neque
par est, neque impar quandoquidem non est numerus, sed omnium
numerorum principium, tam parium quànimparium. Binarius etiam quoniam
est parium origo, impropriè dicetur par. vnde neque erit propriè
pariter par, aut pariter impar: quia neutrius illi conuenit definitio;
sed erit vtriusque principium, & vtrique poterit adaptari. Vocatur
autem vnitas à D. Augustino, principium à quo, & binarius principium
per quod, primo suae Musicae libro. Quibus addit, ternarium primum,
propriè numerum dici debere, & perfectum esse: quoniam principio &
medio & fine constat; in quo valde conuenit cum Aristot. qui primo
li. de celo, Magnitudinum, ait, ea quae in vnum diuidi potest, linea;
quae in duo, extremitas aut planum quae in tria, corpus dicitur. Nec
verò praeter has alia est magnitudo: propterea quòd tribus omnia
continentur, & ter omni ex parte dicitur. Vniuersum enim, & omnia,
tribus, quemadmodum Pythagoraei tradunt, determinata sunt;
quandoquidem finis, medium ac principium vniuersi ac totius numerum
complectuntur, quae eadem illum ternionis continent. Itaque quod à
natura quasi leges illius accepimus in Deorum etiam sacrificijs hoc
numero vtimur. Quin etiam appellandirationes eodem modo attribuimus;
nam duo ambo, duosque ambos, vel vtrumque dicimus, omnes non dicimus,
sed hoc nomen ad tres primum accommodamus. Impariter par est ille, qui
pluries in duo ęqua diuidi potest: sed non toties vt vsque ad vnitatem
perueniat eius diuisio, vt 12. qui potest diuidi in 6. & 6: &
iterum 6. in 3. & 3: sed 3. in duo ęqua ampliùs diuidi non potest. Est
autem hic numerus medius inter pariter parem , & pariter imparem: quia
cum vtroque communicat, & ab vtroque discrepat: communicat quidem cum
pariter pari, quatenus pluries in duo ęqua, sicut ille diuiditur:
discrepat autem ab eo, quia eius in duo aequa diuisio non ad vnitatem
vsque perducitur. cum pariter impari communicat quidem in hoc, quod
non potest vsque ad vnitatem in duo aequa partiri: sed discrepat in
eo, quod pluries, & non semel vt ille in duo aequa diuidi potest. Sunt
autem impariter paris numeri multiplices species: nam quidam bis
tantùm diuidi possunt, vt 12. in 6. & 6: & 6. in 3. & 3. Et hi sunt
omnes dupli omnium pariter imparium. Quod manifestum erit, si
disponantur duae lineae, in quarum altera sint omnes pariter impares,
& in altera omnes primi impariter pares, qui erunt eorum dupli
incipiendo à senario, qui, vt dictum est, est primus pariter impar, vt
hic typus ostendit.

|-----------------------+----+----+----+----+----+----+----|
| Pariter impares.      |  6 | 10 | 14 | 18 | 22 | 26 | 30 |
|-----------------------+----+----+----+----+----+----+----|
| Primi imparit. pares. | 12 | 20 | 28 | 36 | 44 | 52 | 60 |
|-----------------------+----+----+----+----+----+----+----|

Et aduertendum est, omnes hos octonario inter se numero distare, sicut
pariter impares quaternario. Secundi autem ter diuiduntur, et sunt
primorum dupli: vt 24.40.80. & sic sine statu; et ex his quae dicta
sunt, liquidò constabit, ex pariter paribus primum esse quaternarium,
& in infinitum per duplam progressionem protendi; ex pariter imparibus
primum esse senarium, & per additionem quaternarij ad infinitum vsque
procedere: Et ex impariter paribus primum esse duodenarium, & per
additionem octonarij sine statu posse reperiri. &, vt paucis vniuersa
complectamur, quoties quisque vel pariter imparium, vel impariter
parium diuidi potest, totus a ternario duplus, erit eius ordinis
primus, & per toti à ternario dupli additionem procreatur. Et hoc de
Paris numeri speciebus dixisse sufficiat.

** [Chapter 1.7]
De Imparis numeri speciebus. CAP. VII.

SVnt etiam Imparium numerorum tres species: nam quidam eorum sunt
primi & incompositi, quidam secundi & compositi, alij verò inter hos
medij, qui per se quidem accepti sunt secundi & compositi, & cum
altero comparati sunt primi & incompositi, & vocantur contra se
primi. Primus ergo & incompositus numerus est ille, quem sola metitur
vnitas, vt ternarius, & quinarius, quorum sola vnitas est pars
numeratiua, aut multiplicatiua, vel, vt recentiores dicunt,
aliquota. Et ea pars dicitur esse numeratiua, vel aliquota, quae
aliquoties sumpta, ipsum totum restituit: vt binarius est pars
numeratiua senarij: quia ter sumptus senarium restituit: & non est
pars ternarij, aut quinarij, quia bis sumptus ternarium superat, & à
quinario deficit; constituit enim quaternarium, qui ternario maior, &
quinario minor est: ter autem sumptus senarium reddit, qui maior est
quinario. Vnitas vero omnium numerorum est mensura communis; quia in
quemcunque numerum ducatur, ipsum reddit, vt in decem ducta decem, in
centum centum. Et sciendum est, idem esse metiri, quod numerare. Sunt
autem primi & incompositi omnes impares, praeter binarium, qui primus
est parium; ideoque sola ab vnitate numerari potest. Secundus &
compositus est ille, quem praeter vnitatem alius etiam numerus
metitur; vt 9. & 15. quorum priorem praeter vnitatem metitur etiam
ternarius; ter enim sumptus facit nouem, & posteriorem metiuntur idem
ternarius, & quinarius: ille quinquies, & hic ter acceptus. Qui autem
scire volet, quonam pacto hi numeri secundi quasi diuino quodam
artificio generentur à primis, & quam mirabili ab illis ordine
procedant; legat Boëtium priori suae Arithmeticae libro, & Iordanum,
cui plurimùm Arithmeticam omnes debere fatentur. Nos enim Musicam, &
non Arithmeticam profitemur, & ad eius institutionem
properamus. Numeri contra se primi sunt illi, qui (vt dictum est) per
se considerati inueniuntur esse secundi & compositi: & ad alterutrum
collati primi & incompositi naturam participant. cuiusmodi
sunt 9. & 25. quorum priorem metitur ternarius, & posteriorem
quinarius; sed neuter eorum metitur vtrumque. Nam 5. metitur 25. non
tamen 9: & 3. metitur 9. & non 25. Quod non ita euenit in nouenario, &
quindenario: nam vtrumque ternarius metitur, vt superius ostensum
est: 9. & 25. sola vnitas metiri potest, quę, vt dictum est, omnes
metitur numeros. Artem autem, qua hoc demonstrari poterit, trademus
inferius: cum modum docebimus, per quem proportiones ad minimos
numeros, in quibus inueniri possunt, valeant reduci.

** [Chapter 1.8]
De alia divisione numeri Paris digna consideratione, & valde scitu
necessaria.

CAP. VIII.

ESt etiam alia numeri Paris diuisio, quae non minima consideratione
digna videtur. nam parium numerorum quidam inueniuntur esse superflui,
quidam diminuti, quidam autem omnino perfecti. Numerus superfluus est
ille, cuius partes numeratiuae simul sumptae ipsius summam superare
deprehenduntur; vt duodenarius, cuius partes numeratiuae sunt
1.2.3.4.6. quae omnes in summam redactae producunt 16: qui numerus
duodenarium quaternario superat. Diminutus autem est ille, cuius
partes in vnum collectae, à totius summa deficiunt, vt denarius, cuius
partes numeratiuae sunt 1.2.5. qua simul sumptae constitunnt
octonarium, qui denario minor est. Perfectus verò est ille, cuius
partes numeratiuae simul acceptae ipsum restituunt, vt senarius, cuius
partes sunt 1.2. & 3: quae simul sumptae faciunt 6. Et infra decem
vnus senarius reperitur esse perfectus: & infra centum alter, qui
est 28. & infra mille solus 496. & infra decem millia item vnus 8128:
& nullus alius inuenitur vsque ad 130816. In quibus numeris
animaduertendum est, eos ita consequenter dispositos esse, vt primus
in 6.secundus in 8. desinere reperiantur: & sic vnus post alium in his
duobus numeris sunt constituti. Est etiam admirabilis horum numerorum
generatio, atque progressio: nam dispositis ab vnitate, pariter
paribus, qui coniuncti primum fecerint, si in illum extremus ducatur,
perfectum creabunt; vt ex vnitate & binario quia fit ternarius,
binario in illum ducto senarius creatur, ijsdem addito quaternario fit
septenarius, in que ducto quaternario, producitur 28. & quoniam
adiuncto octonario fit 15. qui primus non est, procedendum est
ad 16. & fiet 31. in quem ducto 16. creabitur 496, & sic deinceps, vno
semper intermedio composito relicto, vt in sequentifigura apparet.

|------------------------------------+---+----+---------+---------+---------+---------+---------+----------+-----|
| Pariter pares                      | 1 |  2 |       4 |       8 |      16 |      32 |      64 |      128 | 256 |
|------------------------------------+---+----+---------+---------+---------+---------+---------+----------+-----|
| Eorundem summa                     |   |  3 |       7 | 15. com |      31 | 63. com |     127 | 255. com | 511 |
|------------------------------------+---+----+---------+---------+---------+---------+---------+----------+-----|
| Perfecti ex ultimo in summam ducto | 6 | 28 | positus |     496 | positus |    8128 | positus |   130816 |     |
|------------------------------------+---+----+---------+---------+---------+---------+---------+----------+-----|

Vnum hoc non inutile adiungemus, quod Boëtius Seuerinus etiam
animaduertit, in his numeris similitudinem inueniri vitij & virtutis:
vitium enim aut prouenit ex excessu, aut ex defectu; in virtute autem
neutrum reperitur, sed inter vtrumque medium tenet. & numeri quidem
superflui repraesentant excessum; diminunti verò defectum; & perfecti
virtuntem ipsam referunt, quia sunt inter vtrumque medij. Et quia
multi peccant per excessum, & plurimi etiam per defectum, & quàm
paucissimi medium virtutis amplectuntur; id circo etiam in numeris
superflui, & diminuti quam plurimi reperiuntur, & perfecti quam
paucissimi, vt visum est. Nam, vt Satyricus inquit,

#+begin_quote
Rari quippè boni, vixe sunt numero totidem, quot Thebarum portae, vel
diuitis ostia Nili.
#+end_quote

Sunt autem hi numeri perfecti aut pariter impares, vt 6, aut impariter
pares, vt reliqui omnes, & nullus pariter par: omnes enim pariter
pares sunt diminuti. Ex imparibus verò nullus reperitur perfectus; sed
omnes maxima ex parte sunt diminuti: neque vllus in his reperitur
superfluus usque ad numerum 45045, vt optimè adnotauit lordanus. Et
hoc ingeniosis, & subtilia sectantibus obiter dictum sit: nos autem ad
ea quae reliqua sunt, vt doctrina ipsa postulat, transeamus.

** [chapter 1.9]
De quibusdam figuris Geometricis, quae in numeris inueniuntur, quas
Musicus ex accidenti considerat. CAP. IX.

INueniuntur etiam in numeris omnes figurae Geometricae, ex quibus
nonnullas Musicus considerare debebit, quae prodesse illi poterunt ad
ea, quae paulò pòst de relata ad aliquid quantitate dicenda sunt. Amat
enim (vt Boetius ait) omnis matheseos speculatio alterna probationum
ratione constitui. Quamobrem, antequam de proportionibus, &
proportionalitatibus tractationem instituamus, explicanda sunt nobis
quaedam numerorum, ad figuras pertinentium, nomina; ne, cum ea lector
audierit nominari, aliqua nouitate teneatur. Sciendum est igitur,
aliquos numeros dici quadratos, alios altera parte longiores, alios
verò cubicos. Numerus quadratus est ille, qui prouenit ex alicuius
numeri in seipsum ducti multiplicatione: vt quaternarius est
quadratus; quia nascitur ex binario in seipsum ducto; bis
enim 2. sunt 4. & nouenarius est quadratus; quia nascitur ex
multiplicatione ternarij in seipsum ducti; ter enim 3. faciunt 9. Et
scire oportet, primum quadratum esse eum, qui prouenit ex vnitate in
seipsam ducta, qui erit ipsamet vnitas; semel enim vnu est vnum, quod
in nullo numero potest contingere: omnis enim numerus in seipsum
multiplicatus alium quendam efficit maiorem, quam ipse est. Et, vt
saepe diximus, & saepe dicendum est, omnes numerorum perfectiones
eminenti quodam modo in vnitate consistunt. Est igitur primus
quadratus ex vnitate constitutus, qui vnam habet vnitatem in latere
vt, hic:

|---|
| 1 |
|---|

Secundus vere quaternarius, qui duas, ut hic:

|---+---|
| 1 | 1 |
|---+---|
| 1 | 1 |
|---+---|

Tertius autem nouenarius, qui tres, yt hic.

|---+---+---|
| 1 | 1 | 1 |
|---+---+---|
| 1 | 1 | 1 |
|---+---+---|
| 1 | 1 | 1 |
|---+---+---|

Et sic consequenter per omnes numeros. Et sciendum etiam est, numeros
productos appellari quadratos, illos verò, ex quorum multiplicatione
producuntur, appellari radices. Nam quaternarius est quadratus, &
binarius radix ipsius, & 16. quadratus, & 4. radix ipsius. Et quamuis
non omnis numerus possit esse quadratus, tamen omnes numeri possunt
esse radices: quod manifestè videri poterit, si disponantur omnes
radices, siue numeri naturaliserie in vna linea, & omnes quadratiin
altera, hoc pacto:

|---+---+---+----+----+----+----+----+----+-----|
| 1 | 2 | 3 |  4 |  5 |  6 |  7 |  9 |  9 |  10 |
|---+---+---+----+----+----+----+----+----+-----|
| 1 | 4 | 9 | 16 | 25 | 36 | 49 | 64 | 81 | 100 |
|---+---+---+----+----+----+----+----+----+-----|

Et hoc mirabile videtur inter alia plurima in his numeris, quòd omnes
quadrati nascumtur ex coniunctione numerorum imparium. nam ex vnitate,
& ternario primo impari nascitur quaternarius primus actu quadratus: &
ex vnitate, & ternario, & quinario secundo impari, simul sumptis,
prouenit nouenarius secundus: & sic per additionem vnius imparis
inuenientur omnes quadrati, vt in hoc typo apparet:

|---+---+---+----+----+----+----+----+----+-----|
| 1 | 3 | 5 |  7 |  9 | 11 | 13 | 15 | 17 |  19 |
|---+---+---+----+----+----+----+----+----+-----|
| 1 | 4 | 9 | 16 | 25 | 36 | 49 | 64 | 81 | 100 |
|---+---+---+----+----+----+----+----+----+-----|

Et hęc de quadratis pro prasenti institutione dicta sufficiant. Sut
etiam alij numeri, qui Graecè dicuntur iconirus, & à Boëtio Latinè
altera parte longiores, seu longilateri nominantur, qui sunt etiam
quadrati, sed differunt valdè à superioribus: in illis namque omnia
sunt aequalia, anguli, & latera, & longitudo etiam est ęqualis
latitudini; in his verò ęquales sunt anguli, sed latera inaequalia, &
longitudo maior latitudine. Quamobrem quadrati longi
vocantur. Differunt etiam, quia illi incipiunt ab vnitate, & ex
imparium coniunctione, vt diximus, procreantur, partimque pares sunt,
partim impares; hi verò incipiunt à binario, qui est principium
alteritatis, vt ita loquamur, vnde meritò altera parte longiores
vocantur, & ex parium coniunctione proueniunt, & omnes sunt
pares. Nascuntur autem ex duobus numeris sola vnitate distantibus,
altero in alterum ductis; vt ex vnitate, & binario fit binarius, nam
bis vnum sunt duo: & ex binario, & ternario sit senarius, nam bis tria
sunt sex: & ex ternario, & quaternario duodenarius, ter enim quatuor
faciunt duodecim: & sic in infinitum procedi potest. Diximus autem eos
ex parium coniunctione procreari; quia primus est binarius, qui est
primus par: secundus qui est senarius, sit ex secundo pari cum primo,
hoc est, ex binario, & quaternario: tertius, qui est duodenarius, ex
primo, & secundo, & tertio: nam 2.4. & 6. faciunt 12. Et quartus qui
est 20. fit ex quatuor primis paribus. 2.4.6.8. vt in hoc typo
ostenditur.

|---+---+----+----+----+----+----+----+----+-----|
| 2 | 4 |  6 |  8 | 10 | 12 | 14 | 16 | 18 |  20 |
|---+---+----+----+----+----+----+----+----+-----|
| 2 | 6 | 12 | 20 | 30 | 42 | 56 | 72 | 90 | 110 |
|---+---+----+----+----+----+----+----+----+-----|

Et hæec de multis, quæ dici poterant, de altera parte longioribus
dixisse sit satis. Cubus autem siue cubicus numerus est ille, qui fit
ex quadrato per suam radicem multiplicato, aut ex radice bis in
seipsam ducta: nam ex quaternario in binarium ducto fit octonarius; &
bis duo bis, faciunt octo: & nouem in tria ducta, faciunt 27; & ter
tria ter, sunt 27. Et sciendum est, in hoc numero, aut in figura
cubica, illi respondenti, omnes dimensiones inueniri, longitudinem,
latitudinem, & altitudinem, ex quibus corpus constituitur: quod ex
ipsa numerorum multiplicatione manifestum est; nam cum dicimus, bis
duo bis, duo dicit longitudinem, quia binarius, & quilibet numerus,
primò & per se consideratus, est linearis: Bis duo addit longitudini
latitudinem aequalem, & fit superficies: bis autem, quod postremò
ponitur, addit longitudini, & latitudini altitudinem, siue crassitiem
aequalem; & sic fit corpus. Vnde binarius est numerus linearis,
quaternarius superficialis, octonarius solidus. Et in hoc numero
Cubico inuenitur Geometria, siue proportionalitas harmonica, vt suo
loco demonstrabimus. Et sunt in eo omnia aequalia, anguli , & latera,
& facies Habet autem duodecim latera, octo angulos, & sex facies: quod
in talis siue thessaris conspicari licet. Et primus quidem cubus
potestate est vnitas, secundus verò, aut primus actu 8, tertius 27,
quartus 64. Atque ita in cubis proceditur ab vno ad alterum, vt, si
alter sit impar, alter sit par. Et sic per media progreditur, vt, si
primus numerus sit indiuisibilis, secundus semel diuidatur, tertius
bis, quartus ter: vt in his numeris experiri licet 1. 2.4.8. contrà
verò si primus erit par, & diuidetur ter; secundus erit impariter par
, & diuidetur bis & tertius pariter impar, ac patietur vnam
diuisionem; quartus impar, qui in duo aequa diuidi non poterit: vt
ostendunt hi numeri 8.12.18.27.Et eodem modo , quo progrediemur ab
impari ad parem, regrediemur à pari ad imparem. Et scire oportet,
inter figuras planas rectilineas, quadratam esse optimam, propter
omnimodam ęqualitatem laterum, & angulorum. Atque etiam inter corpora
solida rectilinea cubicum esse optimum, propter aequalitatem laterum,
& facierum, & angulorum, quę in nullo alio solido reperitur. Et haec
sunt, quae necessariò consideranda duximus de numero simplici, & per
se constanti quantitate. lam tandem opus est, vt de numero
relato,atque eius affectionibus, quę ad harmonicam institutionem sunt
necessaria, dicamus.

** [chapter 1.10]
Quid sit Proportio, & quot modis consideretur.

CAP. X.

AD aliquid quantitas est, quae in comparatione ad aliam consideratur:
yt ternarius ad binarium collatus sortitur nomen respectiuum, &
dicitur sesquialter: quae conparatio duarum inter se quantitatum,
vocatur proportio. E S Tautem PROPORTIO (vt ab Euclidis interpretibus
quinto de Geometricis elementis libro definitur) DVARVM, QVANTAECVNQVE
SINT, EIVSDEM GENERIS OVANTITATVM CERTA ALTERIVS AD ALTERAM
HABITVDO. Nam apud ipsum Euclidem Graecè sic habet: ae οfoviα Sgoviui
nora nνdnrura rgs ennda roexi. quod est Latinè: Proportio est duarum
magnitudinum eiusdem generis mutua quaedam secundum quantitatem
habitudo. Et dicitur HABITVDO, quasi quaedam inter duas quantitates
conuenientia, sicut inter homines cognatio, quę potest esse maior &
minor. Nam quemadmodum in hominibus diuersę sunt cognationes, aliae
maiores , & aliae minores, (magis enim cognati sunt germani fratres,
quam consobrini) & alij sunt, qui nullam inter se cognationem habent,
sed sola in humanitate communicant, per cuius participationem plures
homines sunt vnus homo: sic etiam in quantitatibus potest reperiri
maior, & minor conuenientia. Nam magis inter se conueniunt aequales,
qua inęquales. & inter inaequales multae sunt differentiae: aliter
enim se habet quaternarius ad binariu, qui continet eum bis; aliter
senarius ad quaternarium, qui continet eu semel, & eius dimidium; &
aliter quinarius ad ternarium, qui nec continet eum pluries, nec
semel, & aliquam eius partem, sed habent se solùm vt numerus ad
numerum, vel, vt D. Augnstinus eos vocat, vt tot ad tot. Et sicut duo
homines, qui nullam habent cognationem, in sola humanitate; sic
huiusmodi numeri in vnitate sola communicant. Dicitui etiam CERTA, hoc
est, determinata. Et DVARVM QVANTITATVM, quia proportio non reperitur,
nisi in duabus quantitatibus, oportet enim esse quantitate, quae
comparetur, & cui comparetur: & HABITVDO, quę ex ea comparatione
prouenit, vocatur proportio. Dicitur autem QVANTITATVM, quia non solùm
in numeris, sed in continuis quoque reperitur. Et QVANTAECVNQVE sint,
hoc est, finitarum; quia inter infinitas nulla fit comparatio. EIVSDEM
autem GENERIS ideò recte ponitur, quia inter quantitates diuersorum
generum non potest fieri comparatio; vt inter lineam, & superficiem ,
aut inter locum , & tempus: non enim dicitur linea maior, aut minor
superficie: neque spatium, aut locus tempore. Diuiditur autem
proportio prima sui diuisione ab Euclidis interpretibus, &
enarratoribus Latinis in rationalem. & irrationalem. Quamuis ego
proportionem irrationalem impropriè dici existimem, ed quòd omnis
proportio ratio est, atque in ratione consistit. meliùs Gręci, qui
proportionemn hoc est, rationem appellant, & non rationalem &
irrationalem, sed juri & α, quod est dicibilem & indicibilem, esse
dicunt. Sed dicetur irrationalis, cuius ratio confusa est, qualis est
ea, quae non reperitur in numeris, in quibus ratio maximè vim suam
ostendit. Rationalis ergo est, quę reperitur inter duas quantitates
aliqua in parte communicantes, quae sit vtriusque mensura communis: vt
quę reperitur inter duos numeros, quos saltem in vnitate communicare
necesse est. Irrationalis autem est, quę reperitur inter duas
quantitates, nulla in parte, quae vtramque metiatur, communicantes:
vnde à Græecis  vocatur, cuiusmodi est Diametri ad latus in quadrato,
& multę aliae, quae à Geometris considerantur. Differunt autem,
quoniam irrationalis non consideratur in Arithmetica: ipsa enim est de
vnitate, & numero ; & huiusmodi proportio non potest ab aliquo numero,
neque ab vnitate denominari. In Geometria autem vtraque consideratur,
quae tractat de magnitudinibus, ex quibus aliquae sunt
commensurabiles, aliquae non. Constat enim Geometriam considerare
latera quadrati commensurabilia, & Diametrum incomensurabilem lateri,
quae ad Musicae considerationem non pertinent: quoniam Musica, vt
diximus, Arithmeticae subalternatur; & eas solùm proportiones assumit,
quae in illa considerantur. Et inde forsitan irrationales, surdae à
Mathematicis dictae sunt, & ignotae. Ex quibus manifestum est,
irrationales in quantitate continua solùm reperiri, & ad Geometram
earum considerationem pertinere: rationales autem in continua, &
discreta demonstrari, & ab omnibus Mathematicis considerari debere,
sed praecipuè ab Arithmetico, & Musico. Quare relicta Geometris
irrationali, de rationali tantùm nobis habendus est sermo.

** [chapter 1.11]
De proportionis rationalis prima, & secunda diuisione

CAP. XI.

PRoportio rationalis primùm diuiditur in proportionem aequalitatis, &
proportionem inaequalitatis: na quaelibet quantitas, quae alterius
ratione metitur, aut illi ęqualis est, aut inaequalis. AEqualitatis
autem proportio est, quae inter duas aequales quantitates inuenitur, &
in vtroque extremo summam denotat ęqualitatem: vt in numeris, inter
binarium, & binarium; & quaternarium, & quaternarium; & in
magnitudinibus, cùm palmus palmo, aut pes pedi comparatur. Cuius duae
sunt proprietates: altera, quòd natura sua est indiuisa, & (vt Boëtius
ait) eandem seruat in propria moderatione mensuram: altera, quòd duo
extrema eodem nomine nuncupantur. Et quia indiuisibilis est, nullas
habet sub se species, sed uouοis à Graecis appellatur. Ipsa autem
species estRelationis, quam Dialectici vocant AEquiparantiae; cuius
species sunt Vicinitas, Similitudo, Amicitia, AEqualitas. nam sicut
vicinus est vicino vicinus, et amicus amico amicus: sic aequale equali
ęquale. Est itaque proprium quantitatis (vt vult Aristoteles) ęquale,
vel inaequale dici: quemad modum qualitatis simile, vel dissimile. Fit
autem aequalitas ex multiplicatione ab vnitate denominata: vt ex
binario in vnitatem ducto fit binarius: quandoquidem vnitas in
quemcunque numerum ducatur, ipsum restituit: multiplicatio autem à
numero denominata efficit multiplicitatem; à binario quidem
duplicitatem, à ternario triplicitatem, atque ità deinceps: vnde
nascitur proportio inaequalitatis. quae duplex est; maioris
inaequalitatis, & minoris inaequalitatis. Proportio maioris
inaequalitatis est, in qua maius comparatur minori: vt 4. ad 2,
bicubitum cubito. Et est species relationis, quam logici
superpositionis appellant. Quae est illa, in qua relatum habet
dignitatem quandam super illud, ad quod refertur; vt paternitas in
patre super filium, dominium in domino super seruum. Vnde Relatiua
superpositionis dicunt respectum excedentis ad excessum, id est,
maioris ad minus; cuius species sunt duplum ad subduplum, triplum ad
subtriplum, & sic ascendendo in numeris; & vt dominus ad seruum, pater
ad filium. Proportio minoris inaequalitatis est, in qua minus
comparatur maiori: vt 2, ad 4; & 3. ad 6; cubitum bicubito. Haec
species est tertij generis subalterni eorum, quae ad aliquid sunt, &
dicitur suppositionis. Quae est illa, in qua relatum esse videtur
indignius illo, ad quod refertur, vt filiatio in filio erga patrem, &
seruitus in seruo erga dominum. Species autem suppositionis sumuntur è
conuerso, vt subduplum ad dupium, subtriplum ad triplum, seruus ad
dominum. Et quemadmodum superpositio, & suppositio non sumuntur, vt
sub, & supra in linea praedicamentali, ita, vt vnum praedicetur de
altero; sed opponuntur relatiuè: sic etiam proportio maioris inęqua
litatis, & proportio minoris sunt diuersorum generum; sicut proportio
aequalitatis, & proportio inaequalitatis. Est autem proprium horum
duorum generum inęqualitatis, quòd naturaliter diuidi possunt, & sub
se plures habent species; quod est contrarium generi aequalitatis:
atque etiam, quòd diuersa nuncupatione funguntur, vt
cum 10. comparantur ad 5. Sed differunt inter se, quia in proportione
maioris aequalitatis fit comparatio secundum excessum, & continentis
ad contentum: & in proportione minoris inaequalitatis secundum
defectum, & contenti ad continens. Habent se igitur quodammodo vt
actionis & passionis praedicamenta. Et differunt etiam in hoc quod
proportionis maioris inaequalitatis omnes sunt aequa proportione
maiores, minoris verò minores, vt in sequemti figura apparet, in qua,
ternarius in medio positus, numeris superioribus collatus constituit
primò aequam proportionem, deinde aequa paulò maiorem
superparticularem, mox superpartientem, tam aequa quàm
superparticulari maiorem, & sic deinceps in singulis generibus;
inferioribus autem numeris collatus primò aequam, deinde hac minorem
subsuperparticularem, mox vtrauis harum minorem subsuperpartientem,
reliquasque aliam alia minorem.

|------------------------+-----------------+-------------------+---------------+-----------+-----------------------------+-------------------------+------------------------+
|                        |               3 |                 4 |             5 |         6 |                           7 |                       8 | Maioris inaequalitaris |
|------------------------+-----------------+-------------------+---------------+-----------+-----------------------------+-------------------------+------------------------+
| Minoris inaequalitaris |               3 |                 3 |             3 |         3 |                           3 |                       3 | Maioris inaequalitaris |
|------------------------+-----------------+-------------------+---------------+-----------+-----------------------------+-------------------------+------------------------+
| Minoris inaequalitaris |               3 |                 4 |             5 |         6 |                           7 |                       8 |                        |
|                        | Aequa proportio | Superparticularis | Superpartiens | Multiplex | Multiplex superparticularis | Multiplex superpartiens |                        |

Et, vt in summam ea, quae dicta sunt, redigamus, quicquid alteri
comparatur, aut illi aequale est, aut inaequale. Comparatio autem
inter aequalia semper vno eodemque fit modo: inter inaequalia verò fit
duobus modis; nam aut maius coparatur minori, aut minus maiori. Quax
duae comparationes quamuis materia sint eędem, differunt tamen forma,
& diuersa ex illis oriuntur genera proportionum. Sicut enim ex
comparatione patris ad filium oritur paternitas, & ex filij ad patrem
filiatio (quae diuersae sunt relationes) sic ex conparatione maioris
ad minus oriuntur aliae proportiones, quàm ex comparatione minoris ad
maius. Quarum species, iam tandem opus est, vt explicare tentemus.

** [chapter 1.12]
De speciebus proportionum tam maioris, quàm minoris inaequalitatis, &
de genere multiplici, & submultiplici.

CAP. XII.

PRoportio maioris inaequalitatis habet sub se quinque species, &
totidem habet proportio minoris inaequalitatis. Sunt autem maioris
inaequalitatis species (quae etia genera subalterma, respectu suorum
inferiorum, nominari possunt) Multiplex, Superparticularis,
Superpartiens, Multiplex superparticularis, & Multiplex
superpartiens. Atque eadem erunt nomina specierum proportionum minoris
inaequalitatis, praeposita, sub, prępositione, vt Submultiplex,
Subsuperparticularis, Subsuperpartiens, & sic de reliquis. Atque
eadem, quae dicentur de proportionibus maioris inaequalitatis,
intelligi poterunt dicta esse è conuerso de proportionibus minoris. Ex
his autem quinque generibus tria sunt simplicia, Multiplex,
Superparticulare, Superpartiens, & duo composita, Multiplex
superparticulare, & Multiplex superpartiens. Multiplex genus est, in
quo numerus maior, minori comparatus, continet eum pluries adaequate,
ita vt nihil deficiat, aut superet: vt 4. continet
2.bis, 9. continet 3. ter, 20. quater 5, & sic de reliquis. Habet
autem sub se species plurimas: nam, si maior numerus continet minorem
bis, dicitur dupla, quolis est 8. ad 4, 12. ad 6; si ter, vocatur
tripla, vt 12. ad 4,6. ad 2; si quater, quadrupla; & sic sine
statu. Idem intelligi debet de submultiplici; (vt dictum est) quod
est, cùm numerus minor, maiori comparatus, continetur ab eo pluries
adęquatè. & si bis continetur, est proportio subdupla, vt 3. ad 6; si
ter, subtripla, vt 5. ad 15; & sic etiam sine statu: atque ita in hoc
genere semper numerus minor est pars numeratiua maioris; quod in nullo
alio potest euenire. Est etiam huius generis proprium, quòd in eo
reperitur minima proportio, & non maxima. Est autem minima, dupla:
quia in ea numerus maior continet minorem bis; neque minùs continere
potest, si pluries continere debet. Et sic inuenitur in primo numero
ad vnitatem collato, qui est binarius: & est prima proportionum
inaequalitatis; quia proximè omnium ad aequalitatem accedit. Et
sciendum est, ad vnitatem omnes numeros collatos esse multiplices: nam
binarius est duplus, ternarius triplus, quaternarius quadruplus; & sic
in infinitum potest procedi. Atque haec ita nota sunt, vt non multùm
in eis immorari debeamus: quoniam de his plurimi scripserunt, & nos ad
ea, quae sunt Musicae propria, properamus, quae sunt in Arithmetica
exactiora, ipsius professoribus relinquentes.

** [chapter 1.13]
De genere superparticulari, & subsuperparticulari.

CAP. XIII.

POst genus Multiplex, quod omnium primum est inaequalitatis, quia
inter primos numeros inaequales (vt diximus) inuenitur, statim
sequitur genus superparticulare, nam sicut prima multiplicium
reperitur inter duo, & vnum: sic prima superparticularium inuenitur
inter 3. & 2. Atque ita ab aequalitate ad inaequalitatem ordinatim
proceditur: quoniam aequa proportio, quae est omnium mater & origo,
inuenitur inter duas vnitates, quibus nihil potest minus comparari; &
Multiplex, quod est primum inaequalitatis inter duo, & vnum; &
Superparticulare in ternario ad binarium collato, neque in minoribus
numeris inueniri potest. Quamquam si quantitatis ordinem spectes,
genus aequalitatis non multiplex, sed superparticulare & superpartiens
sequuntur, quorum proportiones inter aequam & duplam inueniuntur, vt
in numeris ordine cum ternario collatis in typo capitis vndecimi
videre licet. Est autem genus Superparticulare, cum maior numerus
minori collatus continet eum semel, & aliquam partem minoris
numeratiuam; quae si erit secunda, vel dimidia, efficiet proportionem
sesquialteram; vt 3. ad 2, 6. ad 4; nam ternarius continet binarium, &
vnitatem, quae est illius dimidium; & sex 4, atque insuper binarium,
qui est ipsius dimidium: & si erit tertia pars, constituetur proportio
sesquitertia; quae in minimis eius numeris inuenitur inter 4. & 3: &
si quarta pars, sesquiquarta, vi 5. ad 4: & sic habet species
plurimas, per quas sine statu potest procedi, addita semper vnitate,
vt 6. ad 5,7. ad 6. Et denominabuntur à minori numero praeposita hac
particula, sesqui, vt sesquiquinta sesquisexta: aut ab ea parte
minoris, in qua maior eum superabit: vt ea, quae est à 9. ad 8,
dicitur sesquioctaua; quia vnitas, qua maior minorem superat, est
octaua pars illius. Habet autem hoc genus proprietatem omnino
contrariam ei, quam diximus multiplex habere: quoniam in illo
inuenitur minima proportio, quae est dupla, & non maxima; in hoc verò
datur maxima, & non minima. nam sesquialtera, quae est ipsius prima
species, est omnium maxima; & sesquitertia proxima; & sic minuendo in
infinitum, nec minima poterit inueniri. Maior autem proportio est ea,
quae denominatur à minori numero, & a maiori parte: vt sesquialtera,
quae etiam dicitur sesquisecunda, & denominatur à minimo numero, qui
est binarius, & a maxima parte, quae est dimidium: & sesquitertia a
ternario, qui est maior quàm binarius, & à tertia parte, quae est
minor quàm dimidium. Quare maior (vt diximus) proportio denominabitur
in hoc genere à minori numero, & à maiori parte: & minor à maiori
numero, & à minori parte. Nec potuit hoc genus inueniriinter duo, &
vnum: quia (vt diximus) omnes numeri ad vnitatem sunt multiplices,
quae quoniam indiuisibilis est, nullas habet partes, in quarum aliqua
possit ab vllo numero superari. Et quia breues esse studemus, haec de
genere Superparticulari dicta sufficiant: si tamen hoc solum
admonuerimus, genus subsuperparticulare ab hoc sumi è conuerso; & esse
illud, in quo minor numerus continetur à maiori semel, & aliqua pars
ipsius numeratiua, vt binarius ad ternarium; & tot, & easdem species
habere cum superparticulari, sed nominari praemissa, sub,
praepositione, vt subsesquialtera, subsesquitertia, & sic per omnes,
quotquot voluerimus inuenire.

** [chapter 1.14]
De quibusdam consideratione dignis circa tria genera simplicia; Multi¬
plex, & Superparticulare, & Superpartiens: quae etiam pertinent ad duo
composita

CAP. XIIII.

HAEc duo genera, de quibus locuti sumus, vnicè, & tanquam sacrosancta
(vt Porphyrius ait super Harmonica Ptolemaei) venerabatur antiquitas:
alterum propter ordinem, & alterum propter simplicitatem. In priori
namque idem, qui & in numeris, custoditur ordo: vt enim illi ab
vnitate per binarium, & ternarium, & qui sequuntur naturali procedunt
ordine: sic etiam multiplices à dupla per triplam, & quadruplam eodem
ordine progrediuntur; ita vt in eis semper comes sit pars numeratiua
ducis. Vocantur autem duces numeri maiores, & comites minores, vt in
proportione 6. ad 3, senarius est dux, & ternarius comes. In
superparticulari verò summa reperitur simplicitas: quandoquidem omnes
eius generis proportiones in suis radicibus inter numeros sola vnitate
distantes inueniuntur: quae simplices nuncupantur, quia sine aliarum
commercio nascumtur, vt in sesquialtera, quae à ternario ad binarium
inuenitur, nullus est numerus, qui intercidat. Quod aliter accidit in
omnibus multiplicibus, praeterquàm in dupla; in tripla enim, quae
inter 3. & vnum inuenitur, binarius intercidit, qui ad vnitatem est
duplus, & ad ternarium subsesquialter: quare in sua radice ex
commercio duplae, & sesquialterae nasci reperitur. Sola dupla (vt
diximus) habet hoc commune cum superparticularibus, quòd inter numeros
sola vnitate distantes inuenitur, & sine alterius proportionis
commercio procreatur; nam inter binarium, & vnitatem potest inueniri,
qui proximè ad duas vnitates, in quibus aequa consistit, accedunt,
neque ab vllo numero possunt intercipi. Et si autem numeri duplae sint
inaequales, hoc tamen habent maxim è aequalitatis, quòd excessus est
ęqualis ei, quod exceditur: quandoquidem binarius vnitatem excedit
vnitate, quae est vnitati aequalis; quod nulli alij potest
contingere. Inueniuntur praeterea in his duobus generibus duae
quantitatis species expressae, quoniam multiplex seruat quantitatis
discretae proprietatem, superparticulare autem continuae. quemadmodum
enim in continui diuisione, ita in hoc numeri semper augescunt:
multiplices verò proportiones numerorum ordinem custodiunt, quod est
proprium quantitatis discretae. & sicut partes decrescunt, quod est
proprium continuae: sic etiam semper superparticulares minuuntur; ita
vt sesquialtera sit earum maxima, & à maxima denominetur parte, quae
est dimidium; & sesquitertia sit illa minor, quia tertia pars minor
est dimidio; & sesquiquarta minor sesquitertia, & sic quae deinceps
sequuntur: quia minores erunt partes, a quibus denominabutur. & vt
partes decrescunt, ita numeri succrescunt; sicut in sesquidecima, pars
decima minor est, quàm nona, numerus verò denarius maior, quàm
nouenarius. Hoc etiam animaduertendum est, duplam (quae minima est
multiplicium) maiorem esse sesquialtera superparticularium maxima:
quin potiùs duas superparticularium maximas, quae sunt sesquiaitera, &
sesquitertia, duplam aequare; neque alias duas id efficere posse, vt
in his numeris percipi potest. 2.3.4;a 4.ad 2. dupla,
à 3. ad 2. sesquialtera, à 4. ad 3. sesquitertia. Tertij verò generis,
& reliquorum parua, aut nulla mentio fit apud Graecos: sed omnes quae
in eis proportiones consistut, vocant vt numeri ad numerum. volentes
significare, nullam inter eos numeros praeter numeralem cognationem
inueniri, vt 5. ad 3, & 7. ad 2. Et D. Augustinus vocat huiusmodi
proportiones vt tot ad tot: & ex his quinque generibus duo tantum
facit, alterum, quod appellat connumeratorum, alterum
dinumeratorum. Et connumeratos quidem dicit eos esse, in quibus aut
maior aliqua sui parte coaequatur minori, aut eum exuperat, vt in his
numeris, 4. ad 2, & 8. ad 6: in quorum prioribus maior dimidia sui
parte minori coaequatur; & in posterioribus maior quarta sui parte
minorem exuperat. Dinumeratos autem eos esse dicit, in quibus neutrum
horum inueniri potest, vt in his numeris, 10. ad 3, & 4. ad 11: in
quibus neque ternarius est pars denarij, nec quaternarius vndenarij;
neque in his, 9. & 5, quinarius nouenarij. quibus exemplis ostendit,
superpartiens, & duo composita sub dinumeratis contineri: neque de his
magnam esse curam habendam, vt quae multùm recedant à simplicitate, &
ordine connumeratorum. Rursus connumeratos diuidit in complicatos, &
sesquatos: vt complicati sint, quos Boëtius, atque alij Multiplices
vocant: sesquati verò, qui superparticulares appellantur, vt
sesquialter, sesquitertius, in quibus (vt ostensum est) haec
particula, sesqui, semper inuenitur. Sunt & alij recentiores, qui duo
tantùm genera faciunt, Multiplex, & Partiens. Et Multiplex esse
dicunt, in quo maior numerus ita pluries minorem continet, vt nil
deficiat, aut superet: Partiens autem, in quo maior numerus semel, aut
pluries minorem contineat, & semper aliquid superet; nihil curantes
sitne id, quod superat, pars, an partes: atque ita ex quatuor
generibus vnum tantùm constituunt. Sed nos antiquorum, & doctissimorum
vestigijs insistentes, communi incedemus via: quia facilior, & ad
praesens institutum accommodatior est.

** [chapter 1.15]
De genere superpartiente, & subsuperpartiente.

CAP. XV.

SVperpartiens igitur genus est tertium in ordine, & superparticulare
sequitur: quia sicut Multiplex incipit ab vnitate, & superparticulare
ortum habet à binario; ita superpartiens initium sumit à ternario, qui
binarium sequitur. Est ergo genus superpartiens, cùm maior numerus
minori collatus continet eum semel, & aliquas eius partes, duas, aut
tres, aut plures, ex quibus non possit vna conflari, quae minorem
metiatur: vt in hac proportione, à 5. ad 3, in qua quinarius continet
ternarium semel, & duas eius partes, ex quibus non potest fieri vna
pars, quae ternarium metiatur: quia, si fieri posset, reduceretur ad
multiplex, vel ad superparticulare: vt in hae proportione,6. ad 4,
senarius cotinet quaternarium, & duas eius quartas: sed quia duae
quartae constituunt dimidium, quae est vna, & maxima pars quaternarij;
non superpartiens, sed superparticularis, & sesquialtera dicenda
est. Est autem hoc genus amplissimum, & latissimum, & habet sub se
plura genera, quae plurimas habent species: & haec genera denominantur
à numero partium, quibus dux comitem superat, quae si erunt duae,
dicetur superbipartiens; si tres, supertripartiens; si quatuor,
superquadripartiens; & sic deinceps, ita tamen vt partes non adęquent
minoris summam, vt à 99. ad 50. quia maior superat minorem
quadragintanouem partibus, dicetui superquadragintanonipartiens
quinquagesimas: quod si maior fuisset centum, esset dupla proportio:
vnde sequitur,quòd omnis superpartiens semper erit minor dupla,
quantumcunque ad eam proximè accedat. Et sciendum est, quòd
superbipartiens incipit à ternario, quia in nullo minori numero
possunt duae partes inueniri; & supertripartiens à quaternario, quia
is primùm potest habere tres sui partes, & sic deinceps consequenter,
dispositis ex vna parte naturali serie numeris à ternario
incipientibus, & ex altera numeris imparibus à quinario, partium
excessum habentibus, vt in hoc typo perspici poterit.

|---------------------------+-------------------+---------------+------------+-------------+------------+---------+---------+---------+----------+----------+----------+----------+----------+----------+----------+----------+----------|
| Numeri natiua seriei a 3. |                 3 |             4 |          5 |           6 |          7 |       8 |       9 |      10 |       11 |       12 |       13 |       14 |       15 |       16 |       17 |       18 |       19 |
|---------------------------+-------------------+---------------+------------+-------------+------------+---------+---------+---------+----------+----------+----------+----------+----------+----------+----------+----------+----------|
| Impares a 5.              |                 5 |             7 |          9 |          11 |         13 |      15 |      17 |      19 |       21 |       23 |       25 |       27 |       29 |       31 |       33 |       35 |       37 |
|---------------------------+-------------------+---------------+------------+-------------+------------+---------+---------+---------+----------+----------+----------+----------+----------+----------+----------+----------+----------|
|                           | Superbipartientes | Supertripart. | Superquad. | Superquint. | Supersext. | Super 7 | Super 8 | Super 9 | Super 10 | Super 11 | Super 12 | Super 13 | Super 14 | Super 15 | Super 16 | Super 17 | Super 18 |

In his primum est superbipartiens, secundum supertripartiens, & sic
deinceps omnia nomen sortiuntur à numero partium, quibus numeri
minoresà maioribus superantur. Sed horum generum vnumquodque habet
infinitas sub se species, denominatas quidem illas à nominibus
diuersarum partium, vt à tertijs, quartis, quintis, atque ita
deinceps. Nam superbipartiens, si duae partes, quibus maior superat
minorem sunt tertiae, dicituf superbipartiens tertias, yt in hac
proportione 5. ad 3, in qua duę partes, quibus quinarius superat
ternarium, sunt duae tertiae ternarij: si autem erunt quintae, dicetut
superbipartiens quintas, vt 7. ad 5. Et aduertendum est, in hoc genere
semper oportere numeratorem partium esse minorem, quàm denominatorem,
vt in his; superbipartiens tertias, supertripartiens quartas; in
quibus minor est numerator duarum, aut trium partium, quàm denominatot
tertiarum, aut quartarum. Atque etiam sciendum est, quòd si alter,
siue numerator, siue denominator, sit par, necessariò alter erit
impar, vt superbipartiens tertias, & supertripartiens quartas;
impossibile autem est vtrumque esse parem, nec enim rectè dicas
superbipartiens quartas: possibile verò est, vtrumque esse imparem, &
dato vno impari reliquum esse parem; nisi numerum aliquem, praeter
vnitatem, communem mensuram admittant; itaque rectè dicitur
supertripartiens quintas, & supertripartiens septimas, non aute
supertripartiens sextas, aut supertripartiens nonas, quòd in his
communis mensura est ternarius, illi autem numerum, praeter vnitatem,
communem mensuram nullum admittunt, sed sunt contra se primi. Sed,
quia, si credimus Senecae, praeceptorum iter longum est, ac difficile,
exemplorum autem breue, & efficax; duos, aut tres apponemus typos, in
quibus haec omnia, oculis subiecta, planiùs ac manifestiùs
intelligentur: & in primo erunt superbipartientis species, quarum
radices inuenientur in omnibus imparibus numeris, secundo ad primum, &
tertio ad secundum, & sic deinceps comparatis, in secundo & tertio
typo supertripartientis; in quarto & quinto superquadripartientis
species continentur.

|------------------------------+---+-------------+---+---------+---+-----------+---+-----------+----+------------+----+------------+----|
| Numeri binario se excedentes | 3 |             | 5 |         | 7 |           | 9 |           | 11 |            | 13 |            | 15 |
|------------------------------+---+-------------+---+---------+---+-----------+---+-----------+----+------------+----+------------+----|
| SVPERBIPARTIENTES.           |   | Supbitertij |   | supbi 5 |   | superbi 7 |   | superbi 9 |    | superbi 11 |    | superbi 13 |    |
|------------------------------+---+-------------+---+---------+---+-----------+---+-----------+----+------------+----+------------+----|

|----------------------------+---+-----------------+---+-------------+----+--------------+----+--------------+----+--------------+----|
| A 4 excedentes se ternario | 4 |                 | 7 |             | 10 |              | 13 |              | 16 |              | 19 |
|----------------------------+---+-----------------+---+-------------+----+--------------+----+--------------+----+--------------+----|
| SVPERTRIPARTIENTES         |   | Supertriquarti. |   | supertri 7. |    | supertri 10. |    | supertri 13. |    | supertri 16. |    |
|----------------------------+---+-----------------+---+-------------+----+--------------+----+--------------+----+--------------+----|

|-----------------------+---+----------------+---+------------+----+-------------+----+-------------+----+-------------+----|
| A 5. excedentes se 3. | 5 |                | 8 |            | 11 |             | 14 |             | 17 |             | 20 |
|-----------------------+---+----------------+---+------------+----+-------------+----+-------------+----+-------------+----|
| SVPERTRIPARTIENTES.   |   | Supertriquinti |   | supertri 8 |    | supertri 11 |    | supertri 14 |    | supertri 17 |    |
|-----------------------+---+----------------+---+------------+----+-------------+----+-------------+----+-------------+----|

|-----------------------+---+-------------------+---+---------------+----+----------------+----|
| A 5. excedentes se 4. | 5 |                   | 9 |               | 13 |                | 17 |
|-----------------------+---+-------------------+---+---------------+----+----------------+----|
| SVPERQVADRIPARTIENTES |   | Superquadriquinti |   | superquadri 9 |    | superquadri 13 |    |
|-----------------------+---+-------------------+---+---------------+----+----------------+----|

|----------------------+---+--------------------+----+----------------+----+----------------+----|
| A 7 excedentes se 4. | 7 |                    | 11 |                | 15 |                | 19 |
|----------------------+---+--------------------+----+----------------+----+----------------+----|
| SVPERQVADRIPART.     |   | Superquadriseptimi |    | superquadri 11 |    | superquadri 15 |    |
|----------------------+---+--------------------+----+----------------+----+----------------+----|

His typis inspectis facile erit cuiqe superquintipartientis, ac
reliquorum, quotquot libuerit generum species effingere, easque in
infinitum producere, obseruato cuiusque serieitum principio, tum
numerorum inter se excessu. Excessus ex generis cuiusque nomine
cognoscitur; nam quadripartiens dicitur, cuius numeri quaternario se
excedunt; quintipartiens cuius numeri se excedunt quinario, & sic de
reliquis: principium autem numerorum sumitur ab omnibus numeris
excessu maioribus, & duplo eiusdem minoribus, nisi siqui cum excessu
numerum alium praeter vnitatem communem habeant mensuram, ideo
superquadripartientes incipiunt ab his numeris, qui sunt inter 4. & 8,
veluti à 5. & 7, non autem a 6, quia 4. & 6. ambo pares sunt,
pariumque omnium praeter vnitatem etiam binarius est communis mensura.

** [chapter 1.16]
De genere Multiplici super particulari, &y eius speciebus.

CAP. XVI.

TRia genera simplicia sequuntur duo composita: nam Multiplex
componitur cum reliquis duobus, quorum alterum dicitur Multiplex
superparticulare, alterum Multiplex superpartiens. Multiplex
superparticulare est, cùm numerus maior minori collatus continet eum
pluries, & aliquam eius partem. & quatenus eum habet pluries, meritò
vocatur Multiplex: & quia continet insuper vnam ipsius partem, dicitur
etiam superparticulare: vt 5. ad 2, in qua proportione quinarius
continet binarium bis, vnde est Multiplex genus, & dupla proportio; &
vnitatem, quae est dimidium binarij, quare est superparticularis
generis, & proportio sesquialtera: & simul dicitur esse dupla
sesquialtera. Sic etiam in hac proportione 7. ad 3. septem continet
tria bis, & tertiam eius partem, quare erit dupla sesquitertia. Atque
ita in eo inueniuntur omnes species Multiplicis cum singulis
superparticularibus, & omnes superparticulares cum singulis
Multiplicibus. exemplum prioris, dupla sesquialtera 5. ad 2: tripla
sesquialtera 7. ad 2: quadrupla sesquialtera 9. ad 2. exemplum
posterioris, dupla sesquitertia 7. ad 3: dupla sesquiquarta 9. ad 4:
dupla sesquiquinta 11. ad 5. Atque ita variæ possunt fieri vtriusque
generis coniugationes, vt per hunc typum manifestum esse poterit.

|-------------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-------------+-------------|
|           2 |        3 |        4 |        5 |        6 |        7 |        8 |        9 |        10 |        11 |        12 | Comites.    |             |
|-------------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-------------+-------------|
|           5 |        7 |        9 |       11 |       13 |       15 |       17 |       19 |        21 |        23 |        25 | Dupli.      | ad Comites. |
|-------------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-------------+-------------|
|           7 |       10 |       13 |       16 |       19 |       22 |       25 |       28 |        31 |        34 |        37 | Tripli.     | ad Comites. |
|-------------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-------------+-------------|
|           9 |       13 |       17 |       21 |       25 |       29 |       33 |       37 |        41 |        45 |        49 | Quadrupuli. | ad Comites. |
|-------------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-------------+-------------|
|          11 |       16 |       21 |       26 |       31 |       36 |       41 |       46 |        51 |        56 |        61 | Quintupli.  | ad Comites. |
|-------------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-------------+-------------|
|          13 |       19 |       25 |       31 |       37 |       43 |       46 |       55 |        61 |        67 |        73 | Sescupli.   | ad Comites. |
|-------------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-------------+-------------|
| Sesquialeri | Sesqui 3 | Sesqui 4 | Sesqui 5 | Sesqui 6 | Sesqui 7 | Sesqui 8 | Sesqui 9 | Sesqui 10 | Sesqui 11 | Sesqui 12 |             |             |
|-------------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-------------+-------------|

Idem determinatum sit circa genus Submultiplex subsuperparticulare,
quandoquide solum ratione differunt, vt superius demonstratum est. Id
fortè non inutiliter additur, posse praecedentem typum tam secundum
longitudinem; quàm secundum latitudinem in infinitum extendi, solo
numerorum excessu obseruato, quem ipsa proportionum nomina
reuelant. nam secundum longitudinem dupli sese binario excedunt,
tripli ternariò, quadrupli quaternario; secundum satitudinem similiter
sesquialteri binario, sesquitertij ternario, sesquiquarti quaternario:
ergo dupli sesquialteri vtrimque binario se excedunt; at dupli
sesquitertij secundum longitudinem binario, secundum latitudinem
ternario, & sic de reliquis, longitudine multiplicibus, latitudine
autem superparticularibus attributa.

** [chapter 1.17]
De genere Multiplici superpartienti, & de eius speciebus.

CAP. XVII.

IDem etiam dici potest de multiplici superpartienti, in quo numerus
maior continet minorem pluries, & aliquas eius partes: quatenus enim
continet eum pluries, dicitur Multiplex: & quatenus continet insuper
aliquas eius partes, quae non faciunt vna, est superpartiens, atque
ita simul dicitur Multiplex superpartiens, vt in hac proportione 8. ad
3, in qua numerus maior continet minorem bis, & duas eius tertias
partes, vnde meritò dicetur haec proportio Dupla superbipartiens
tertias. Et hoc genus, sicut Multiplex superparticulare, habet omnes
species Multiplicis cum singulis generibus, ac speciebus
Superpartientis, & contrà. reperiuntur enim in eo dupla
superbipartiens, & tripla superbipartiens, & quadrupla
superbipartiens: & cum his omnes species superpartientis, tertias,
quartas, & quintas, vt in hoc diagrammate, quod hîc apponendum
curauimus, omnia miro poterunt ordine inuestigari in quo limes
secundus ad primum ostendit superpartientes priùs positos; tertius
limes eos continet, qui ex vna comitum ad superpartientes adiectione
restituti sunt; quartus autem eos, qui vna & altera adiectione;
quintus eos, qui trina.

Longitudo
Latitudo
Comites
Superpartientes
Ternario
Dupli
Tripli
Quaternario.
Quinario.
Excedentes se

[figure 1 pdf page 63, book page 20]

Vides tertium ordinem ad primum duplos amplecti superpartientes;
quartum item ad primum triplos itidem superpartientes; denique quintum
quadruplos superpartientes. quod si eadem lege sextum, septimum, &
alios feceris, surgent quintupli, sextupli, septupli superpartientes.

** [chapter 1.18]
De Pythagoreorum diagrammate celeberrimo, quod Pythagorae mensam
appellant, & de ipsius ptilitatibus.

CAP. XVIII.

PRæeter ea quæ posita sunt, aliud etiam diagramma duximus apponendum,
quod Pythagora mensam appellant, maxima consideratione dignum, quod
est huusmodit

Longitudo.
Latitudo.
Primus limes
Dupli
Tripli
Quincupli
Sescupli
Septupli
Octupli
Decupli

Excedunt se Numeri primi limitis unitate, Dupli binario, Tripli
ternario, Quadrupli 4. & sic deinceps.

Ad primum limitem

[figure 2 pdf page 63, book page 20]


In hoc diagrammate (quod Pythagorae Mensam ab omnibus diximus
appellari) omnium generum naturali ordine dispositae proportiones
inueniuntur, ita vt primùm occurrant multiplices, deinde
superparticulares, postea superpartientes, deinceps multiplices
superparticulares, postremo multiplices superpartientes. Ad duos enim
primos ordines longitudinis, & latitudinis, qui faciunt angulum in
vnitate, omnes alij sunt MVLtiplices, si numeros numeris sibi
respondentibus conferas: nam duo secundi ordines, qui, in quaternario
concurrentes, angulum constituunt, sunt ad primos dupli; tertij, qui
in nouenario, tripli; atque ita qui sequuntur ad decimos vsque, qui
faciunt angulum in centenario, & sunt ad primos decupli. Et quoniam ad
vnitatem nullus inuenitur SVPERparticularis, ideo nullus ordo, ad
primum comparatus, est illi superparticularis; sed duo tertij ordines,
ad duos secundos collati, efficiunt primam superparticularium speciem,
& sunt ad eos sesquialteri; quarti ad tertios sesquitertij; quinti ad
quartos sesquiquarti; & sic vsque ad decimos, qui ad nonos sunt
sesquinoni. Inueniuntur etiam SVPerpartientium genera, & species
complures: nam quinti, comparati ad tertios, sunt superbipartientes
tertias; septimi ad quintos, superbipartientes quintas; septimi item
ad quartos, supertripartientes quartas; octaui ad quintas,
supertriquinti; noni item ad quintos, superquadriquinti; decimi ad
septimos, supertripartientes septimas. MVLtiplex etiam
SVPERparticulare inuenietur: nam si comparemus quintos, & septimos, &
nonos ad secundos, emergent dupli sesquialteri, tripli sesquialteri,
quadrupli sesquialteri; &, si comparentur septimi, & decimi ad
tertios, consurgent dupli sesquitertij, & tripli
sesquitertij. Postremò inuenitur MVLtiplex SVPerpartiens: nam, si
comparentur octaui ordines ad tertios, reperietur inter eos dupla
superbipartiens tertias. Sunt etiam plurima in hoc typo consideratione
dignissima, & (vt Boëetius ait) ad subtilitatem tenuissima, ad
scientiam vtilissima, & ad exercitationem mentis iucundissima; quorum
aliqua perstringemus, quae fastidium, quod in proportionibus
inquirendis conceptum fuit, leuare possint. Primumque esto, quòd linea
diametralis, si ab angulo, quem facit vnitas, protendatur per numeros
angulares, transibit vsque ad angulum, quem facit centenarius:
dicuntur autem numeri angulares, qui fiunt ex concursu or dinum
longitudinis, & latitudinis, vt quaternarius ex concursu secundorum
ordinum, & nouenarius ex tertiorum; & hi omnes sunt quadrati, &
puncto, vt prae coeteris dignoscantur, notati. Secundum, quòd omnes
quadrati sunt circunclusi à numeris longilateris, (quorum natura
superiùs explicata est cap.9.) vt quaternarius à binario, & senario,
ita vt alter praecedat, & alter sequatur. Quòd si duobus longilateris
aggregatis quadratus duplicatus coniungatur, emerget quadratus: nam ex
binario, & senario aggregatis fiunt octo, & ex quaternario duplicato
item octo,quibus coniunctis emergunt 16, qui est quadratus
quaternarij. Tertium, quòd, si aggregentur duo quadrati immediati, &
duplicetur longilaterus, eos geometricè diuidens, qui inde prouenient
numeri, in summam collecti, quadratum etiam efficient: vt si
quadrati 4. & 9. aggregentur, proueniunt 13; longilaterus verò 6. bis
sumptus facit 12; denique producti 13. & 12. in vnum collecti,
constituunt 25, qui est quadratus quinarij. est tamen nonnulla inter
hos quadratos differentia: nam illi , qui surgunt ex longilateris
duobus, & quadrato, erunt numeri pares; & qui surgunt ex duobus
quadratis, & longilatero, erunt impares, quorum melior & fortior est
natura. Quartum, quòd in tota tetragoni figura, & in quadratis
minoribus, qui ex partibus eius fiunt; si numeri, qui ex angulis
oppositis se respiciunt, alter in alterum ducantur, eandem inter se
summam conficiunt; vt si vnitas per centum multiplicetur, prouenient
centum, & tantundem efficient denarij, qui in reliquis duobus
lateribus sunt oppositi, si alter in alterum ducatur. atque idem
eueniet in quadratis minoribus, veluti sunt
T. 9. 81. 9. 8. 10. 30. 24. aliáaque infinita: tantundem enim
producitur ex 1. in 80. quantum ex 8. in 10, itémque ex 4. in 24,
quantum ex 8. in 12. Et haec de multis dicta sint, quae circa hoc
diagramma dici poterant, omnibus quidem notissimum, vtpote quod
pueris, praxim Arithmetites exercentibus, primùm ediscendum
proponitur, sed à paucissimis, vt par est, examinatum; nos autem de
illo, ac de proportionum generibus haec tantùm, breuitatis causa,
dicenda, qua maiori potuimus claritate curauimus.

** [chapter 1.19]
De modo coniungendi, & duplandi Proportiones.

XIX. CAP.

ET quoniam saepe cogitur harmonicus ex duabus, aut tribus
proportionibus vnam componere, saepe etiam vnam in duas, aut tres
diuidere, antequàm de proportionalitatibus dicere ordiamur, in quibus
diuidendi proportiones modus inuestigatur, necesse erit, vt modum, eas
coniungendi, & in summam colligendi, doceamus. Quae si fuerint
inaequales, facilè poterunt coniungi, duarum proportionum numeris
maioribus altero in alterum ductis, atque item minoribus; & in
numeris, qui ex ea multiplicatione proueniunt, reperietur vna ex
duabus facta proportio. Vt si velimus, ex coniunctione sesquitertiae
cum sesquialtera, scire, quaenam emergat proportio, accipiemus maiorem
sesquitertiae, qui est 4, & ducemus in maiorem sesquialterae, qui est
3, & prouenient 12; & minorem sesquitertiae, qui est 3, per minorem
sesquialterae, qui est 2, & prouenient 6: & à 12. ad 6. erit dupla,
composita ex sesquialtera, & sesquitertia. Cuius erit probatio
certissima, simultiplicemus minorem vnius per maiorem alterius, 2. per
4, & prouenient 8, qui numerus diuidet duplam in sesquitertiam, &
sesquialteram, vt in his numeris, 6.8.12. Et si velimus adiungere
sesquitertiae sesquiquintam, ducemus 6. maiorem sesquiquintae,
in 4. maiorem sesquitertiae, & prouenient 24, & 5. in 3. vtriusque
minores, & fient 15: & à 24. ad 15. erit proportio supertripartiens
quintas facta ex duabus. quod facilè apparebit, si ducantur aut 6, in
3, aut 5. in 4: quia ex priori multiplicatione prouenient 18, & ex
posteriore 20, vt in his numeris, 24.18. 15, vel, 24. 20. 15. Quòd si
volemus his tertiam adiungere, capiemus maiorem illius numerum, &
ducemus in huius maiorem; & minorem item in minorem: vt si erit
sesquialtera, ducetur 24. in 3, & fient 72; & 15. in 2. prouenient 30:
in quibus numeris inuenietur proportio dupla superbipartiens quintas,
facta ex sesquialtera, & sesquitertia, & sesquiquinta, vt apparet in
his numeris.

Sesquialtera Sesquitertia Sesquiquinta
Duplasuperbiquinte.

[figure 1 pdf page 65, book page 22]


Et ad hunc modum poterunt, quotquot voluerimus, coniungi. Quòd si
proportiones erunt aequales, earum coniunctio dicitur duplatio, aut
triplatio. Et duarum coniunctio (quę duplatio vocatur) facilimè fieri
poterit, numeris, in quibus proportiones aequales inueniuntur, ductis
in seipsos: & in numeris, qui ex hac multiplicatione prouenient,
inuenietur ex duabus aequalibus facta vna: vt si velimus duplare
sesquialteram, ducemus maiorem numerum, 3, in seipsum; similiter &
minorem, 2, & prouenient 9. & 4, quae erit dupla sesquiquarta, facta
ex duabus sesquialteris: quod erit manifestum, si ducatur 3. in 2, nam
fient 6, qui numerus diuidit proportionem, 9. ad 4, in duas aequales,
vt ostendunt hi numeri:

Sesquialtera Sesquialtera
Dupla sesquiquarta.

[figure 2 pdf page 65, book page 22]

Idem fiet, si duas sesquioctauas velimus coniungere, ductis in
seipsos 9. & 8, ex qua multiplicatione consurgent 64. & 81, quae erit
superseptendecimpartiens sexagesimas quartas, ex duabus sesquioctauis
composita: nam, ductis 8. in 9, prouenient 72, qui erit
ad 64. sesquioctauus, & eandem proportionem faciet ad eum 81. Quòd si
proportionem triplare velimus, numeri, qui ex duplatione prouenerint,
ducendi sunt in minimos ipsius numeros, maior in maiorem, & minor in
minorem, & in ijs, qui ex ea multiplicatione nascentur, triplata
reperietur. vt, si velimus triplare sesquialteram 3. ad 2, numeri 9. &
4, ex eius duplatione producti, ducendi sunt in eosdem 3. & 2,
maior 9. in maiorem 3, & minor 4. in minorem 2, & consurgent 27. & 8,
quae erit tripla supertripartiens octauas, composita ex tribus
sesquialteris, vt apparet in his numeris:

Sesquialtera Sesquialtera Sesquialtera Triplasupertripartiens octauas.

[figure 1 pdf page 66, book page 23]


Et si sesquioctauae duplatae numeri, 81. & 64, ducantur in minimos
sesquioctauae numeros, 9. & 8, prouenient 729. & 512, in quibus
numeris inuenietur vna ex tribus sesquioctauis facta proportio, quas
ostendunt hi numeri, 512. 576.648. 729. Atque idem faciedum est, si
quadruplare velimus, in numeris, qui ex triplatione prouenerunt; &, si
quincuplare. in his, qui ex quadruplatione; semper eos ducendo in
minimos illius proportionis, quam multiplicare propositum sit. Quae
duplandae, & triplandae proportionis regula erit non minùs vtilis,
quàm facilis rerum musicalium speculationem facere volenti, vt suis
locis manifestum esse poterit.

** [chapter 1.20]
De modo subtrahendarum vnius ab altera proportionum, & quo pacto ad
minimos numeros reducantur.

CAP. XX.

OPortet etiam Harmonicum examinare solerter excessuum quantitates,
quibus vna proportio superatur ab altera, vt possit exactas earum
inter se differentias cognoscere: quam cognitionem perfectam habere
nequaquam poterit, nisi priùs vnam ab altera discat subtrahere. Fit
autem subtractio per multiplicationem numerorum antesedentium per
consequentes, ita vt antecedens proportionis vnius ducatur in
consequemtem alterius. vt, si velimus subtrahere sesquitertiam à
sesquialtera, multiplicabimus quaternarium, antecedentem
sesquitertiae, per binarium, consequentem sesquialterae, & emerget 8;
& ternarium, antecedentem sesquialterae, per ternarium, consequentem
sesquitertiae, & prouenient 9, & proportio, quae est à 9. ad 8, erit
reliqua ex subtractione sesquitertiae à sesquialtera. Quod probari
potest, si denuò eo modo, quo in praecedenti capite dictum est,
coniungantur sesquitertia, & sesquioctaua; redibit enim sesquialtera,
ex vtraque conflata; nam 8. in 3. ducta, faciunt 24, & 9. in 4,36. Et
vt Subtractionem per Additionem, ita contrà & Additionem per
Subtractionem probare licebit. Potest & alio modo fieri subtractio,
si, assumptis minoribus numeris duarum proportionum, quarum maioris ad
minorem excessum scire velimus, alterum in alterum ducamus: in eo enim
numero, qui ex ea multiplicatione proueniet, vtraque poterit inueniri,
ex quo facilè vnius ad alteram excessus deprehendetur. vt si scire
propositum sit excessum sesquialterae ad sesquitertiam, ternarium,
minorem sesquitertiae, ducemus in binarium, minorem sesquialterae, &
proueniet senarius, qui, quoniam habet dimidiam, & tertiam partem,
habebit numeros sesquialterum, & sesquitertium: nam, si ternarium illi
superaddamus, qui est eius dimidium, emerget nouenarius ad eum
sesquialter; &, si binarium adiungamus, proueniet octonarius, qui erit
ad eum sesquitertius quo facto, facilè apparebit, sesquialteram esse
maiorem sesquitertia ea proportione, quæ est a 9. ad 8, vt ostendit
hic typus.

[figure 1 pdf page 67, book page 24]

Et eodem modo in quibuslibet alijs & vna ab altera subtrahi, & vnius
ad alteram excessus poterit inueniri. Et quoniam saepe necesse est,
radices alicuius proportionis inuestigare, & minimos, in quibus
reperiri potest, numeros inuenire, id hac via commodissimè fieri
poterit; Si minorem numerum toties a maiore subtrahamus, donec ad
numerum minimum, qui vtrumque metiatur, perueniamus, qui si erit
vnitas, nequaquam vlteriùs erit progrediendum, vt si velimus
proportionem, quę est à 24. ad 15, ad suas radices reducere, primùm
inuestigandus est numerus, qui sit vtriusque communis
mensura. subtrahatur igitur 15.à 24, & relinquetur 9, quo subtracto à
15, restabit 6, quem si à 9. auferas, relinquetur 3, quo
a 6. subtracto, restabit etiam 3; & quia 3. à seipso subtrahi non
potest, is erit numerus, qui vtrumque metietur. quare
proportio 24. ad 15. erit per 3. diuidenda, & ad tertias partes
reducenda, quae erunt 5. & 8. Et si velimus examinare, sintne hi
numeri ipsius minimi, an ad minores possint reduci, eadem via erit
inuestigandum, subtrahendo videlicet quinarium ab octonario, &
restabit ternarius, quo subtracto à quinario relinquetur binarius, quo
sublato à ternario restabit vnitas, quae sola erit communis quinarij,
& octonarij mensura: quamobrem vlteriùs procedi non poterit, & hi
erunt minimi numeri huius proportionis. Et hac etiam regula poterunt
cognosci numeri contra se primi, de quorum natura, & proprietatibus
superius abundè dictum est: vt si scire velimus, vtrùm hi duo
numeri, 9. & 25, (quorum vterque compositus est, alter ex ternarij,
alter ex quinarij multiplicatione) sint contra se primi, eadem via
procedendum erit. nam subtractis 9.à 25. restabunt 16, eisdem
à 16. sublatis, relinquentur 7, quibus à 9. subtractis, restabunt 2, &
his à 7. subtractis, reliqui erunt 5, & à 5. 3, & a 3.1, quo sublato a
2, relinquetur ipsamet vnitas, quae sola metietur vtrumque. Quod non
ita euenit in his numeris, 9. & 21: nam si fiat idem, ternarius
vtriusque reperietur esse mensura. quare non erunt contra se primi; &
proportio, quae in huiusmodi numeris reperietur, ad minores numeros
reduci poterit, quod non contingit in numeris contra se primis, sed,
siue vterque sit impar, vt 9. & 2 5, siue sit alter par, & alter
impar, vt 64. & 8i; proportio, quae in eis inuenietur, ad minores
numeros reduci non poterit. Nunc autem ad resiqua, quae praesenti sunt
instituto necessaria, pergamus.

** [chapter 1.21]
De Arithmetica Proportionalitate

XXI. CAP.

Am tandem de Proportionalitatibus agendum est, quas Analogias Græci
vocant, in quibus porportio ipsa medio aliquò inuenitur diuisa, & ex
vna in duas dissoluta. Sciendum verò est, quosdam politioris
literaturae viros vocem Graecorum aν vertere rationem, & avaias
proportionem: nos contrà nν proportionem, & advie proportionalitatem
vocamus, tum vt Boëtium, & alios grauissimos autores sequamur, tum
quòd, vt avadoylar ano roù doyn, ita & proportionalitas à proportione
deriuatur. Est autem proportionalitas proportionum inter se habitudo,
sicut proportio numerorum. Et quemad modum proportio in paucioribus,
quàm duobus numeris, reperiri non potest; sic etiam proportionalitas
ex duabus saltem proportionibus constare debet, & tribus numeris,
quorum medius eas conuenienter diuidat. Et quamquàm tempore Boëtij
decem diuidendarum proportionum modi fuerant inuenti, quibus vndecimum
Iordanus, cui plurimùm Arithmetica debet, adiecit; nos tamen tribus
his, quas Pythagoram Boëtius asserit inuenisse, erimus in praesentia
contenti; de quibus tantum ab Arist. & Platone factam esse mentionem
compertum est, & quae solae, ad faciendas rerum Musicalium
speculationes, sunt necessarię; quae sunt Arithmetica, Geometrica, &
Harmonica. Prima autem est Arithmetica, quae mediatio fiumeralis
Latinè dici potest, quandoquidem numerus natura prior est mensura, &
harmonia; quamobrem de medio Arithmetico priùs, quàm de alijs, agemus,
& de eo, atque alijs, ea tantùm afferemus, quae huic instituto
videbuntur esse necessaria, quàm plurimis, scitu dignissimis, his, qui
exactam Arithmeticae cognitionem prositentur, relictis. Medium ergo
Arithmeticum dicimus esse illud, quod ab vtroque extromo per aequales
differentias, & inaequales proportiones disiunctum est. Vocamus autem
differentias excessuum quantitates, quae inter ipsos inuicem numeros
inueniuntur: vt in ea proportione, quae est ab 8. ad 4,
dicimus 6. medium Arithmeticum esse: quia distat ab vtroque per
aequalem differentiam, quae est binarius; sed per inaequales
proportiones, quia 6. ad 4. facit sesquialteram, 8. verò
ad 6. sesquitertiam: vt liquidò constat in his numeris, 4. 6. 8, in
quibus eadem est differentia à 6. ad 4, quae à 6. ad 8, nam vtraque
est binarius; sed non eadem, vt diximus, proportio. Sed in hac
proportionalitate potissimùm à Musico videtur esse considerandum, quòd
in ea maiores proportiones in minoribus numeris, & minores in
maioribus collocatae reperiuntur; vt in hac dupla 4. ad 2. per hoc
medium Arithmeticum 3. diuisa in sesquialteram, & sesquitertiam,
sesquialtera, quae maior est, à 3. ad 2, qui numeri sunt minores,
inuenitur; & à 4. ad 3, qui maiores, sesquitertia; vt ostendunt hi
numeri, 2.3.4. Modus autem medij Arithmetici inueniendi commodissimus
erit, si duo extrema coniungantur, & dimidium eius summae capiatur,
quod erit medium quaesitum; vt in hac eadem dupla, 4. & 2. aggregati
faciunt 6, cuius summae dimidium est 3, qui medium in ęa est
Arithmeticum. Est tamen aduertendum, quòd, si numerus, ex duorum
extremorum aggregatione proueniens, fuerit impar, (quod contingit cum
extremorum alter est par, alter impar) quia medietatem non habebit,
duplicandi erunt extremi, & tunc, qui proueniet, erit par, atque eius
dimidium poterit assumi: vt, si velimus inuenire medium huius
proportionis 3. ad 2, quia ex eorum collectione conficitur quinarius,
qui est impar, non poterit inter eos medium inueniri, atque etiam,
quia sola distant vnitate, quae indiuisibilis est; quare duplicandi
sunt, vt proueniant 4. & 6, qui simul sumpti faciunt 10, cuius
dimidium erit 5, qui medium erit inter eos. Et haec de Arithmetica
proportionalitate dixisse sit satis.

** [chapter 1.22]
De Proportionalitate Geometrica.

CAP. XXII.

PRoportionalitas Geometrica est ea, in qua medium distat ab vtroque
extremo per æequales proportiones, & inaequales differentias: vt, in
proportione 4. ad 1. medium Geometricum erit 2, qui est duplus ad
vnitatem, quemadmodum quaternarius ad eum etiam est duplus. Et
differentiae sunt inaequales, quia binarius ab vnitate distat per
unitatem, & à quaternario per binarium, quod demonstrant hi numeri.

Excellus
Geaneries Lusluge laillo.
Dupla Dupla
Quadrupla.

[figure 1 pdf page 68, book page 25]


Huiusmodi mediatio in multò paucioribus proportionibus inuenitur, quàm
aliarum quælibet: quoniam in his tantùm inueniri potest, quæe ex
aggregatione duarum aequalium reperiuntur esse compositae, in quas
etiam diuidi poterunt: vt in quadrupla, quae componitur ex duabus
duplis, vt in praemisso typo ostendimus; & in noncupla, quae constat
ex duabus triplis, vt 1. 3. 9; & in ea, quae est a 9. ad 4, quae ex
duabus sesquialteris componitur, vt apparet in his numeris, 4.6.9; &
in ea, quæe est a 25. ad 9, quæ componitur ex duabus
superbipartiontibus tertias, vt ostendunt hi numeri, 9. 15. 25. Atque
ita passim occurrent ex empla in omnibus generibus proportionum;
praeterquàm in superparticulari, cuius nulla proportio, in duò aequa
certo constitutóque numero diuisa, poterit inueniri. Habet etiam naec
proportionalitas hoc sibi peculiare, quòd numerus, qui vocatur in ea
diuisor Geometricus, in seipsum ductus, facit eandem summam, quam duo
extrema, altero in alterum ducto: vt in hac
proportione 9. ad 4. medium Geometricum est 6, quoniam eandem
proportionem facit ad 4, quam 9. ad ipsum, vtraque enim est
sesquialtera; & differentiae, sunt inaequales, quoniam a quaternario
distat binario, & à nouenario ternario; ductus autem in seipsum facit
36, & 9. in 4. ductus, in eandem excrescit summam. Quamobrem nullus
est accommodatior modus inueniendi medij Geometrici, quàm duos numeros
eius proportionis, quam Geometricè diuidère proponemus, vnum in
alterum ducere, ac deinde inter eos quaerere aliquem, qui ductus in
seipsum eandem summam, quam illi fecerint. constituat; vt si velimus
diuidere Geometricè eam proportionem, quae est à 16. ad 9, inueniemus
ex altero in alterum ducto prouenire 144. Neque vllus est inter eos
numerus, qui, ductus in seipsum, eandem summam faciat, nisi
duodenarius; quare is erit Geometricus eius diuisor, quoniam eandem
proportionem facit ad 9, quam 16. ad ipsum, vtraque enim est
sesquitertia. Atque haec visa sunt nobis, quae Musicum in hac
proportionalitate considerare oporteret. Solùm hoc illum admonendum
putauimus, in numeris vniuscuiusque proportionis, Geometricè
diuidendae, duos numeros, qui sint eius radices, semper esse
quadratos. nam si diuidenda est in duas ęquales, (vt Geometrica
postulat diuisio oportet eam ex duabus etiam aequalibus esse
compositam; quam compositionem superiùs duplationem diximus appellari,
duplationem autem cuiuscunque proportionis fieri, per duorum
numerorum, in quibus inuenitur simpla, quadrationem. Quare necesse
erit, illos, in quibus inuenitur duplata, quadratos esse. Etiam hoc
animaduersione dignum est, inter duos quadratos medium Geometricum
semper esse longilaterum, & inter duos longilateros quadratum esse
medium Arithmeticum: prioris exemplum, 1.2.4; posterioris, 2.4.6. Et
hæc de Geometrica proportionalitate dicta sufficiant.

** [chapter 1.23]
De Proportionalitate Harmonica.

CAP. XXIII.

REliquum est, vt de proportionalitate Harmonica dicamus, quę sic dicta
fuisse vide tur, quòd maximè ad harmoniam apta sit: consonantiae enim
harmonicè diuisę Harmoniae vocantur à Musicis, quae proportionibus,
harmonica mediatione disiunctis, respondere, suo loco
demonstrabuntur. Est autem Harmonica proportionalitas, in qua medium
ad extrema nec seruat aequalitatem differentiarum, vt Arithmeticum,
nec proportionum, vt Geometricum; sed ita collocatum est inter ea, vt,
quae proportio est alterius ad alterum extremorum, eadem sit
differentiae maximi, & medij ad differentiam medij, & minimi. vt in
hac proportione, 6.ad 3, in qua medium harmonicum erit 4: quia
differentiae 6. ad 4, quae est binarius, ad differentiam 4. ad 3, quae
est vnitas, eadem est proportio cum ea, quæe est à 6. ad 3, vtraque
enim esse dupla reperitur, yt apparet in huis numeris.

DVPLA
Differentia Medij & extremorum.
Harmonica Duplae divisio.
Sesquialtera Sesquitertia
DVPLA

[figure 1 pdf page 70, book page 27]

Hoc multò breuiùs & concinniùs in Timaeo Plato videtur expressisse,
vbi medium harmonicum eisdem ipsorum extremorum partibus alterum
superare, & ab altero ait superari; vt 8. inter sex & duodecim,
quoniam superat senarium tertia senarij parte, & superatur à
duodenario tertia etiam parte duodenarij. Sciendum est autem
harmonicam proportionalitatem nihil aliud esse, quàm Arithmeticam
inuersam. in easdem enim proportiones inuenitur diuisa: nisi quod
maiores proportiones, in illa minoribus comprehensę numeris, in hac ad
maiores transferuntur; & minores (vt par est) in minoribus numeris
collocantur, &, si fieri potest, in ijsdem, in quibus antè fuerant,
remanent collocatae. vt in hac dupla Arithmeticè diuisa,2.3.4, quam si
harmonicè mediatam habere velimus, sesquialtera proportio, quae est
à 3. ad 2, transferenda est ad maiores numeros, &, vt sesquitertia, in
quibus erat, collocata remaneat, examinandum est, vtrùm 4. habeat
supra se sesquialterum, quem necessariò, cùm par sit, habebit, si ipsi
dimidium eius, quod est 2, aggregetur, vnde proueniet 6, à quo
ad 4. erit sesquialtera, & à 4. ad 3. sesquitertia, vt erat antè,
relinquetur. atque ita maior proportio in maioribus numeris, & minor
in minoribus (quod harmonicę proportionalitatis proprium est)
inuenitur. Quod ostendunt hi numeri:

Harmonica proportionalitas
Arithmetca proportionalitas
PSesgalera Sesqui z. Sesgaltera
DVPLA
DVPLA

[figure 2 pdf page 70, book page 27]


Restat nunc, yt modum harmonici medij inueniendi diligenter
exquiramus, qui facilis erit inuentu, habito priùs
Arithmetico. quoniam vbi non poterit inueniri Arithmeticum, neutiquam
inuenietur harmonicum: quandoquidem harmonica proportionalitas
Arithmeticae, vt diximus, est inuersa. Inuento igitur ad modum, quem
superiùs ostendimus, Arithmetico, primùm inquirendum est, vtrùm habeat
supra se numerum, qui ad eum faciat eandem proportionem cum ea, cuius
est medius, quem si habuerit, illo assumpto, proportio harmonicè
reperietur diuisa: in qua ipse, qui erat medium in proportionalitate
Arithmetica, erit minus extremum in Harmonica; & qui erat maius
extremum in Arithmetica, erit medium harmonicum; & numerus assumptus
maius erit extremum. Vt, si velimus harmonicè diuidere hanc triplam,
quae est à 3. ad 1,accipiemus medium eius Arithmeticum, quod est 2, &
inquiremus numerum eius triplum, qui erit 6. Atque ita proportio, quæe
erat à 3. ad 1. Arithmeticè diuisa, inuenietur harmonicè mediata
à 6. ad 2: & 3. maius extremum in proportionalitate Arithmetica, erit
medium in harmonica; & 2. medium Arithmeticae, minus extremum;
& 6. numerus assumptus, erit maius. vt percipi potest in his numeris:

TRIPLA Arithmnetice diuisa.

[figure 1 pdf page 71, book page 28]

Quòd si nullus in maioribus numeris inuenietur, qui ad Arithmeticum
diuisorem eandem faciat proportionem cum ea, quam ipse diuisit;
duplicandi, aut triplicandi erunt numeri, donec inueniatur. neque id
temerè faciendum est, sed regula quadam adhibita. Quoniam in
multiplicibus ferme omnibus inuenietur, vt in dupla, & tripla paulò
superiùs osten sum est, & in quadrupla, ac quintupla ostendent hi
numeri:

[figure 2 pdf page 71, book page 28]

Et sic in omnibus ferè multiplicibus passim occurrent exempla. Sed in
superparticularibus multò certiori, & constantiori ordine procedendum
est. Nam, vt in omnibus, ad inueniendum medium Arithmeticum,
necessariò duplicandi sunt numeri; ita ad inueniendum harmonicum,
inuento Arithmetico, in sesquialtera sunt duplicandi, in sesquitertia
triplicandi, in sesquiquarta quadruplandi: & hoc ordine seruato, in
omnibus superparticularibus medium harmonicum facilimè poterit
inueniri, vt his tribus exemplis satis erit omnibus manifestum:

EXEMPLVM PRIMVM.
2. 3. SESQVIALTERA diuidenda.
4. 5. 6. Sesquialtera diuisa Arithmeticè.
8.10.12. Numeri Arithmeticae proportionalitatis duplicati.
10.12. 15. Sesquialtera divisa Harmonice.

EXEMPLVM SECVNDVM.
3. 4. SESQVITERTIA diuidenda.
6. 7. 8. Arithmeticè diuisa.
18.21.24. Triplicati numeri.
21.24.28. Harmonicè diuisa.

EXEMPLVM TERTIVM.
4. 5. SESQVIQVARTA diuidenda.
8. 9.10. Arithmeticè diuisa.
32. 36.40. Quadruplati numeri.
36.40.45. Harmonicè diuisa.

Atque hic modus inueniendi medij harmonici mihi videtur esse multò
facilior, & commodior, quàm is qui traditus est ab antiquis, & adhuc
in omnibus docetur scholis.

** [chapter 1.24]
De alio modo medij Harmonici simul & Arithmetici inueniendi, qui multò
videtur esse facilior: & de quibusdam, quae in harmonica
proportionalitate, praeter ea quae dicta sunt, oportet considerare

CAP. XXIIII.

ET quoniam haec proportionalitas omnium maximè ad Harmonici
considerationem pertinet, nulli mirum videri debebit, si in ipsius
explicatione diutiùs, quàm in aliarum enarratione,
immorabimur. Quamobrem cùm valdè Musico conducat, medium Harmonicum
inuenire, & modus eius inueniendi ab antiquis traditus sit
difficilimus: quamuis ille, quem supra attulimus, facilis satis esse
videatur, alterum nunc afferemumultò faciliorem, quo eam simul
harmonicè & arithmeticè poterimus habere diuisam, is talis est:
Accipiendi sunt numeri, in quibus arithmeticè diuisa reperitur, &
minimus, & maximus per medium arithmeticum multiplicandi, & in
numeris, qui ex ea multiplicatione prouenient, reperietur arithmeticè
simul, & harmonicè diuisa: harmonicè quidem. si minimus in maximum
ducatur, arithmeticè verò, medio in seipsum ducto. Vt, exempli gratia,
accepta sesquialtera arithmeticè diuisa in his numeris, 4. 5. 6,
ductis 4. & 6. in 5, prouenient 20. & 30, qui continebunt
sesquialteram tam Harmonicè, quàm Arithmeticè diuidendam; nam
ducto 4. in 6,emergent 24, qui numerus erit medium harmonicum; & 5. in
seipsum ducto, surgent 25, qui numerus erit medium arithmeticum, vt in
sequenti numerorum dispositione apparet:

3. SESQVIALTERA diuidenda.
4. 5. 6. Arithmaticè diuisa.
20. 30. Numeri producti ex medio 5. in exttema 4. & 6. ducto.
Medium Harmonicum ex multiplicatione extremorum 4. & 6.
Medium Arithmeticum ex medio 5. in seipsum ducto.
20.24. 30. Proportionalitas Harmonica.
20.25.30. Proportionalitas Arithmetica.

Hic medij Harmonici inueniendi modus in omnibus omnium generum
proportionibus certissimus inuenitur. Atque haec de proportionalitate
quidem harmonica ad praesentem institutionem dicta sufficiunt. Vnum
verò hoc de tribus medijs praetermittendum minimè videtur, quòd, si
aliquando proportio aliqua per haec tria media reperietur diuisa,
medium Arithmeticum erit maiori extremo proximum, Harmonicum minori:
Geometricum verò medium tenebit locum, nec solum geometricè diuidet
duo extrema, sed & media harmonicum, & arithmeticum; & proportio, quae
reperietur inter ea, geometricè erit diuisa: vt in his numeris
perspici poterit, 10.16.20.25.40, in quibus proportio diuidenda est
à 40. ad 10: Medium Arithmeticum 25, quia per aequales numeros distat
ab vtroque: Medium Geometricum 20, quia eandem proportionem facit ad
10, quam ad ipsum 40: Harmonicum verò 16, quia differentia eius ad 40,
quae est 24, ad differentiam ipsius ad 10, qua est 6, quadruplam habet
proportionem, vt 40. ad 10: & in ea proportione, quæe est a 25. ad 16,
etiam est 20. medium Geometricum, quoniam vtraque proportio, in quas
inuenitur diuisa, est sesquiquarta; & 20, ductus in seipsum, facit
400, qua eandem summam faciunt 40. per 10,
& 25. per 16. multiplicati. Quòd si per duo solùm media, arithmeticum,
& harmonicum, inuenietur diuisa, altero in alterum ducto, vicem
obtinebunt medij Geometrici. nam eandem summam facient, quam duo
extrema, altero in alterum ducto. Vt in ea proportione, quae est
à 12. ad 6, medium arithmeticum 9. si ducatur in 8. medium harmonicum,
consurgent 72: & eadem summa proueniet ex 12. per senarium
multiplicato. Postremò illud non minore consideratione dignum puto,
quòd, si tria media quadrentur, duo verò extrema, & binae
differentiae, alterae arithmeticae proportionalitatis, alterae
harmonicae, inter se multiplicentur; productum extren brum,
quadratorum aliud aequabit, aliud luperabit, & ab alio superabitur;
aequabit geometricum, superabit harmonicum producto differentiarum
eius, & superabitur ab arithmetico similiter producto differentiarum
eius, vt sequens declarat figura:

MEDIVMIEXTREMVM
EXTREMVMIMEDIVMMEDIVM
Arithmeticum
Geometricum
minus
Harmonicum
maius
Differentia
Media quadrata
pducta ex differentijs
SVMMA
RESIDVVM

[figure 1 pdf page 73, book page 30]

** TODO create continuous figure numbering
** TODO crop figures and store them
** [chapter 1.25]
De noua ratione inueniendi tria Media (Arithmeticum, Geometricum, & Harmonicum) ex eorum & Extremorum differentis.

CAP. XXV.

QVae hactenus de trium Mediorum inuentione attulimus, ea pleraque
nobis cum alijs, qui de hac re scripserunt, conueniunt. Id verò nemo
est, qui ex ijs, quorum ad me scripta publicè edita peruenerunt,
considerauerit, quòd, cognitis Extremis, & quales eorundem ac Mediorum
oporteat esse Differentias, eo ipso statim & Media patere
possunt. Quae eorum inuestigandorum ratio cùm superioribus & facilior
sit, & ipsis Medijs magis propria, (quid enim eis magis sit proprium,
quàm id, per quod constituta, inter se & differunt, & definiuntur?)
facere non possum, quin eam praemissis praeceptis, iam vsu receptis,
adiungam. Verùm, cùm tota haec ratio ex Differentiarum pendeat natura
ac proprietate, de ea quaedam præemittenda videntur. Sciend migitur im
primis est, Differentias esse vel aequales, vel inaequales. ęquales
sunt in proportionalitate Arithmetica, in caeteris inaequales. Cumque
Arithmeticae differentię proportior es constituant aequam simpliciter
& per se; reliquae non per se, sed alteri proportioni aequam
constituunt, Harmonicae quidem proportioni diuisae, Geometricae verò
diuidentibus. Quod in quadruplae diuisione videre licet, quae
sit 40. ad 10: in ea differentiarum
Arithmeticarum 15. ad 15. proportio aequa est: Harmonicarum
verò 24. ad 6. proportio aequa est quadruplae diuisae, sicut
Geometricarum 20. ad 10. duplis eam diuidentibus, quae sunt 20, ad 10,
& 40. ad 20. Quæ, & plura quæ sequuntur, in hac formula intueri
licebit:

[figure 2 pdf page 73, book page 30]


Cumque proportionum Geometricè diuidentium vtralibet (nam aequales
sunt) duplo à diuisa superetur, simul proportio differentiarum
Geometricarum ab Harmonicarum proportione duplo vincatur necesse est,
vt in eodem exemplo patet.diuisa enim quadrupla Geometricè, vtralibet
proportionum diuidentium, 20. ad 10, & 40. ad 20, duplo à quadrupla
diuisa superatur: cumque & differentiae Geometricae, 20. ad 10, duplam
constituant, & Harmonica,24. ad 6, quadruplum; manifestum est ab his
illas eadem proportione superari. Itaque si quis velit tres
differentiarum proportiones ad vnum aliquem terminum communem
constituere, eum terminùm Arithmeticus quidem aequabit, Arithmeticum
verò superabit Geometricus, & Geometricum item Harmonicus; ita vt;
quoties Arithmeticum Geometricus, toties Geometricum contineat
Harmonicus; solumque superetur Arithmeticus, superétque Harmonicus,
Geometricus verò tam superet, quam superetur; & tantum superet,
quantum superetur: superat enim Arithmeticum eadem parte, qua ab
Harmonico superatur. Nam si, eadem quadrupla tripliciter diuisa,
triplices oriantur differentiae, vt in praemissa figura, harumque
omnium vnum terminum communem constituamus 2; erit reliquus terminus
Arithmeticus quidem 2, Geometricus verò 4, & Harmonicus 8: nam communi
termino 2. aequus est 2, quem 4. vt duplo superat, ita & ab 8. duplo
superatur. Guius contrarium contingit in tribus Medijs inter eadem
extrema collocatis. nam Geometricum superat non Arithmeticum, sed
Harmonicum; ab Arithmetico verò superatur eadem parte, qua ab ipso
superatur Harmonicum: nam, cùm sint tria Media quadruplae, 16.20.25,
superatur 16. quarta sui parte à 2ò, itémque 26. quarta sui parte
superatur a 25. Plura de Differentiarum natura ac proprietatè afferri
possent; sed nos, ne longiùs ab instituto diuagari videamur, nunc èa,
quae praesenti négocio maximè conducere videntur, memoriae mandanda
recésebimus. In Arithmetica igitur proportionalitate notandum est
differentias esse aequales, proportiones verò inaequales, ita vt maior
proportio minoribus numeris, minor maioribus contineatur. In
Geometrica contrà inaequales sunt differentiae, proportiones verò
aequales. Praeterea differentia minor ad minus extremum, maiórque ad
maius sunt numeri secundi & compositi, hoc est, qui communi mensura
coniunguntur; idque ita vt, quoties minor mensura metitur differentiam
minorem, toties maior metiatur maiorem; quod de maxima communi mensura
accipiendum est, quae non potest omnibus esse eadem, sed minor est,
quae metitur differen tiam & extremum minora, maior autem, quae
maiora. Medium quoque Geometricum ad vtrumque extremum est compositum;
non tamen vni tantùm, sed duplici subijcitur mensurae, quippe ijsdem,
quibus & differentiae; quarum alteram habet communem cum minori
extremitate, alteram cum maiori. éstque his mensuris illud proprium,
quòd eadem à se inuicem distant proportione, qua Medium ab extremis:
quare minor mensura tot partibus superatur à maiori, quot minus
extremum à Medio, Mediumque ab extremo maiori. Suntque quatuor haec in
eadem proportione, minus extremum cum Medio, Medium cum extremo
maiori, duae differentiae, & duae communes mensurae. Mensurarum verò
altera metitur Medium, differentiámque & extremum minora, altera
Medium, & differentiam atque extremum maiora. In Harmonica tandem
proportionalitate tam differentiae quàm proportiones inęquales
sunt. nam sicut proportio in numeris minoribus reperitur in
proportionalitate Arithmetica maior, & in Geometrica aequa, ita in
Harmonica minor, contráque in numeris maioribus maior. Differentiae
verò constituunt proportionem eandem cum proportione diuisa. His rectè
intellectis, facilimè percipientur ea; quae nunc de Mediorum ex
Differentijs inuentione in medium allaturi sumus. In qua illud ambigi
à nemine potest, praedictas ternas differentias potentia contineri in
Extremorum differentia confusa, quare si communis illa ac confusa
differentia distinguatur in duas partes, quales requirit quarumlibet
differentiarum natura ac proprietas; deinde pars minor (vel vtralibet,
si sint aequae, yt in Arithmetica proportionalitate) extremo addatur
minori vel maior subtrahatur à maiori, prodeunt quaesitae
differentiae. Itaque si quadruplae quaeratur medium Arithmeticum,
extremorum quadruplae, 1. & 4, Differentia confusa est 3, qua in duas
partes aquales diuisa, si pars altera [1 1/2] addatur extremo minori, vel
subtrahatur à maiori, prodit medium Arithmeticum [2 1/2], vel 5, si,
duplatis singulis, Medium integris numeris constituatur, vt in hac
figura apparet:

Exemplum Quadruplae Arithmeticè diuisae.
Proportio diuidenda.
Differentia confusa.
Eiusdem duæ partes aequales.
Medium Arithmeticum ex altera parte &e mi extre.
Proportionalits Arith.Medio fracto.

[figure 1 pdf page 75, book page 32]


Iam cùm Medium Geometricum proportiones efficiat ęquales, ęqua illa
maioris proportionis differentia (quam diximus esse eam, quae
minoribus numeris continetur) tamdiu minuenda est, donec minori
extremo coniuncta, vel reliqua à maiori subtracta, eandem ad vtrumque
extremum proportionem constituat, quod duobus modis experiri
licet. Primùm, si minor Differentia adeò sit imminuta, vt & ipsa ad
minus exrremum, & maior ad maius sint numeri secundi & compositi,
quorum maximae communes mensurae eandem seruent proportionem, quam
differentiae: quod fit, cùm toties minor mensnra metitur differentiam
minorem, quoties maior maiorem. Secundò, si medium Arithmeticum (quod
ex aequa differentia & minori extremo componi diximus) tamdiu
imminuatur, donec eandem cum vtroque extremo proportionem constituat,
quod accidit, cùm ad vtrumque videtur esse secundum & compositum, ita
vt vtriusque communis mensurae eadem sit proportio, quae Medij ad
extrema. Et hic modus superiore duabus de causis facilior esse
videtur: primùm, quòd ratio illic habetur numeri tam aucti, quàm
imminuti, hîc imminuti tantùm: deinde quòd hîc Medium statim post
imminutionem prodit, illic verò adhuc vel minorum coniunctione, vel
maioris à maiori subtractione opus est. Quamquan interim prioris modi
facilitatem id commendat, quòd & minoribus numeris (quales sunt
differentiae separatae) operatur, & minoris tantùm Differentiae
ratione habita, ea tamdiuminui potest, donec ad minus extremum numerum
compositum efficiat, qui si à Differentia confusa subtrahatur, statim
prodit Differentia maior, quae si item ad maius extremum numerum
compositum, quali requirimus mensura, constituat, nil ampliùs
quaerendum est; sin minùs, denuò eodem modo procedendum est. Vtriusque
modi exemplum proponemus in proportione 9. ad 25, cuius differentia
confusa est 16; eius dimidium 8, subtracta vnitate, fit 7, qui numerus
ad §, minus extremum, non est compositus; altera autem vnitate
subtracta, prodit 6, ad 9. compositus: quo sublato ex differentia
confusa, relinquitur maior Differentia 10, qui cùm similiter
ad 25. maius extremum sit compositus, totiesque contineat communem
mensuram suam, quae est 5, quoties 6. minorem mensuram, quæe est 3;
patet has veras esse Geometricae proportionalitatis
differentias. addita igitur minore minori extremo, vel maiore sublata
ex maiori, oritur medium Geometricum 15. Cuius operationis haec potest
esse descriptio:

MEDII GEOMETRICI INVESTIGATIO.
25. Proportio Geometricè diuidenda.
Differentia confusa.
Partes aquales Differentia confusa.
Primus ad 9, sublata Vnitate ex 8.
Compositus ad 9, sublata altera Vnitate.
Altera Differentia, sublaro 6 ex 16.
Communes mensurg in eadem proportione cum 6.& 10.
Medium Geometricum, compositum ex 6. & 9.

[figure 1 pdf page 76, book page 33]


Altero modo idem euenit, si, Differentiae confusae medietate minori
extremo addita, vel ex maiori subtracta, constituatur Medium
Arithmeticum 17, idque toties vnitate minuatur, donec ad vtrumque
extremum reperiatur compositum: occurrit autem primùm 16 qui numerus
ad neutrum extremum compositus inuenitur: sed, qui hunc sequitur, 15,
ad vtrumque compositus est, quia cum minori 9. ternarium, cum
maiori 25. quinarium communem habet mensuram, qui 3. & 5. cùm
proportione comparentur eadem, qua 15. cum alterutro extremorum;
(toties enim ternarius metitur vtriusque proportionis numerum minorem,
quoties maior quinarius maiorem) patet 15. verè esse Medium
Geometricum inter 9. & 25. Eius quoque operationis descriptionem
subiungemus.

Altera Medij Geometrici inuestigandi ratio.
25. Proportio Geometrice duuidenda.
Differentia confusa.
Differentia aquales, confusa bifariam diuisa.
Medium Arithmeticum compositum ex 8. & 9.
Idem vnitate imminutum ad 9.incompositum.
Medium Geometricum tam ad 9. quàmad 25. copositum.
Cômunes mélurx in eadé proportione in qua Med ad ertr.

[figure 2 pdf page 76, book page 33]


Medium Harmonicum ex eadem Differentia confusa eruitur,si ea diuidatur
in duas partes inaequales, quae sint eiusmodi, vt proportionem
constituant eandem cum proportione diuidenda, id hoc modo contingit:
Diuidatur Differentia confusa per minimos proportionis diuidendae
numeros similiter confusos, productum toties addatur minori extremo,
quot vnitatibus constat minor proportionis numerus: vel toties
subtrahatur à maiori extremo, quot vnitatibus constat numerus
proportionis maior. Exempli gratia, si proportio diuidenda sit 6. ad
12; eius Differentia confusa est 6: minimi proportionis diuidendae
numeri sunt 1.2; quibus confusis componitur ternarius, per quem si
diuidatur 6, prouenit binarius, qui si semel addatur minori extremo 6,
vel bis subtrahatur à maiori 12, (sicut monent minimi proportionis
numeri 1. & 2.) nascitur medium Harmonicum 8, cuius & extremorum
Differentiae, 2. & 4, proportionem constituunt eandem cum 6. & 12, vt
sequens ostendit formula:

Medij Harmonici inuestigatio.
12. Proportio Harmonicè diuidenda.
Differentia confusa.
Minimi proportionis diuidendae numeri.
lidem confusi, diuidentes Differentiam confusam.
Productum diuisionis.
Medium Harmonicum compositum ex 2. & 6.
Eiusdem differentia in cadem proportione cum diuisa.

[figure 1 pdf page 72, book page 34]


Et hocmodo retentis ijsdem terminis quàm citisime in cognitionem Medij
Harmonici peruenire possumus; cùm alij nos eôdem vel longioribus
ambagibus deducant, vel etiam terminos datae proportionis
immutent. Quòd siquis obijciat, interim saepe, & quidem in omnium
proportionum minimis numeris, occurrere fractiones; is sciat non minùs
idem in Boëtij methodo euenire. Possunt autem facilè vel fracti numeri
reduci ad integros, yel etiam, ne eos frangi necesse sit,
praecaueri. Fracti ad integros reducuntur, cùm omnes integri per
denominatorem multiplicantur, & numerator illius producto, cui
adhaerebat, aggregatur. Vt, si sit Harmonicè diuidenda
sesquialtera. eius numeri sunt 3.2, differentia confusa 1, diuisor,
numeris proportionis confusis, est 5, per quem diuisa differentia
confusa, prouenit [ 1/5 ], qui numerus si bis addatur extremo minori,
vel ter subtrahatur à maiori, prodit medium Harmonicum [ 2 2/5 ], vt
sit proportionalitas Harmonica 3 [ 2 2 / 5 2 ] quòdsi omnes integri
numeri per denominatorem 5. multiplicentur, Mediique producto
numerator 2. addatur, redit eadem proportionalitas numeris integris
15.12.10. Eodem reductionis modo suprà medium Arithmeticum reddidimus
integrum. Potest & à principio statim, ne fracti incidant, procurari;
nam si (cum differentia confusa diuisor aut maior est, aut non omnem
diuidendo absumit) minimi datae proportionis numeri per eosdem
confusos multiplicentur, termini efficiuntur eiusmodi, in quibus
minimis Medium Harmonicum integrum constitui queat. Vt in eodem
sesquialterae exemplo, si numeri proportionis diuidendae sint 3.2, vel
18.12; quoniam in prioribus differentia confusa, 1, minor est
diuisore, in alteris differentia 6. à diuisore 5. non consumitur, sed
relinquitur [ 1 / 5 ] ideo, ne incidant fracti, multiplicandi sunt
minimi numeri 3. 2. per diuisorem 5, quo facto, prodeunt 15, & 10, qui
sunt minimi numeri, in quibus integris sesquialtera Harmonice diuidi
potest, in quibus quia differentia confusa diuisori semper est
aequalis, omissa diuisione, statim numero proportionis minore minori
extremo addito, vel maiore ex maiori subtracto, prodit medium
Harmonicum. nam addito 2. minori 10, vel subtracto 3. ex 15,
relinquitur 12, cuius ad extrema differentiae sunt 3.2; quae cùm
proportionem diuisam referant, certum est 12. esse medium Harmonicum.

** [chapter 1.26]
Quo pacto demonstretur omnem Inaequalitatemab Aequalitate procedere.

CAP XXVI.

ET quoniam dubitari non potest, vt à puncto lineam, & ab vnitate
numerum, sic omnem inaequalitatem ab aequalitate procedere, superest
vt, priusquàm huic operis parti finis imponatur, id quonam pacto fieri
contingat, ostendamus; quandoquidem, non temerè, aut casu, sed certo
constantique ordine id euenire, compertum est. Nam ęqualitatem priorem
esse inaequalitate, atque illa praestantiorem, nemini dubium esse
potest, & multis in locis id asserit D. Augustinus, vnde aequalitatis
proportio prior erit inaequalitatis proportionibus; eo tamen ordine,
vt ab aequis creentur Multiplices, à Multiplicibus conuersis
Superparticulares, & à Superparticularibus conuersis Superpartientes,
à rectis autem Multiplices superpartientes, denique à
Superpartientibus rectis Multiplices superpartientes. Quod si cui
experiri lubet, disponat primùm duos terminos aequales, siue sint
vnitates, siue binarij, siue quilibet alij, qui proportionem aequam
contineant; deinde subiciat illis alteros duos, primum primo aequalium
parem, secundum ex vtroque aggregatum: & comperiet ex aequa nasci
duplam, ex dupla triplam, ex tripla quadruplam; & rursus ex dupla, sed
conuersa, sesquialteram, ex tripla sesquitertiam; mox ex conuersa
sesquialtera superbipartientem tertias, ex sesquitertia
supertriquartam; at ex recta sesquialtera duplam sesquialteram, ex
sesquitertia duplam sesquitertiam, denique ex recta superbitertia
duplam superbitertiam, ex supertriquarta duplam supertriquartam, vt
subiecta figura demonstrat:

EXAEQVISEX MVLTI-EX SVPER-EX SVPERJEX SVPER.

[figure 1 pdf page 78, book page 35]


Nos hic in duobus tantùm numeris exempla proposuimus, quòd plurium
numerorum consideratio ad Musicum non pertineat, vt in fine sequentis
libri patebit. Sed nequis interim nobis vitio verteret, quòd à Boëtij,
viri grauissimi, autoritate recesserimus, qui tam in Musica, quàm in
Arithmetica trium numerorum exempla proposuit; ipsius quoque Boëtij
nunc statim exempla breui collecta typo subiungimus.

[figure 2 pdf page 78, book page 35]


Hactenus Boëtij exempla, in quibus sciendum est, tertij numeri
procreandi regulam a prioribus differre. Nam certam numerus quisque in
sui procreatione regulam sequitur: oritur enim primus quidem ex primo,
secundus ex secundo, tertius ex tertio, & sic deinceps, verùm ita, vt
numero procreanti semper antecedentes coniungantur, quidam semel,
quidam saepiùs, vt numeri cuiusque procreandi regula docet. Regulae
igitur trium numerorum hae sunt:

Priminumeri procreandiregula.

Ponatur primus semel.

Regula secundi.

Popatur primus lemel, & secundus semel.

Regula tertij.

Ponatur primus semel, secundus bis, tertius semel.

Quòd si quis plures velit procreare numeros, pluribus indigebit &
regulis, quæ quamuis infinitae sint, sicut & numeri, in quibus
contingit procreatio; est tamen omnium conficiendarum certus quidam ac
determinatus modus, quo siquis vnam atque alteram conficeresciat,
statim omnes calleat necesse est.is, cùm à nemine hactenus descriptus
inueniatur, nobisque diuino obtigerit beneficio, benignè omnibus hoc
loco videtur esse communican dus.

** [chapter 1.27]
Quòd non à tribus tantùm, sed à quotlibet terminis equalibus omnis
mequalitas producatur.

CAP. XXVII.

BOétius hunc ine qualitatis ab equalitate processum, disciplinam
profundissimam vocat, quae ad omnem naturae vim, rerumque integritatem
maxima ratione pertineat magnumque in hac scientia fructum esse
affirmat. Quod cùm ita sit, non video curea imperfecta fuerit
relinquenda. nec enim ille eam amplius quàm in tribus numeris
ostendit: vnde & comentator eius Girardus Ruffus cocludit,
inaequalitatem quidem progigni ab aequalitate, non tamen à
quantacunque, sed à trina tantùm: idémque sentit lacobus Faber
Stapulensis in septuagesima noni lordani, cur autem eam non in
pluribus terminis aequalibus quàm in tribus ostenderint, omnes sese
excusant; Boëtius quidem, ne infinita sectaretur, & circa res
obscurissimas ingredientium animos detinens ab vtilioribus
remoraretur; Girardus Ruffus autem, quòd id pluribus in terminis fieri
nequeat, eóque rerum omnium principium vnitrinum (vt ipse vocat)
significetur, quandoquidem creationis initium sit Patet, medium
Filius, terminus Spiritus sanctus; denique Faber hanc eandem obcausam
Pythagoricos, inquit, & Magos, & Priscos sacerdotes, omnésque qui de
rebus agant diuinis, admirari aequalitatem, pariter & trinitatem in
suis arcanis in imagine numerorum venerari tacitos.

Nos trinitatis mysterijs nihil derogamus, verùm hoc loco non à trina
tantùm aequalitate, sed à quotlibet terminis aequalibus inaequalitatem
produci ostendemus: nec hanc rem adeò obscuram esse, &, vt Boëtius
opinatur, circa infinita versari, sed certis terminis, limitibus, ac
regulis comprehensam, perspicuè omnes doceri posse probabimus; idque
duplici via. primùm enim simpliciter, qua via, quibusque regulis id
fiat ostendemus: deinde, ne causa ignoretur, quamobrem his regulis id
efficiatur, perspicua demonstratione omnem haesitantibus scrupulum
mouebimus. Iamque, quod ad ostensionem attinet, tria imprimis
agemus. primùm, qui numeri à quibus oriantur, docebimus; secundò
modos, seu regulas aliquot, secundum quas haec contingit procreatio,
trademus: tertiò triplicem harum regularum conficiendarum rationem
aperiemus.

Numeri oriuntur ex aequis multiplices; ex his conuersis
superparticulares; ex superparticularibus autem rectis quidem positis
multiplices superparticulares, ex conuersis autem superpartientes;
denique ex superpartientibus rectis multiplices superpartientes. quòd
autem diximus, ex aequis oriri multiplices, id certo quodam ordine
fieri intelligendum est, ita vt primùm atque immediatè ex aequis
nascantur duplices, ex his tripli, ex triplis quadrupli & ad eundem
ordinem consequentes: quod ipsum quoque ita accipiendum est in
reliquis proportionum generibus; vt cum dico, ex multiplicibus oriri
superparticulares, significo, ex prima multiplicium specie primam
superparticularium oriri, ex secunda secundam, ex tertia tertiam, &
ita deinceps.

Contingit autem haec procreatio certis quibusdam regulis, quae tot
sunt, quot & numeri procreandi: quare cùm Boëtius non nisi vsque ad
tres numeros procederet, tres tantùm secutus est reguias: quibus nos,
breuitati studentes, tretantùm adiungemus, & in sex terminis,
inaequalitatis ab aequalitate processum ostendemus; & tandem harum
regularum confectionem, seu originem aperiemus, quaquis cognita,
infinitas eiusmodi regulas constituere possit, quibus adiutus simili
modo non tantùm in tribus, aut sex, sed quotquot libuerit terminis
procedat.

Regula prima, de procreatione primi cuiusque ordinis numeri.

Ponatur primus semel.

Regula secunda, de procreatione secundi.

Ponatur primus semel, & secundus semel.

Regula tertia, de procreatione tertij.

Ponatur primus semel, secundus bis, tertius semel.

Regula quarta, de procreatione quarti.

Ponatur primus semel, secundus ter, tertius ter, quartus semel.

Regula quinta, de procreatione quinti.

Ponatur primus semel, secundus quater, tertius sexies, quartus quater, quintus semel.

Regula sexta, de procreatione sexti.

Ponatur primus semel, secundus quinquies, tertius decies, quartus
decies, quintus quioquies, sextus semel.

Hae regulebreuiter sequenti figurae includuntur.
1 Regula prima.
Regula secunda.
Regula tertia.
Regula quarta.
6 4/1 Regula quinta.
s1/5 10 | 10 1 Regula sexta


Secundum has regulas procreantur ex aquis duplices, & ex his tripli, vt sequens demon¬
strat figura:
Anui
Dupli
Tripli
In hac figura primus ordo sex terminos aequales continet, secundus totidem duplos, ter¬
tius triplos; & inuenitur primus duplorum procreatus ex primo aequalium semel posito,
secundus ex primo & secundo, semel positis; tertius primo semel, secundo bis, tertio semei
positis; & sic caeteri secundùm praemissas regulas: eodémque modo positis duplicibus
oriuntur tripli: & duplis conuersis positis, prodeunt sesquialterae, vt in hac patet figura:
Dupliconuersi
Sesquialtera
Idem & in cæeteris generibus experirilicet. Nos ne longiores simus, nune statim mo¬
dum docebimus, quo tum praemissae regulae sunt confectae, tum quotlibet aliae, quibus ab
infinitis terminis aequalibus ad inaequalium procreationem procedatur, confici queunt.


circa quod notandum est, has regulas ex certis numeris componi, qui aduerbialiter profe
runtur, vt semel, bis, ter, quater; quos Positionum numeros appellare licebit, quòd do-
ceant, quoties quemque ex illis numeris, ex quibus alios procreare volumus, poni oporteat,
continetque prima regula numerùm positionum vnum, secunda duos, tertia tres: & pri¬
ma regula respondet primo numero procreando, secunda secundo , tertia tertio , & sic
deinceps. itaque si ex duplis velimus procreare numerum triplorum tertium, continet ter
tia regula tres positionum numeros, qui sunt, 1. 2. 1, quorum primus tribuendus est
duplorum primo, secundus secundo, tertius tertio: docetque primus primum duplorum
ponendum esse semel, secundus secundum bis, tertius tertium semel, quibus coniunctis
oritur 9, qui est tertius triplorum; vt in hac ostenditur figura.
1. Primus duplorum semel positus.
Secundus duplorum bis positus.
4. Tertius duplorum semel positus.
9. Tertiustriplorum ex duplorum collectione procreatus.
In quo exemplo illud simul obseruatu dignum est, quòd sicut in qualibet actione tria con
currunt, quae sunt agens, patiens, & modus agendi:ita & in hac numerorum procreatio¬
ne, triplices concurrunt numeri, procreans, procreandus, & is, qui docet procreandi mo¬
dum: vt in praedicto exemplo numerus procreandus est 9.tertius triplorum; procreantes
sunt tres dupli 1.2.4; quique modum procreandi docent, sunt tres positionum numeri 1.
2.1, quorum primus docet, primum duplorum ponendum esse semel, secundus secundum
bis, tertius tertium semel. Quare cùm regulae ex numeris positionum componantur, hi
quomodo nascantur, ostendendum est. utque appareat, nos nó infinita (vt Boëtius autu-
mat) sectari; rem omnem non vno tantùm limite complectemur, sed tres modos, quibus
hae regulae confici possunt, proponemus primùm enim numerorum positionum alterius
ab altero ex continua ab vnitate serie originem aperiemus: deinde singulorum ex binis
coniunctis compositionem explicabimus: denique eorundem ex ordine, quo in qualibet
regula ponuntur, ortum enodabimus.
Circa primum modum sciendum est, ex nu¬
meris positionum alium esse primum, alium secundum, alium tertium, & sic deinceps, vt
in praemissa Regularum figura apparuit. oriuntur igitur ex primis positionum numeris
secundi, ex secundis tertij, ex tertijs quarti, & sic caeteri, hoc modo: Primi positionum nu¬
meri omnes sunt vnitates, quarum prima dat primum secundorum; prima, & secunda col
lecta secundum; prima, secunda, & tertia tertium; prima, secunda, tertia, & quarta quartu:
eodémque modo collectis ordine ab vnitate secundis, oriuntur tertij, & ex tertijs quarti,
yt sequens dedarat figura:
Longitudo
Primi
Verunkh
Tertij
56 Quarti
Duwi
126 | 252 | Sexti
Altero modo coniunctis binis proximis cuiusque regulae numeris, oritur numerus sequem
tis regulae, vltimo coniunctorum in ordine respondens. Verbi gratia, ex primo, & secun¬
do oritur secundus; ex secundo, & tertio tertius; ex tertio, & quarto quartus: vt in supe-


riori regularium figura, coniunctis quintae regulae numero tertio, & quarto, oritur quar¬
tus sextae regulae. qua ratione Regularum illa figura nullo labore in infinitum extendi po
test; Sicut & proxima figura: nam & in ea numerus quisque ex duobus, qui eum, alter se¬
cundum longitudinem, alter secundum latitudinem, antecedunt, compositus esse videtur.
Sed his duobus modis tertius, quem nunc afferemus, longè praestat. Na primo modo
numeri Positionum ita alij ex alijs colliguntur, vt secundùm eum sexti procreari nequeant,
nisi praesciantur quinti; nec quinti, nisi extent quarti; nec quarti, nisi ex tertijs. Secundo mo
do similiter sextae regulae numeri constitui nequeunt, nisi ex quinta, & haec ex quarta, quar
ta ex tertia, tertia ex secunda, secunda ex prima.quare si quis, verbi gratia, regulam vigesi
mam nosse velit, omnes ordine regulas vsque ad vigesimam componat necesse est. Tertio
autem modo numeri alij quidem oriuntur ex alijs, verùm ita, vt omnes sint eiusdem regu
le atque ordinis, nec alterius ordinis numeri praeexigantur. idque hac obseruatione: Quae
proportio est numeri inuentorum ad inueniendos, eadem est proportio inter vltimò in¬
uentum, & primum inueniendorum. vt siquis numeros Quintae regulae, qui quinque sunt,
inuestigare velit, primus erit vnitas: (idque generaliter in omnibus regulis) inuento vno,
restant inueniendi quatuor; quae igitur proportio est inter vnum & quatuor , eadem est
inter inuentum, qui erat 1, & inueniendum, qui ob id erit 4: inuentis duobus, restant in¬
ueniendi tres; quae igitur est proportio inter inuentos duos, & inueniendos tres, hoc est,
inter 2. & 3, eadem erit inter vltimò inuentum, qui erat 4, & primum inueniendorum, qui
idcirco erit 6: inuentis tribus numeris, restant inueniendi duo; quae igitur est proportio
inter 3. & 2, eadem erit inter vltimò inuentum, hoc est, 6, & primum inueniendorum, is
igitur erit 4: iam quatuor inuentis, vnus inueniendus restat; sed & vltimus inuentorum
fuit 4, ergo 1. tribuetur inueniendo. Nunc antè, quàm demonstratione exordiamur,
pauca quaedam, scitu non iniucunda, quae circa mirum horum numerorum ordinem ac
connexionem obseruauimus, exponemus. Quorum primum est, quòd numeri à medio.
vel à medijs aequidistantes sunt aequales, maximusque medius existit, minimi verò pri¬
mus, & vltimus; à quibus tanquam gradibus aequalibus ad medium ascenditur: vel potiùs
à primo usque ad medium ascenditur, móxque ijsdem gradibus ad vltimum desceditur:
sicut Sol à parte Horizontis orientali ysque ad circulum Meridianum ascendit, deinde to
tidem gradibus ad Occidentem denuò delabitur. exemplum huius obseruationis esto re¬
gula decima, & vndecima: decimae regulae numeri sunt, 1. 9. 36.84. 126. 126. 84. 36. 9. 1;
vndecimæe, 1.10.45. 120.210.252. 210. 120. 45. 10. 1. est autem Medius numerus nunc
vnus, nunc duo: vnus quidem in regula tertia, quinta, septima, caeterisque imparibus; duo
verò in regula quarta, sexta, octaua, ac reliquis paribus. Alterum est, quòd in regulis impa
ribus primus Medius ad duos vicinos, inter quos immediatè ponitur, constituit propor¬
tionem duplam, secundus sesquialteram, tertius sesquitertiam, quartus sesquiquartam, &
sic caeteras proportiones superparticulares, yt in his numeris ostenditur:
Numeri Positionum.
Ex regula tertia.
Dupla
Ex regula quinta.
Sesquialtera
Ex regula septima.
Sesquitertia
Ex regula nona.
Sesquiquarta
Ex regula vndecima.
Sesquiquinta


Tertium, quòd in regulis paribus, duo medij aequales ad circumuicinos proportionem ef
ficiunt primi triplam, secundi duplam, tertij superbipartientem tertias, quarti sesquialte¬
ram, quinti superbipartientem quintas; & sic alternatim, per superparticulares, & super¬
partientes omnes, procedunt, vt in his numeris apparet:
Numeri Positionum.
Tripla
Exregula quarta
Ex regula sexta
Dupla
Superbipartiens tertias
Ex regula octaua
Sesquialtera
Ex regula decima
Superbipartiens quintas
Ex regula duodecima
Quartum & vltimum est, quòd numeri positionum cuiusque regulae collecti, constituunt
ordinem duplorum. nam prima regula continet vnitatem, secunda duas, tertia quatuor,
quarta 8, quinta 16, vt in praemissa Regularum figura, numeris vniuscuiusque regulae col
lectis, videre licet.
Inaequalitatis ab aequalitate processus Demonstratio.
CAP. XXVIII.
HVnc de afferenda Demonstratione datam fidem liberamus. Ad eam verò quibus¬
dam tum Definitionibus, tum Sententijs communibus indigemus, quas statim
praemittimus.
Definitio prima
Numerus Simplex est, qui alterum, ad quem simplex dicitur, semel continet: Multiplex.
qui saepiùs; Duplex, qui bis: Superparticularis, qui semel, & partem; Sesquialter, qui semel.
& partem dimidiam: Superpartiens, qui semel, & duas partes; superbipartiens tertias, qui
semel, & duas tertias: Multiplex superparticularis, qui saepiùs, & partem; Duplus sesquial¬
ter, qui bis, & partem dimidiam: Multiplex superpartiens, qui saepiùs, & partes; Dupius su
perbipartiens, qui bis, & duas partes; Duplus superbipartiens tertias, qui bis, & duas tertias.
Definitio secunda
Originales numeri dicuntur, quibus positis alij procreantur.
Definitio tertia.
Numeri Positionum sunt, quiindicant, quoties quemque Originalium numerorum,
yt ex eis alius procreetur, poni oporteat.
Prima communis Sententia
Vnusquisque numerus, semel positus, sibi similem procreat.
Secunda.
Ordo numerorum continuus usque ad senarium in quolibet proportionum genere
talis est:


1AEQVALES.
AEquales.
Dupli.
8. 16. 32.MVLTIPLICES.
Dupli conuersi.
IMVLTIP. CONVERSI.
Sesquialteri.
32. 48. 72. 108. 162. 243. SVPERPARTICVLARES
Dup. sesquialteri.
32. 80. 200. 500. 1250. 3125. MVL. SVPERPARTICVLA.
Sesquialte. couer. 243. 162. 108. 72. 48. 32. SVPERPARTIC.CONVER.
Superbipartientes. 243.405. 675.1125. 1875. 3125. SVPERPARTIENTES.
Dup. suphipartiem. 243. 648. 1728. 4608. 12288. 32768. MVL.T. SVPERPARTIENT.
Tertia
Dupli numeri oriuntur, cùm numero proximè antecedenti, vel eius originalibus addi
tur simplum; Tripli, cùm duplum: Quadrupli, cùm triplum: Sesquialteri, cum pars altera;
Sesquitertij, cùm tertia: Superbipartientes tertias, cùm duae tertiae; Supertriquarti, cùm
tres quartae: Dupli sesquialteri, cum simplum, & pars altera: Dupli superbitertij, cùm sim
plum, & duæ tertia, & sic deinceps.
Quarta..
Simplum, Duplum, Triplum alicuius numeri, dicitur sequens eiusdem ordinis nume¬
rus. similiter & Subduplum, Subtriplum, sequens numerus dicitur, sed ordine conuerso.
Idem dicendum est in coeteris proportionum generibus, vt in singulis ordinibus secun¬
dae Communis Sententiae videre est.
Argumentum sequentium propositionum.
Prioribus quinque propositionibus ostenditur, ac demonstratur, qui numeri quorum
sint Originales: numeri autem Positionum sex deinde sequentibus propositionibus de¬
monstrantur.
Propositio prima..
Ex Aequalibus Dupli, ex Duplis Iripli, reliquique ex ordine Multiplices oriuntur.
Sit numerus Duplus 2, erit igitur duplus ad 1; (per primam definitionem) cui si adda¬
tur simplum, oritur 2: (per tertiam communem sententiam) Simplum verò eius est sequens
numerus: (per quartam communem sententiam) quaeratur igitur Ordo numerorum, in
quo numerum quemlibet datum sequatur simplum; nec inuenietur nisi Ordo AEqua¬
lium. (per primam definitionem, & per secundam communem sententiam) Quod ipsum
similiter in Triplorum à Duplis origine, coeterisque ad eundem modum consequentibus
Multiplicibus demonstrari potest: quare patet, ex AEqualibus Duplos, ex Duplis Triplos,
reliquósque deinceps Multiplices oriri.
Propositio secunda
Ex Multiplicibus Conuersis oriuntur Superparticulares.
Sit 3. Sesquialter, eritque sesquialter ad 2; (per primam definitionem) cui si addatur di-
midium, oritur 3: (per tertiam communem sententiam) dimidium verò eius dicitur se¬
quens numerus: (per quartam communem sententiam) quaeratur igitur Ordo numero¬
rum, in quo binarium sequatur dimidium; nec inuenietur, nisi ordo Duplorum. (per pri¬
mam definitionem, & secundam communem sententiam) Similiter & Sesquitertios ex
Triplis, Sesquiquartos ex Quadruplis, coeterósque Superparticulares ex coeteris Multipli
cibus Conuersis oriri ostendi potest: constat igitur, ex Multiplicibus Conuersis oriri Su
perparticulares.
Propositio tertia
Ex Superparticularibus oriuntur Multiplices superparticulares.
Sit 5. Duplex sesquialter, eritque talis ad 2, (per secundam communem sententiam) cui


si addatur simplum & dimidium, efficitur 5: (per tertiam communem sententiam) sed
simplum & dimidium refertur ad numerum proximè sequentem; (per quartam communen
sententiam) neque in yllo numerorum Ordine binarium, vel quemcunque alium nume
rum simplum & dimidium sequi reperitur, praeterquàm in Sesquialteris: (per secundam
communem sententiam) ergo ex Sesquialteris oriuntur Dupli sesquialteri, & ex illis Tri
pli sesquialteri, & coeteri Multiplices. Simili modo ostendi potest, ex Sesquitertijs oriri Du
plos sesquitertios, & ex Sesquiquartis Duplos sesquiquartos, & ita deinceps: quare patet
ex Superparticularibus oriri Multiplices superparticulares.
Propositio quarta.
Ex Superparticularibus conuer sis oriuntur Superpartientes.
Sit 5. Superbipartiens tertias, eritque talis ad 3; (per primam definitionem) cui si addan
tur duae tertiae, oritur 5: (per tertiam communem sententiam) sed duae tertiae Ternarij di
citur numerus ternarium in eodem ordine proximè sequens; (per quartam communem
sententiam) nec nisi in Sesquialteris conuersis talis reperitur: (per secundam communem
sententiam) ergo ex Sesquialteris conuersis oriuntur Superbipartientes. Similiter ex Ses¬
quitertijs Supertripartientes, coeterósque deinceps superpartientes oriri demonstrari po¬
test: ergo ex Superparticulatibus Conuersis oriuntur Superpartientes.
Propositio quinta
Ex Superpartientibus oriuntur Multiplices superpartientes.
Sit 8. Duplus superbipartiens tertias, eritque 3. eius subduplus superbitertius; (per pri¬
mam definitionem) cui si addatur simplum, & duae tertiae, hoc est, proximè sequens nu¬
merus (per quartam communem sententiam) orietur 8: (per tertiam communem senten
tiam) Sed in nullo numerorum Ordine reperitur ternarium sequi simplum & duae tertiae,
nisi in Superbipartientibus: (per secundam communem sententiam) ergo ex Superbipar
tientibus oriuntur Dupli superbipartientes, & ex ijs Tripli superbipartietes, aliique dein¬
ceps Multiplices. Similiter & ex Supertripartientibus Duplos supertripartientes, ex Su¬
perquadripartientibus Duplos superquadripartientes, & ita deinceps oriri ostendi potest:
ergo liquet, ex Superpartientibus oriri Multiplices superpartientes.
Colligitur ex his quinque propositionibus, numeris quibusibet rectis quidem positis,
oriri Multiplices tam puros, quàm mixtos, seu compositos; illos exAEquis, hos ex Super
particularibus & Superpartietibus: ita yt ex Simplicibus Duplices, ex Duplicibus Tripli¬
ces, & sic deinceps nascantur, è Conuersis verò Multiplicibus Superparticulares & ex his
Superpartientes.
Propositio sexta.
Primus semel positus procreat primum.
Primus Duplorum est Vnitas; (per secundam communem sententiam) quam nequis fal
so existimet ideo in omnium Multiplicium Ordinum principio poni, quòd non nume
rus, sed principium sit numerorum, dico eam hoc loco pro numero poni: non enim al
Vnitatibus, sed ab AEqualibus numeris, qualescunque illi sint, Inaequales, primumque
Duplos oriricontendimus. quapropter, cùm pro numero ponatur, alia opus est demon¬
stratione; quod ipsum & reliqui omnes, qui Multiplices sequuntur, Ordines confirmant,
in quibus locum Vnitas ne quidem sortitur vllum, nedum primum. Dico igitur primum
numerum à primo, semel posito, procreari; quia numerus quisque semel positus parem
libi procreat: (per primam communem sentetiam) primus autem in omnibus ordinibus,
praeterquàm in aequalibus, soli primo par reperitur: (per secundam communem senten¬
!! In AEqualibus quoque à primo
tiam) ergo primus semel positus primum procreat.


semel posito primum Duplorum procreari probari potest. Sit enim primus Duplorum
Vnitas; is cùm ab AEqualibus generetur, (per primam propositionem) AEqualium quoque
ordinom ex Vnitatibus componi necesse est. Oritur autem à Prima vnitate. nam si ab alia
oriatur, ea primam aut antecedet, aut sequetur:non antecedit; (per secundam communen
sententiam) nec sequentium vlla est prima: (per eandem) ergo, cum haec prima sit Duplo¬
rum, id à prima habeat necesse est. (per primam communem sententiam ) Huc accedit,
quòd à primis secundi,non à secundis primi oriuntur: (per tertiam communem senten-
tiam) qui nihilominus Secundi, non Primi, dicendi sunt, quòd non à solis primis, sed, dum
illis accedunt, oriuntur.
Propositio septima¬
Primus & secundus, semel positi, procreant secundum.
Secundus Duplorum est 2, (per secundam communem sententiam) quem antecedit
vnitas; (per eandem) cui, vel Originali eius si accedat simplum, procreatur 2: (per tertiam
communem sententiam) Originalis verò eius est primus AEqualium semel positus; (per
praecedentem propositionem) cuius simplum est proximè sequens numerus, (per quartam
communem sententiam) idque si semel ponatur, alioqui non esset simplum seu simile: (per
primam communem sententiam) quare primus & secundus AEqualium, semel positi, se¬
cundum Duplorum procreant. Similiter à primo & secundo Duplorum semel positis, secundum
Triplorum procreari, idémque eodem modo in coeteris proportionum generibus ac spe¬
ciebus ita sese habere ostendi potest: ergo in vniuersum primus & secundus, semel positi,
procreant tertium. Eodem modo in sequentibus propositionibus, quod nos, breuitatis
causa, de sola Duplorum specie dicimus, de omnibus proportionum generibus, ac spe¬
ciebus, dictum, ac conclusum intelligi debet.
Propositio octana.
Primus semel, secundus bis, tertius femel, positi procreant tertium.
Tertius Duplorum numerus est 4, (per secundam communem sententiam) quem an¬
tecedit 2, (per eandem) cui, vel originalibus eius numeris simplo addito, procreatur 4: (per
tertiam communem sententiam) sed originales binarij sunt AEqualium primus & secun
dus numerus, semel positi, (per praecedentem) quorum simplum sunt proximè sequentes
numeri: (per quartam communem sententiam) ergo primo & secundo semel positis, se¬
mel quoque ponendi restant proximè sequentes numeri, hoc est, secundus & tertius. qui-
bus positionibus coniunctis, sequitur ponendum esse primum semel, secundum bis, ter¬
tium semel, vt sequens declarat figura:
L
secundus
Ordonumerorum ponendorum
Prunus
semel
Prima positiones
Send
Femel
semel
Secundae positiones
semel
bis
Summa poltionum
semel
Propositio nona
Primus semel, secundus ter, tertius ter, quartus semel, positi procreant quartum.
Quartus Duplorum est 8, (per secundam communem sententiam) quem antecedit 4;
(per eandem) cui, vel Originalibus eius si adijciatur simplum, procreatur 8: (per tertiam
communem sententiam) sed Originales quaternarij sunt primus semel, secundus bis, ter¬
tius semel, positi; (per praecedentem) & horum simplum sunt (per quartam communem
sententiam) proximè sequentes numeri, qui sunt secundus semel, tertius bis, quartus se¬
mel: his igitur positionibus omnibus coniunctis, patet primo semel, secundo & tertio ter,


quarto semel, positis, procreari quartum; quod in sequenti typo clariùs perspicitur.
primus
secundus
Ordo numerorum
tertius
quartus
Eenel
bis
Prime positione:
semel
semel
Secundae positiones
bis
semel
ter
semel
ter
uma pelionun
Iemel
Propositio decima.
Primus semel, secundus quater, tertius sexies, quartus quater, quintus semel, posi
ti, procreant quintum.
In Duplis quintus est 16, (per secundam communem sententiam) quem antecedit 8;
(per eandem)cui, vel originalibus eius adiecto simplo, generantur 16: (per tertiam com¬
munem sententiam) sed originales octonarij sunt primus AEqualium semel, secundus &
tertius ter, quartus semel, positi; (per praecedentem) simplum autem horum sunt numeri
proximè sequentes: (per quartam communem sententiam) coniungatur igitur Origina¬
libus simplum (quod est secundus semel, tertius & quartus ter, quintus semel, positi) & pa
tebit manifestè, quintum numerum procreari, dum ponitur primus semel, secundus qua¬
ter, tertius sexies, quartus quater, quintus semel, vt sequens ostendit figura:
primus
secundus
Ordo numerorum
tertius
quartus
quintu.
ter
semel
ter
Prima positiones
semel
ter
semel
ter
Secundae positiones
Kemel
semel
sexies
quater
Summapositionum
Iemel
quater
Propositio ondecima
Primus semel, secundus quinquies, tertius & quartus decies, quintus quinquies,
sextus semel, positi constituunt sextum.
Sextus Duplorum numerus est 32, (per secundam communem sententiam) quem an¬
tecedit 16, (per eandem)cui, vel originalibus eius si accedat simplum, procreatur 32: (per
tertiam communem sententiam) originales verò 16. sunt primus AEqualium semel, secum
dus quater, tertius sexies, quartus quater, quintus semel, positi, (per praecedentem) & ho¬
rum simplum sunt proximè sequentes numeri: (per quartam communem sententiam) po
sitis igitur & proximè sequentibus numeris secundo semel, tertio quater, quarto sexies,
quinto quater, sexto semel, patet his cum superioribus, quorum sunt simplum, coniunctis,
ad sexti numeri procreationem primum ponendum esse semel, secundum quinquies, ter
tium & quartum decies, quintum quinquies, sextum semel, quod ex sequenti typo liqui¬
diùs colligere licet.
Ln
quintus
NAE
vertiu
Ordo numerorum
Prmn
Ferundus
semel
quater
series
semel
quater
Prime geluiones
Fena
quater.
quater
Eens
sexies
Secunda positiones
decies quinquies semel
quinquies
decies
semel
Summa positionu
Hae sex vltimae propositiones sex regulis suprà traditis respondent, quibus pauciores tra
dere noluimus; ne, si nulla exemplorum appareret varietas, obscuri esse videremur. sed
nec pluribus exemplis opus est, quando innumerae aliae regulae eodem modo, quo sex prę¬
!! Quòd si quis hîc nobis obijciat, non nisi
dictæe, & confici, & demonstrari possunt.


duorum numerorum considerationem ad Musicum pertinere, ideóque nos ne quidem
ad tres, nedum ad sex usque procedere oportuisse:Respondemus eandem esse scientiam
paucorum & plurium; nec posse quenqua, quod in pluribus quomodo se habeat ignorat,
eius certam in vno atque altero assignare rationem. Nos igitur, qui scientiae tradedae mu
nus suscepimus, non immeritò pluribus vsi sumus exemplis; quando sine illis nec duarum
!! Si quis has
illarum regularum, quae ad nos pertinent, scientia perfectè haberi potest.
sex propositiones breui figurae inclusas intueri cupiat, is sciat huic loco planè eam conue-
nire, quam in capite praecedenti de sex regulis proposuimus.
Multa quidem alia, scitu
dignissima, de numerisac eorum inter se comparationibus afferri potuissent, sed hęc
potissimùm visa sunt nobis, quę de priori subiecti Musicę parte, quę ad nu¬
merum pertinet, Harmonicus considerare deberet. nunc ad po¬
steriorem, quae ad sonos spectat, diuini numinis auxilio
copiosiùs explicandam pergemus.
PRIMI DE MVSICA LIBRI
FINIS.
