#+title: Salinas: Seven Books on Music
#+subtitle: An attempt to summarize
#+author: Johannes Keller
#+startup: overview

#+OPTIONS: html-style:nil
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" href="style.css" />
#+HTML_HEAD_EXTRA: <script type="text/javascript" src="image-processing.js"></script>
#+HTML_HEAD_EXTRA: <link rel="preconnect" href="https://fonts.googleapis.com">
#+HTML_HEAD_EXTRA: <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
#+HTML_HEAD_EXTRA: <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap" rel="stylesheet">

#+startup: overview


# Math notation:
#   Testing \( \frac{1}{2} \) within a line.

* Comments
** What this is
This is a personal project. No guarantees for correctness. Everything
is done with the best intentions. Errors, misunderstandings and lack
of awareness of the historical context are to be expected. Corrections
are welcome anytime. There is no promise concerning the time frame of
this project.

** Process
1. The latin original is processed with Transkribus.
2. The plain text (.txt) output is manually converted into org-mode
   syntax. All illustrations are cropped form the images of the source
   and linked into the org file. Line breaks are manually resolved.
3. This org file is translated into English using Kagi Translate and
   stored in a new org file with the same structure and links to
   images.
4. The English text is manually sectioned, obvious mistakes are
   corrected. This edited version is stored in a new org file,
   maintaining the document structure and links to image files.
5. This version of the text is then summarized. The summary is stored
   in yet a new org file, maintaining its structure the links to the
   images.
6. All org files are exported to HTML. Only the file salinas-summary
   is intended for readers, the others are only kept for archival
   purposes and to make the process transparent.
   - salinas-lat
   - salinas-en
   - salinas-en-edited
   - salinas-summary
7. [Future] Music theoretical thoughts are expressed in code and
   embedded into the HTML file, ideally in an interactive
   fashion. Where applicable, audio rendering will be included.

The long term goal is to create a representation of Salinas' thinking
in code to make it available for easy integration in audio
applications and further computational analysis or artistic
exploration.

* Preface
The human voice is unique, because compared to animal sounds it can
speak and sing.

These two gifts are reflected in grammar and music, which are the
science of speaking correctly and singing well respectively.

The two disciplines are closely related: speech consists of letters
that form sillables, which form words. Music consists of sounds that
form intervals, which form consonances and progressions. For both,
pitch and rhythm are the defining parameters of their mode of
operation.

Speech and music differ in the fact that speech relies solely on the
authority of the speaker while music can be defined by mathematical
principles which form the categories of true and false.

According to [[https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0058%3Abook%3D8][Aristotle, Book 8 of _Politics_]] Music is necessary to
fuse honor and pleasure.

Beyond pleasure, teaching and learning music also increases moral,
since searching for truth and exposing the mind to it forms a deep
connection to moral values. This is confirmed by Boethius.

Boethius further recommends to train children in music, and noble
persons will find delight in music that is of a kind that doesn't need
regret.

Plato identifies in music a power to make humans more humane by giving
the example of a man who changed his mind to harrass a woman based on
the influence of a song he heard.

Persons who live outside of society can be drawn back to community by
the power of song. Religious people deepen their devotion through
chanting, alluding to the singing of angels.

All nations and religions use song to worship their gods. Jewish
people use 238 singers and many instruments in Solomon's
temple.

For christians, David is a musical idol. Testimonies of St. Hilary,
St. Augustine and St. Jerome confirm the importance and power of
music. Gregory and Ambrose composed many hymns that contribute to the
musical christian heritage.

A rudimentary mathematical knowledge is enough to understand the
benefits of the study of music. The seven books of music contains
truths about music that have been collected in many years with great
diligence.

Since I was born blind without any hope for gaining eyesight my
parents decided to provide for my musical education. Trained in
singing and organ playing, I mainly studied music in its abstract
form, as described by authors such as Aristoxenus, Ptolemy and
Boethius.

I learned Latin from a woman who stayed in our home when I was still a
boy, and I taught her music in exchange. This produced an appetite for
deeper study, which lead me to Salamanca, where I devoted myself to
study Greek, the arts and philosophy.

Having been very poor I was dependent on the generosity of Archbishop
of Compostella Peter Sarmento who introduced me to several Cardinals
in Rome. There I learnt music theory, which completed my practical
musical training I had received already. Practical musicians without
theoretical knowledge are unable to gain authority in their field,
while theorists who don't establish their own practice risk to chase
phantoms.

After having studied Aristotle's teachings on ratios, consonances and
harmonic intervals I discovered that music consists of more intervals
than what Artistotle provided ratios for. To investigate this further
I read Greek manuscripts that have not yet been translated into Latin,
namely [[https://brill.com/display/title/6825][Ptolemy]], [[https://en.wikipedia.org/wiki/Elementa_harmonica][Aristoxenus]], [[https://archive.org/details/manualofharmonic0000nico][Nicomachus]], [[https://www.oxfordreference.com/display/10.1093/acref/9780198662778.001.0001/acref-9780198662778-e-5768][Bacchius]], [[https://www.cambridge.org/core/journals/early-music-history/article/abs/aristides-quintilianus-on-music-in-three-books-translation-with-introduction-commentary-and-annotations-by-thomas-j-mathiesen-new-haven-and-london-yale-university-press-1983-xiii-217-pp/40B80D4BE6355D8E594CF67064B7A2B3][Aristides]] and
[[https://en.wikipedia.org/wiki/Manuel_Bryennios][Briennius]].

After more than 23 years of examination and research I came to a more
complete understanding. But I was also confronted with many deaths of
people around me, financial supporters and family members alike. This
forced me to return to Spain, where I chose a life in honorable
poverty.

Luckily, the Academy of Salamanca understood the importance of the
teaching of music, in theory as well as in practice.

King Alfonxo X. of Castille founded or reformed the Academy and was
fully aware of the importance of music as a mathematical discipline
and a practical field alike. I went to Salamanca to apply for the
position of professor of music, which was given to me.

Back to the topic of music. Romans, Italians, Spaniards, Germans,
French and Britons have studied, enhanced and transformed ancient
knowledge and found their own ways of articulating it.

The only exception though is music. In no other discipline is it
acceptable to openly display incompetence without shame. One of
hundreds of examples: eveybody knows that a tone is the difference
between a fifth and a fourth, but virtually nobody can name its
proportion.

Only some individuals, mainly Italians and French, can be found who
invested time and effort into a thorough understanding.

It is notoriously rare that people who are most interested in a
subject are able to received an adequate education. Therefore I
decided to publish this treatise which aims at those who want to truly
understand my thoughts. I overcame my hesitation which is based on the
expectation that many scholars will critizise my thoughts and will
fight them with ancient authors.

I carefully studied ancient and recent authors and I state with
confidence, that nobody has gone as far as myself in terms of
arithmetics, which is the universal abstraction of music, independent
of time, culture and religion.

There are great differences in opinion and approach among ancient
authors, such as Pythagoras and Nicomachus, Ptolemy and Aristoxenus,
who expressed various divisions of the diatessaron, which is the most
central structure of our science. We will therefore examine their
views thoroughly to seek truth.

More recent authors have to be judged differently, since they didn't
have access to the knowledge of many ancient authors because many of
them are not translated into Latin. Nevertheless they came up with
relevant aspects that we will integrate into our search for truth.

We are going to start our great journey, looking carefully into all
the many details, but without losing a sense for the bigger
picture. We will come to a profound understanding that is desired by
many, but accessible to only a few.

There will be many aspects that might be seen as unnecessary or
pedantic to experts, but I claim that all these details and
complications are relevant. Furthermore, to grasp the science of music
in its entirety, knowledge of almost all disciplines is necessary.

A true expert needs to be trained in singing, instrument making,
symbolic arithmetic, computation and geometry. Musical truth can be
established through proofs in arithmetics and geometry.

Furthermore the expert needs to know Greek, since the works of most
ancient authors are only available in Greek, and the modern
terminology still uses mainly Greek terms. The aspect of rhythm in
music is based on language, therefore knowledge of poetry is required
as well.

The entire knowledge contained in this treatise is taken from various
ancient and recent books, conversations with experts, and my own
reasoning. It is organised into seven books. The first four books are
dedicated to pitch, the other three books to rhythm.

The first book contains everything a musician needs to know about
numbers and proportions.

In the second book, the knowledge of the first book is transferred
into the realm of sound. We will look at individual sounds, and how
they form intervals.

In the third book we construct scales and tuning systems out of the
intervals established in the second book. We will apply them to real
life instruments such as keyboard instruments and fretted instruments.

In the fourth book we introduce an unconventional approach to modes
and tones. We will focus on the ideas of Ptolemy, who has been absent
in recent music theory. We will examine the assertions of ancient and
recent theoretical approaches.

The fifth book is the first book about rhythm. We are going to discuss
meter and feet and how they can be divided and joined.

In the sixth book we discuss the various species of poetic meters and
how they manifest in music.

In the seventh book we discuss the constitution and perfection of
verses. We will close the treatise with all the aspects that have been
neglected so far.

I use a consistent language to construct a coherent line of thought,
embracing ideas that are articulated in very different ways. To keep
the original thought transparent, I often add quotes from my sources.

Furthermore, we have instruments available today that were not in use
at the time of many of my sources, for example the instrument called
"Lautum" or "Viola", which is played with a plectrum or by
hand. Certainly music has been taught very differently in the past,
the only thing we have to connect to it is language.

Another modernization is the addition of Spanish, French and Italian
meters to the original ones in Greek and Latin.

It was necessary to demonstrate truth in harmony through numbers, and
truth in rhythm through songs that can be treated as numbers
metaphorically.

Before this preface, already way longer than a prologue, grows into
its own book, we stop here.

Juan Lopez de Velasco: his review is unequivocally in favor of
printing this treatise, since its quality is above anything that is
available, its content is solid, and it is beneficial to all
theoretical and practical musicians.

Juan Fernandez de Herrera, Secretary of the Council of His Majesty
confirms that all the volumes of this treatise are licensed to be
printed on paper and published. 6th of November 1577.
