#+title: Salinas: Seven books on music
#+subtitle: Summary
#+author: Johannes Keller
#+startup: overview

* Comments

* Preface

The human voice is unique, because compared to animal sounds it can
speak and sing.

These two gifts are reflected in grammar and music, which are the
science of speaking correctly and singing well respectively.

The two disciplines are closely related: speech consists of letters
that form sillables, which form words. Music consists of sounds that
form intervals, which form consonances and progressions. For both,
pitch and rhythm are the defining parameters of their mode of
operation.

Speech and music differ in the fact that speech relies solely on the
authority of the speaker while music can be defined by mathematical
principles which form the categories of true and false.

According to [[https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0058%3Abook%3D8][Aristotle, Book 8 of _Politics_]] Music is necessary to
fuse honor and pleasure.

Beyond pleasure, teaching and learning music also increases moral,
since searching for truth and exposing the mind to it forms a deep
connection to moral values. This is confirmed by Boethius.

Boethius further recommends to train children in music, and noble
persons will find delight in music that is of a kind that doesn't need
regret.

Plato identifies in music a power to make humans more humane by giving
the example of a man who changed his mind to harrass a woman based on
the influence of a song he heard.

Persons who live outside of society can be drawn back to community by
the power of song. Religious people deepen their devotion through
chanting, alluding to the singing of angels.

All nations and religions use song to worship their gods. Jewish
people use 238 singers and many instruments in Solomon's
temple.

For christians, David is a musical idol. Testimonies of St. Hilary,
St. Augustine and St. Jerome confirm the importance and power of
music. Gregory and Ambrose composed many hymns that contribute to the
musical christian heritage.

A rudimentary mathematical knowledge is enough to understand the
benefits of the study of music. The seven books of music contains
truths about music that have been collected in many years with great
diligence.

Since I was born blind without any hope for gaining eyesight my
parents decided to provide for my musical education. Trained in
singing and organ playing, I mainly studied music in its abstract
form, as described by authors such as Aristoxenus, Ptolemy and
Boethius.

I learned Latin from a woman who stayed in our home when I was still a
boy, and I taught her music in exchange. This produced an appetite for
deeper study, which lead me to Salamanca, where I devoted myself to
study Greek, the arts and philosophy.

Having been very poor I was dependent on the generosity of Archbishop
of Compostella Peter Sarmento who introduced me to several Cardinals
in Rome. There I learnt music theory, which completed my practical
musical training I had received already. Practical musicians without
theoretical knowledge are unable to gain authority in their field,
while theorists who don't establish their own practice risk to chase
phantoms.

After having studied Aristotle's teachings on ratios, consonances and
harmonic intervals I discovered that music consists of more intervals
than what Artistotle provided ratios for. To investigate this further
I read Greek manuscripts that have not yet been translated into Latin,
namely [[https://brill.com/display/title/6825][Ptolemy]], [[https://en.wikipedia.org/wiki/Elementa_harmonica][Aristoxenus]], [[https://archive.org/details/manualofharmonic0000nico][Nicomachus]], [[https://www.oxfordreference.com/display/10.1093/acref/9780198662778.001.0001/acref-9780198662778-e-5768][Bacchius]], [[https://www.cambridge.org/core/journals/early-music-history/article/abs/aristides-quintilianus-on-music-in-three-books-translation-with-introduction-commentary-and-annotations-by-thomas-j-mathiesen-new-haven-and-london-yale-university-press-1983-xiii-217-pp/40B80D4BE6355D8E594CF67064B7A2B3][Aristides]] and
[[https://en.wikipedia.org/wiki/Manuel_Bryennios][Briennius]].

After more than 23 years of examination and research I came to a more
complete understanding. But I was also confronted with many deaths of
people around me, financial supporters and family members alike. This
forced me to return to Spain, where I chose a life in honorable
poverty.

Luckily, the Academy of Salamanca understood the importance of the
teaching of music, in theory as well as in practice.
