* [Preface]
FRANCISCI SALINAE BVRGENSIS IN libros de Musica Praefatio.

INter omnium animantium voces meritò vox humana principem locum
obtinere censetur: quoniam ea sola loquendi & canendi facultate
praedita est. Vnus enim homo verè ac propriè dicitur capere & loqui:
caetera verò animalia per analogiam quandam & similitudinem, yt prata
atque aquæ ridere dicuny tur. Quae duo munera vt exactius ac
perfectius exercere posset, obseruatio cum ratione coniuncta
Grammaticam & Musicam artium antiquissimas inuenit: quarum alteram
antiqui rectè loquendi, alteram benè modulandi scientiam esse
dixerunt. Sunt autem ab ipsis primordijs adeò similes, vt non sorores
modò, sed pene gemellae fuisse censeantur. Nam quemadmodum Grammatica
initium sumit à literis, à quibus nomen accepit: deinde per syllabas,
quae ex literarum permixtionibus fiunt; ac per dictiones, quae ex
syllabarum coniunctione conflantur, ad orationem perficiendam
peruenire contendit: sic etiam Musica à Musis, quibus omnimodam
canendi peritiam tribuebat antiquitas, nuncupata, ex sonis ac
interuallis ex sonorum permixtione sactis, & ex consonantijs, quae
fiunt ex interuallorum coniunctione, melos siue cantum conficit atque
componit. Et sicut loquutio subsistere non potest, nisiratio in ea, &
in dictionibus accentum, & in syllabis quantitatis habeatur, vt per
alterum sublatio vocis ac depressio, per alterum exacta syllabarum
breuitas & longitudo seruetur: ita etiam & multò (vt ita dicam)
naturaliùs ac veriùs id in musica custoditur: ex quibus illud ad
harmoniam, hoc ad rhythmum duas musicae partes, quae totam ipsius vim
intra se continent, spectare dignoscitur. Differunt tamen nihilominis
Grammatica & Musica, quòd illius disciplina ex veterum, qui bene
loquuti sunt, vsu collecta, sola nititur autoritate dicentis: huius
verò doctrina ex ipso rationis aeternae fonte procedens, veritatem
suarum assertionum ineluctabi libus argumentis, & mathematica semper
ratione demonstrat. Inter præecipuas autem disciplinas, quibus antiqui
sapientes philosophantium animos excultos esse debere censuerunt,
honoratissimum semper musicae doctrina locum obtinuit: cuius
euidentissimo est argumento, quod ex Philosophis, quorum vitae
literarum monumentis mandatae sunt, nullus ferè est, qui non in musica
praeceptorem habuisse dicatur. Cuius scientiam atque vsum non minus
viro ciuili, quàm philosopho necessarium esse multis de causis
Aristoteles toto ferè libro Polyticorum octauo determinat. Primum, vt
pulcherrimis valeat gaudere melodijs ac rhythmis, non communi quodam
sensu, qui omnibus innatus est musicae, vt pueri ac serui faciunt: sed
vt arte ac ratione de ijs, quae sunt artis, iudicium serre, & praua
possit à rectis dignoscere. Deinde, cum in duo tempora vita diuisa
sit, alterum negotij, alterum otij, ad negotia quidem cum dignitate
obeunda, alias disciplinas necessarias magis atque vtiles autumat. Ad
vitam verò liberaliter in otio degendam, non ludum aptum esse
contendit, vt plerique propter similitudinem, quam vita voluptuosa cum
felici videtur habere, putant. Sed Mulicam necessariam esse decernit
propter honestatem, quam habet cum voluptate coniunctam. Non enim
solùm, inquit, in negotio nos rectè gerere oportet, sed danda etiam
opera est, yt in otio bene beateque viuamus. Beata verò vita non in
honestate solum, neq; in voluptate, sed in honesta voluptate
consistit. Musicam autem esse de numero iucundissimarum rerum omnes
asserit cosentire. Quod etiam Musei vatis antiquissimi testimonio
confirmat, qui

[Greek]

Hoc est

#+begin_quote
Iucundißsimum, ait, cantum mortalibus esse.
#+end_quote

Sed praeter hanc voluptatem, quam suapte natura omnibus praebet, ob
quam omni homi num aetati, & conditioni, & moribus sensus eius est
iucundus, honoratiorem eam locum habere dicit: plurimum enim posse ad
virtutes in anima ingenerandas. Per eam nanque quadam animi qualitate,
quae ad mores pertinet, afficimur. Quoniam, vt Boëtius etiam Seuerinus
ait, praeter hoc, quòd quemadmodum caeterae mathematicae, circa
inuestigationem veritatis laborat, moralitati etiam coniuncta est:
talis enim efficitur vnusquisque, quales harmonias ac rhythmos audire
consueuit. Proponendam autem imprimis eam pueris esse censet: vt per
illam ab ipsa inde pueritia rebus optimis laetari assuescant, & ab
illiberalibus inhonestisque iocis arceantur. Nec è musica viro ciuili
tam vtile quàm delectabile petendum esse, ait. Non enim, inquit,
ingenuum virum decet, omnibus in rebus semper vtilitatem quaerere; sed
potior apud eum illa debet esse delectatio, quae voluptate non
poenitenda, qualis ex musica percipitur, ipsius animum
afficiat. Quanquam ego nescio, quae maior esse possit vtilitas, quàm
ea, quae prouenit ex musica: siquidem efficimur ab ipsa humaniores,
religiosiores, & doctiores. Humaniores quidem, quoniam, vt Plato ait,
quemad modum gymnastica corpus optimè reddit affectum; ita musica plus
aequo efferatum animum mansuesacit, atque mollit: quod in iuuene
quodam Taurominitano Pythagoram expertum esse D. Aug. & Boëtius
Ciceronem in consiliorum suorum expositione scripsisse tradunt. Cui,
cùm ad pudicae mulieris aedes expugnandas vino calidus & amore
percitus, tibiarum etia & cytharae cantibus incitatus ire contenderet,
neque vllis verbis à tanto facinore posset auerti, cytharistae
Pythagoras imperauit, vti rhythmum mutaret, ac spondeum caneret, quo
ille facto, mansuetior effectus, re infecta domum redijt. Nec vtique
ob aliud poëtas Orpheum & Amphionem finxisse credendum est, illum

#+begin_quote
Arte mat erna rapidos morantem
Fluminum lapsus, celeresq ventos
Blandum & auritas fidibus canoris
Ducere quereus.
#+end_quote

Hunc Thebanx conditoremarcis
#+begin_quote
/Saxa mouere sono testudinis, &er prece blanda/
/Ducere quo vellet./
#+end_quote

Nisi quod homines vagos ac dispersos, quo nihil est ab humanitate
alienius, cantus suauitate delinitos ad societate n humanam, vitamque
ciuilem reduxerunt. Religiosiores autem à musica nos reddi manifestum
est: valde enim erigimur ad rerum caelestium contemplationem
modulationibus & canticis, quae in templis audiuntur; quod in sacris
solennibus experimur, in quibus maiori cum artificio & suauitate
cantatur. Nec alia de causa choros monachorum, aut canonicorum in
terris institutos fuisse credibile est, nisi, vt, quemadmodum
caelestibus in choris angeli Deo semper assistunt, pulcherrimis eius
laudes melodijs ac rhythmis celebrantes, vbi, vt sancta canit
Ecciesia,

#+begin_quote
Nouas semper harmonias voxe meloda concrepat.
#+end_quote

Sic etiam terrenis in hus choris viri religiosi semper Hymnis ac
Pfalmis canendis inuigilarent, & quo meliore possent modo Deum
Optim. Maximumque laudarent. Id quod mali etiam demones, cum sicuti
dij colerentur, appetiuerunt. Nulla enim tam barbara gens vnquam
inuenta est, quae deos, quos coleret, non metris ac canticis
veneraretur. Quod maximae curae fuisse Graecis & Romanis, eorum
narrant historici: sed multò magis id populum Hebraeum, qui verum Deum
agnouit & coluit, curasse compertum est. Nam Salomonis in templo non
pauciores, quàm ducentos & triginta octo cantores, inter quos nouem
erant archipsaltae, & genus omne musicorum instrumentorum sacrae
paginae fuisse testantur. Christianus autem populus non dubium, quin
Hebraeum Ecclesiasticorum cantuum grauitate ac dulcedine superarit: de
quo Cythara psallendi peritissimus Dauid prophetico sermone dixisse
videtur in Psalmis, Beatus populus, qui scit iubilationem. Quae verba
Diuus Hilarius enarrans, Necessaria ergo, inquit, est homivi
Christiano musica, quandoquidem eius beatitudinem in ipsius scientia
consistere propheta decantat. Diuus etiam August. qui sex de Musica
libros omnigena refertos eruditione matura iam aetate conscripsit, se
mirum in modum antequàm ad orthodoxam Christi fidem conuerterotur,
musica delectatum esse di:it: sed post conuersionem vehementer eius
auditione copungi, & valde Hymnis Ecclesiae suauè resonantis
acquiescere. Et Diuo Hieronym.o scribens musi cam, ostendit ad rei
magnae admonitionem hominibus Dei largitate fuisse concessam. Atque
eius ignorationem in libris de doctrina Christiana multarum
intellectum scripturarum asserit impedire. Et duo Ecclesiae lumina
Gregorius, & Ambrosius quantum musicam ad religionis augmentum
prodesse iudicauerint, plurimis canticis Hymnorum à se compositis
testati sunt, quae adhuc alterius Mediolani, & alterius Romae canuntur
Doctiores musicae disciplina nos effici nemo ambigit, qui vel minùs,
quàm mediocriter in mathematicis e ercitatus sit: siquidem vna ex
quatuor mathematicis semper est habita, quae inter disciplinas primum,
vt dicunt, gradum certitudinis obtinent. Cuius veritas à nobis septem
his libris, quos ea de re multis annis, & maximis laboribus tandem ad
finem perduximus, patefacienda est. Quod opus vt aggrederer, non
paucis, nec parui momenti rationibus adductus sum. Primum enim venit
in mentem illius veteris sententiae, qua monemur, vt in ea, quam
nouimus, arte tempus conteramus. Ego verò ab ipsa propè infantia per
totum vitae meae curriculum rebus musicis operam impendi. Nam cum à
nutricis vberibus caecitatem infecto cum lacte suxissem, nec adhibitis
vndique remedijs vlla visus recuperandi spes affulgeret, non alia
parentibus ars vel honestior, vel vtilior visa est, in qua me
potissimum institui vellent, quam ea, quae per auditum, alterum animae
ratione pollentis optimum ministrum, aptissimè posset addisci. Nec
solum in cantu, qui humana voce conficitur, sed multò magis in ea
musicae parte, quae manuum vsu in practicis nstrumentis, quae per
antonomasiam organa vocant, exercetur, omne ferè tempus insumpsi; in
quo quantum profecerim, aliorum esto iudicium. Hoc tamen affirmare
ausim, eum, qui Aristoxeni, Ptolemaei, Boëtij, atque aliorum maximi
nominis musicorum intelligere doctrinam exactè volet, hac in parte
musicae multum diuque exercitatum esse debere: quandoquidem omnes hi
de priori musicae parte, quae Harmonica nuncupatur, & ad
instrumentalis harmonię compositionem pertinet, scripserunt. De qua,
qui versatus fuerit in musicis, quibus vtimur instrumentis, multò
faciliùs ac perfectiùs poterit iudicare. Caeterum ne de aliorum etiam
meorum studiorum ratione nihil omninovidear attigisse: fortè, dum
adhuc puer essem, venit in patriam faemina quaedam honestis orta
natalibus, quae linguae Latinae cognitione pollebat, & vt virgo sacra
fieret, artem organa pulsandi mirum in modum addiscere cupiebat: cuius
addiscendae gratia, cum domi nostrae mansisset, & illa musicam à me, &
ego vicissim ab ipsa Grammaticam didici, quam ab alio fortasse nunquàm
didicissem. Quia vel nunquam id patri venisset in mentem, vel quia
vulgus practicorum ei, nocituras musicae literas per¬ suasisset. Huius
ego disciplinae degustatione discendi cupidior effectus persuasi
parentibus vti me Salmanticam mitterent, vbi linguae Graecae & artium
ac philosophiae studijs per aliquot annos operam dedi. Sed inde
reifamiliaris inopia proficisci coactus in regiam curiam me contuli, &
à Petro Sarmento Archiepiscopo Composte. lano peramanter exceptus, cum
eo paulò post in numerum Cardinalium assumpto, discendi potiùs, quàm
ditescendi gratia Romam veni;, vbi dum inter eruditos viros versarer,
quorum illic magna copia semper fuit, pudere me coepit eius artis,
quam prositerer, ignarum esse, nec eorum, quae tractarem, afferre
posse rationem. Et tandem intellexi non minus in musica, quàm in
architectura verissimum esse illud Vitruuij, quòd ij, qui sine literis
contenderunt, vt manibus essent exercitati, non potuerunt efficerè, vt
haberent pro laboribus autoritatem. Qui autem ratiocinationibus &
literis solis confisi fuerunt, vmbram, non rem persequuti videntur. At
qui vtrumque perdidicerunt, vti omnibus armis ornati, citiùs cum
autoritate, quod fuit propositum, sunt assequuti. Quare cum ex
Aristotele cognouissem, numerorum rationes, consonantiarum &
interuallorum harmonicorum exemplares esse causas, nec omnes
consonantias aut interualla minora in suis legitimis constituta
rationibus inuenirem, veritatem ipsam ad sensus & rationis iudicium
inuestigare conatus sum. Qua in re me plurimùm adiuuerunt, praeter
Boëtium, quem omnes in ore musici habent, Gręcorum antiquorum libri
manu scripti, nec adhuc Latinitate donati; quorum etiam illic magnam
inueni copiam, sed ante alios Claudij Ptolemaei, cui nescio plus
Astronomia debeat, an musica, harmonicorum libri tres ex Bibliotheca
Vaticana, & Porphirij in eos conmentarij maximis diuitijs ex
antiquorum lectione collectis instructissimi: quorum mihi copiam fecit
Cardinalis Carpensis: & Aristoxeni de Harmonicis elementis libri duo,
& Nicomachi, quem Boëtius sequutus est, etiam libri duo, Bachaei vnus,
Aristidis libri tres, itidem Briennij tres, quos Cardinalis Burgensis
Venetijs ex Diui Marci Bibliotheca sibi transcribendos
curauerat. Quorum ijs, quae bene dixerunt, doctior, & quae secus,
cautior effectus, ad huius disciplinae cognitionem exactam potui
peruenire. In cuius inquisitione & examinatione plures viginti tribus
annis consumpsi; & tandem multis calamitatibus, praesertim duorum
Cardinalium & Proregis Neapolitani, qui me magis amarunt, quam
ditarunt, mortibus oppressus, & tribus fratribus bello amissis, maximo
natu tribuno militum, & altero eius signifero sub vrbe Metensi, tertio
ad conducendum militem ab Albano duce misso in itinere interfecto,
paucis contentus, quae tenuem admodum victum suppeditare possent, ad
Hispanias redire decreui.Statueram autem id, quod mihi vitę tempus
superesset, intra meos me continere parietes, & otiosam vitam in
honesta paupertate degentem, mihi tantùm & musis canere:

#+begin_quote
Nam nec diuitibus contingunt gaudia solis,
Nec vixit male, qui natus moriensque fefellit.
#+end_quote

Sed aliter Deo Opt. Maximo visum esse arbitror, qui me ex Italia,
postquam in ea viginti ferè annos non prorsus ignotus impenderam, ad
Hispanias reuocauit: & ex alijs Hispaniarum vrbibus, in quibus artem
musicam praemijs satis amplis exercere poteram, ad Academiam
Salmanticensem post triginta fere annos, ex quo ab ea profectus
fueram, tandem redire concessit. In qua vna, praemia satis honesta
proposita sunt musicae doctrinam, tamquae speculatur, quam quae
operatur, prositenti. Intellexit enim Alphonsus Castellae Rex huius
nominis Decimus cognomento Sapiens, qui vel primus eam instituit, vel
in meliorem formam redegit, non minus musicae disciplinam, quàm
caeterarum mathematicarum, in quibus ille maximè excelluit, disci
oportere: nec solum illius vsum, sed speculationem etiam esse
necessariam ci, qui musici nomine dignus merito iudicandus esset. Quam
ob rem inter primas & antiquissimas cathedram illius erexit, quae cùm
Doctore vacaret, quaereretur que, qui musices vtranque partem in ea
rite docere posset, ego Salmanticam veni, vt huius disciplinae peritos
sui periculum in ea facientes, audirem. Vbi cum aliquod meorum in
musica studiorum specimen dedissem, iudicatus suin ad id munus
obeundum idoneus: & cathedram ipsam duplicato ferè adauctam praemio,
ipsa etiam regia maiestate probante, sum consequutus. Et de me quidem
haec, fortasse plura, quàm opus erat, dicere volui, solum ob hoc, ne
prorsus omni destitutus auxilio rem tantam aggressus esse
viderer. Nuno ad reliquas instituri nostri rationes prosequendas
reuertar. Et possem equidem ostendere, si vellem, nullam esse earum
artium, quae circulum doctrinae constituunt, quae ab eo fastigio, in
quò veterum beneficio fuerat collocata, lapsu miserabili non
deciderit. Sed non libet mala nostra querelis nihil proficientibus
augere: longè enim praestat gaudere, quòd dudum non Romani modò, &
Itali, sed Hispani, Germani, Galli, & Britani illi toto orbe diuisi
hanc tantam bonarum artium ruinam certatim fulcire contendunt. Ac eò
rem paulatim iam perduxerunt, vt non modò ad eloquentiam, sed ad
omnium prorsus bonarum artium scientiam latior ac minùs impedita via
patere videatur. Quod vna in musica facti adhuc non esse, vehementer
conqueror: nulla namque disciplina ab altiori gradu deiecta, & minus
in nitorem antiquum restituta quàm musica reperitur. quotus enim
quisque est eorum, qui professores illius haberi volunt, qui eius
disciplinae vestigium vnquam animad uerterint! Nec quemadmodum, qui
caeteras artes profitentur earum scientiam ex causi ac principijs
adipisci conantur, sic etiam musici huius temporis musicae disciplinae
causas usque ad elementa scire concupiscunt, sed tantum ipsius
operationi dediti quod ad scientiam attinet, omnino contemnunt. Nam si
quaeras ab eis, quid sit tonus: illum diapente ad diatessaron excessum
esse respondebunt: sed quanam in proportione sit constitutus, ignorare
non erubescent. Sexcentaque sunt id genus alia, quae non tam gloriosum
erat eis scire quàm turpe nescire. Fatemur autem apud Italos & Gallos
non solum, qui caeterarum bonarum artium, sed huius etiam disciplinae
ruinam fulcire contendant, aliquos reperiri. Inter nostrates etiam
quosdam nouimus, id esse conatos; sed potiùs optasse, quàm re
praestitisse. Qiod ego cum non sine iusta animi indignatione sępe
mecum agitarem, mei nescio quo pacto me paenitere coepit. Dolebam
enim, quòd totam prope modum aetatem ita consumpsissem, vt nihil de
posteritate cogitans, in solo eorum profectu, qui à me discere
voluissent, mei periculum fecissem. Nec vnquam si quid in me ingenij &
eruditionis esset, aliter, quàm alios docendo probare
tentassem. Pręsertim cum propter exiguum quęstum, qui ex huius
disciplinę scientia prouenire solet

#+begin_quote
Pauci, quos aquus amauit luppiter.
#+end_quote

eam addiscere ac audire velint: & ex his, quorum eius doctrinam maximi
scire intererat vix vnus aut alter, qui gymnasium ei praecipiendae
dicatum adeat, inueniatur. Itaque mutato in melius, nisi me spes
fallit, proposito, coepi velle absentibus etiam & posteris prodesse,
si possem. Quod effecturum me putaui, si ex his, quae scripseram,
didascalicon aliquid, atque id non inutile publicassem: statimque
animum conuerti ad libros, quos hac de re multis abhinc annis
inchoatos, postea propemodum abieceram, non inutiles quidem illos
ratus, sed veritus ne malè feriati homines priùs negligerent, quàm
intellex issent, & consilium meum statim reprehenderent, & clamarent
me post tot Graecos & Latinos autores, & illos quidem grauissimos, in
re toties agitata, toties scripta, nihil aliud posse, quàm quod veteri
prouerbio vetamur, actum agere. Hac ego re, atque alijs, quas obijci
mihi posse intelligebam, nihil deterritus, sed magis magisque
incitatus, quoscunque vel antiquorum, vel recentiorum tractatus ea de
re inuenire potui, diligenter euolui. Et vt quosdam ex eis musica
peritissimos fuisse negare non ausim, ita illud, nihil reluctante
conscientia, affirmauerim, neminem eorum, quos huius disciplinae
scriptores habere contigit, in eius doctrina praecipienda omnes, quod
aiunt, verè numeros expleuisse. Cuius euidentissimo est argumento,
quòd, cum vnam atque eandem musicam semper fuisse, semperque futuram
esse necesse sit, eaedemque consonantiae tam apud Graecos, quàm apud
Persas sensus ac rationis iudicio deprehendantur, non aliter quam in
arithmetica bis duo christianis & barbaris sunt quatuor, non idem in
hac scientia videtur accidere. Nam aliter Pythagoras & Nicomachus
atque alij Pythagorei, aliter Ptolemaeus, & qui eum sequuti sunt, &
multò secus Aristoxenus atque eius sequaces circa consonantias &
dissonantias, & circa diatessaron diuisionem, in cuius exacta
partitione huius scientiae cardo consistit, opinati sunt. Vt cum eorum
atque aliorum maximi nominis musicorum assertiones inueniendae potiùs
veritatis, quàm tantorum virorum aestimationis minuendae causa
diligenter examinabimus, apparebit. Iuniores verò & nostri seculi
homines tantùm absunt à culpa, vt non modò digni venia, sed etiam
laude sint. Nam eorum plerique nullos ex antiquis Graecis huius
disciplinae scriptoribus habere potuetunt, quia nondum aut in Latinum
sermonem versi, aut sub praelo fuerunt, vt in manus hominum facilius
venire possent. Et si quis eorum aliquos legit, legisse potius, quàm
intellexisse videtur. Quidam autem quanquàm ingenio valuerunt, & suo
marte plurimis in rebus veritatem inuenerunt, non tamen omnia propter
abstrusam huius rei scientiam & multiplicem difficultatem assequi
potuerunt. Veruntamen hi multa in suos commentarios contulerunt,
quibus nonnihil hic labor noster adiuuatur, & in eo quoque nos eorum
doctrina delectat, quod huius disciplinae cognitionem sciendi cupidis
non honestam modò, sed vtilem esse consentiunt. Quae ratio nos mouit,
vt cum alij pro se quisque rem literariam, qua parte possent, iuuare
tentarent: idque multis ac magnis in rebus iam praestitissent: nos
quoque, quoniam maiora non possumus, experiremur, an hac in parte ab
alijs neglecta, ab alijs quasi percipi nullo pacto queat, deposita ac
desperata, à multis desiderata, à paucis intellecta, aliquid opis
afferre possimus. Atque id maiori fiducia aggressisumus, quòd nunquàm
in magnis ita fuimus occupati, vt minora negligeremus: nec vnquàm
sumus ita speciosa sectati, vt non vtilia praeferremus. Ad haec nullus
me successus aut fauor vnquam ita potuit inflare, vt

#+begin_quote
Artem puderet proloqui, quam factitem.
#+end_quote

Quamobrem nihil inuidiosum mihi sumo, si multa, quae quamuis vtilia ac
prope necessaria, caeteri contemnunt, collegisse me dico; & ea in
communem eorum, qui nesciunt, vsum proferre non erubesco. Nec me adeò
tenet scribendi cacoëthes, vt hunc laborem assumere voluissem, nisi
valde necessarium ac vtilem esse certo certius intellixissem, aut si
ab alijs ea, quae ad disciplinae huius integram perfectamque
cognitionem requiri cognoueram, excogitata vel literis pro rei
dignitate madata reperissem. Nec mirum id cuiquam videri debebit: nan
praeter hoc, quòd acutissimam & speculationibus aptissimam ingenij
perspicacitatem haec doctrina desiderat, oportet etiam, qui notitiam
ipsius exactam habere volet, eum in omni propè disciplinarum genere
versatum esse. Necessaria enim est ei musicae practicae cognitio; vt
non in cantu modò, sed in arte factis instrumentis, vt supra diximus,
exercitatus sit. Habere etiam debet artem numerandi, tam
speculatricem, quàm operatricem maximè perspectam. Principia enim
huius disciplinae ab arithmetica sumuntur, & in ea vt ipsius
conciusiones probantur. & facilitas in numerando mirum in modum
prodest speculationem rerum musicalium intelligere aut facere volenti:
contràverò tarditas, dici non potest, quamtum huiusmodi cogitationibus
officiat. Nec geometricę volumus eum ignarum esse: omnis nanque
matheseos disciplina, vt Boëtius ait, amat alterna probatione
constitui, quae multum ei prodesse poterit in participatione, ut
vocant, musicorum, quibus vtimur, instrumentorum facienda ad ditonum
in duo, & tritonum in tria spatia aeque proportionalia diuidenda. Opus
est etiam ei linguae Graecae cognitione: quoniam omnia vocabula huius
artis Graeca sunt. Et pręterea euoluendi sunt ei scriptores huius
artis, qui fere omnes Graeci fuerunt, praeter Boëtium & Diuum
Augustinum quorum ille harmonicam, hic rhythmicam à Graecis ortas
parentibus Latino sermone loqui docuerunt. Nam cęteri Latini antiqui
quàm paucissima, recentiores verò plura quidem, sed parum dilucide
tradiderunt. Et imprimis ad eam musicae partem, quae ad rhythmum
pertinet, intelligendam, eum in poëtica non parum exercitatum esse
conuenit, vt de metrorum ac versuum multiplici varietate ex varijs
poëtarum exemplis faciliùs ac perfectiùs valeat iudicare.

Quidquid igitur ad huius scientiae perfectam cognitionem pertinere
sumus arbitrati, quanta potuimus cura vndique conquisiuimus, & quae
non solùm apud musicos, philosophos, rhetores ac grammaticos
inuenimus, sed à doctis hominibus audiuimus, vel ipsi excogitauimus,
id totum in septem libros contulimus, ac eos in duas classes, alteram
quatuor, alteram trium primò diuisimus, ita vt quatuor priores prioris
etiam partis musicae, quae ad harmoniam spectat, integram exactamque,
mi fallor, doctrinam contineant. Tres autem posteriores partis quoque
posterioris, quae ad rhythmum attinet, omnia, quę necessario musicum
scire visa sunt, habere deprehendantur. Et quatuor quidem priores ita
digessimus, vt in primo à musicae vniuersè acceptae diuisione & partis
ipsius, quade agimus, definitione orsi, omnia, quae de numeris tam per
se constantibus, quam ad alios relatis, ab arithmetica petere musicum
oportere cognouimus, eôdem congessimus, vt humerorum & proportionum,
quae ex illorum collationibus oriuntur, scientia, quantum satis est ad
demonstrationes harmonicae musicae faciendas, instructus accedat. In
altero de sonis seorsum acceptis, & de eisdem inter se collatis, vnde
interualla harmonica consonantiaeque pro creantur, eodem ordine, quo
de numeris in primo & eorum collationibus, ea, quae harmonicum scire
debere, rati sumus, posita sunt. In tertio, quonam ordine iuxta veram
harmonicae rationis exigentiam, disponi, locarique soni debeant, in
tribus melodiarum generibus exactè perfecteque, ita vt nihil addi,
detrahiue possit, ostendimus. Quorum omnium typos oculis subiecimus,
vt veritatis optima constitutio sensu etiam ac ratione perpendi
queat. Atque ibidem de vero situ commatis in vno quoque trium generum
iuxta mirabile harmonicae rationis artificium non minus ingeniosam,
quàmveram ratiocinationem apposuimus. Et de diuersa artificialium
instrumentorum à perfecto deriuata imperfectione, altera organorum ac
cymbalorum, altera testudinum aut lyrarum multa scitu digna & vtilia
factu, quae nemo adhuc scripsit, nec, vt arbitror, cogitauit,
addidimus. In quarto verò de speciebus consonantiarum multo aliter,
quàm adhuc considerata sunt: de systematis & de sex antiquorum
harmonijs ac tropis, à quibus duodecim recentiorum modi fluxerunt: &
de tonis quot numero sint, & quo pacto à modis differant, ex Graecorum
doctrina, quando Latinorum ante hac id animaduertit nemo, Ptolem aei
testimonijs adductis, tractationem instituimus. Et in huius libri fine
Graecorum & Latinorum, tam antiquorum quam recentiorum, qui de musica
benemeriti sunt, assertiones, qua maiori fide ac diligentia potuimus,
recitauimus, ac examinauimus: vt quaenam earum vera esset, aut proxime
veritatem accederet, exquireremus; & in quibus bene aut secus opinati
sunt, sensu nuncio, & iudice ratione deprehenderemus. In quinto, qui
primus de altera musicae parte, quae rhythmica nominatur, institutus
est, initio quoque à rhythmi definitione sumpto numerum oratorium &
poëticum à musici rhythmi puritate seiuntimus: & de temporibus, ex
quibus pedes constant: & de pedibus seorsum acceptis, & inter se
legitimè copulatis: & de rhythmis, qui ex eorum singulis conficiuntur,
plurima scitu digna tractauimus. In cuius fine fuerit ne apud antiquos
cantus plurium vocum consideratur, & Aristotelis testimonio, ac
efficacibus argumentis apud eos in vsu fuisse, confirmatur. In sexto
de metris per eorum genera, & singulorum generum species, latè
diffuseque tractauimus: & à metricis scriptoribus, quae ad musicam
institutionem necessaria videbantur, desumpsimus. In septimo tandem de
versuum constitutione ac perfectione, ex D. Aug. & Terentiano, & Mario
Victorino, & Hephestione Graeco, atque alijs nobilibus scriptoribus,
quidquid cognitione dignum inuenimus, ad huius operis consummationem
afferre curauimus: examinatione tamen adhibita, vt, dum per veritatem
liceret, illis assentiremur. Scribendi verò stylus nó potuit esse non
varius, vt. potè qui fuerit ex nimis varia Graecorum ac Latinorum
lectione coflatus. Ex quibus pręcipui, qui nos hoc in labore iuuerunt,
plerique sunt Afri, atque eius aetatis cum iam à natiuo candore lingua
Romana valde declinauerat. Et eò maximè diuersum esse necesse fuit,
quòd ipsorum autorum no sententias modò, sed eadem verba multis in
locis, praesertim in libro septimo, ponere voluimus: cum vt operi
nostro maior autoritas accederet, tum etiam vt inspectis illorum
positionibus, ex eorum verbis syncera fide transcriptis, si quid in
eis inesset mendi, vel librarioru negligentia, vel iniuria temporis,
aut ex alijs autoribus, aut ex ipsa disciplinae ratione
corrigeremus. Vel si quid ab illis parum animaduersum ob scientiae
subtilitatem, aut minus exactè consideratum humanae naturae parum
cautae incuria fuisset, ex nostrorum tum illis collatione doctrinae
veritas dilucidior appareret. Accedit ad hoc, quod aliqua nunc sunt in
vsu instrumenta, quę vel antiqui non habebant, vel, quod verius esse
reor, quibus ea nominibus appellarent, nescimus: vt illud, quod ab
hale utica forma, quam habet, Lautuin vocatum esse creditur; & Viola,
cuius chordae tam pectine, quam manu pulsantur. Quod nomen apud
neminem Beda Sacerdote antiquiorem inueni: & multa nunc à practicis
aliter, qua ab antiquis docentur. Quorum cum ad hunc modum non fuerit
antiqua descriptio, heri non potuit, vt sermonem è medio vulgi
fugeremus; aut enim confictis nouis nominibus, cum vetera non
haberemus, arrogantiae crimen subeundum fuit, aut aliquid tot iam
annorum usui concedendum erat. Subiunximus etiam metra vulgaria
Hispanica, Gallica, & Itala Grecis ac Latinis, vt ostenderemus versus
ac metra ad omnes pertinere linguas, vel potius nullius idiomatis esse
propria, quandoquidem in modulationibus absque verbis inueniuntur: &
modos quibus vulgò canuntur, apposuimus, notis & figuris à practicis
recentioribus inuentis delineatos, cùm vt ab omnibus in arte canendi
vel mediocriter exercitatis intelligi possemus; tùm vt vulgarium
linguarum syllabae, in quibus quantitatem fixam non habent, sed omnes
communes sunt, ex ipso cantu longa ne an breues essent,
dignoscerentur. Quod in Graecis ac Latinis fieri necesse non fuisset,
nisi proptereos, qui cum canere sciant, syllabarum tamen quantitatem
ignorant. Quocirca quemadmodum in harmonica per numeros, ac eorum
proportiones veritatem opus fuit demonstrare, sic etiam in rhythmica
per notas cantuum & figuras eam ostendere, coacti sumus: qui cantus
etiam numeri per metaphoram accepti dicuntur, vt apud Maronem Orpheus

#+begin_quote
Obloquitur numeris septem discrimina vocum.
#+end_quote

Qua omnia ex totius operis lectione manifesta cuiuis esse poterunt:
interim satis erit haec pramisisse. Et ne praefatio prologi modum
excedat, ac in libri magnitudinem excrescat, hie prafandifinem
faciemus: si prius, quàm ad operis initium accedamus, auxilium
Omnipotentis Dei poposcerimus, qui laudes suas harmonijs ac rhythmis
varijs ornatas in terris pariter ac in caelis semper ab orbe condito
voluir decantari.

IOANNIS SCRIBONII IN ACADEmia Salmanticensi Graecae linguae Professoris Dodecatechon Græecum.

#+begin_quote
Hulayogas rè nadas dinaiun ixrrioar (xdeus
roruious noeu ioxa tidonin.
Eira d agiootiros ouotior nealo nudot
Movrixis inxiis niçinuiorárov.
Kai piyas onlodunios aiioten iadagns,
Eundioous s aua ro, cvno i d' e loue voge
Kovivridiunos ir apiigvione yuinoro xdtires.
Bovotos in junnaontror didtre adéog.
Touso vrvennéiligt niy aupoliene e Sadunant
xai veagir nogion, rixuitd rs xparson.
Pulposs dacuegun vodvydureave reirines ourus
Jadure weulais, ruri ravsopivois.
#+end_quote

EIVSDEM LATINVM.

#+begin_quote
Tiresie quondam ceco pensauerat auctor
Naturae damnum munere fatidico.
Luminis amißsi iacturam cacus Homerus
Pignore diuini sustinet ingeny.
Democritus visu cernens languescere mentis
Vires, tunc oculos eruit ipse sibi.
His ita dum docte mentis constaret acumen,
Corporis equanimi damna tulère sui.
Vnus at hie magnus pro maltis ecce SALIN AS,
Orbatus visu præstat ptrunq simul.
Cernit in hoc opere id, quod lynceus ille nequiret,
Iigenio quantum nullue in orbe pidet.
#+end_quote

HE visto ellibro de Musica, què compuso el Maestro Francisco de
Salinas, y no hallo enel cosa porqueno se pueda imprimir, y assi me
parecequesedeue dar Licencia, porque es obra muy auentajada de lo que
hasta agora esta escrito en la facultad, y sera muy vtil a todos los
Musicos Theoricos y Practicos, que se qui sieren aprouechar del. En
Madrid r7. de Septiembre 1575.

Iuan Lopez de Velasco.


LVDOVICI CHAZARETAE in laudem autoris

EPIGRAMMA.

#+begin_quote
Dum te virgineos, ò nostri gloria secli
Aoniae fidicen, docte Salina, lyra,
Vrget inaccessi nemoris penetrare recessus
Audacem tantæ laudis anhelus amor:
Exuperas montis secreta biuerticis antra,
Antra, nec humano limina pulsa pede;
Limina qua riguas obliquis flexibus vmbras,
Vmbrosumqu, rigat (astalis vnda nemus.
Hic tum fortè sacros adytis penetralibus artus
Rorabant nudae vitreo in amne Deae.
Hue inopina pago flectens vestigia gressu
Deprendis nudas vitreo in amne Deas.
Vertere nec dum acieni licuit,cùm numine Dinum
lam subita sentis lumina nocte premi.
O sed quæ, o rapta succedunt pramia luci,
Quàm sie à detito Sole carere inuat.
Ductrix accedit cetu comitata sororum,
Et regina sui Calliopea chori:
Ipsa chelyn tradens, facundag plectra, fidesq,
Et meritam incingens birgine fronde comam,
His, antistes, ait, nostris dignande choreis,
Dulcia iacturae damna repende tuæ.
Hae tibi erunt artes, vulgare arcana per orbem
Nostra, & Bistoniae fila nouare lyrae.
#+end_quote

YO Iuan Fernandez de Herrera Secretario del consejo de su Magestad doy
fe que auiendose visto por los Señores del vn libro que con licencia
de los dichos Señores hizo imprimir el Maestro Francisco de Salinas
Cathedratico de propriedad de la facultad de Musica en la Vniuersidad
de Salamanca intitulado de Musica especulatiuale dieron licencia para
que pudiesse vender cada volumen de los del dicho libro en papel a
seyscientos marauedis con que antes, y primero que le veda haga
imprimir en la primera hoja del este testimonio de tassa: fecho en
Madrid, a seys dias del mes de nouiembre, de mil y quinientos y
setenta y siete anos.

Iuan Fernandez de Herrera.

* [Book 1]
** [Chapter 1.1]
DE MVSICA LIB. I.

DE MVSICAE UNIVERSALIS DVPLICI DIVISIONE, ALTERA IVXTA POSItiones antiquorum, altera nuper excogitata.

CAPVT PRIMVM.

E Musica dicere nobis instituentibus, quoniam ipsius vis adeò latè per
vniuersa diffunditur, yt nihil sine illa costare credatur, necesse
erit, eam in partes diuidere, vt quaenam ipsius pars sit, de qua
disputare velimus, faciliùs intelligatur. Musicam ergo antiqui ferè
omnes triplicem esse dixerunt: Mundana, Humanam, &
Instrumentalem. Mundanam quidem eam appellauerunt, quę in dissimilium
motuum caelestium mira coaptatione, & concordi temporumvarietate, ac
elementorum proportionabili permixtione, & denique in harmonica totius
mudi constructione consistit. Humanatem  esse dixerut, que in hominis
opificio, presertim in animae, & corporis coniunctione, & in ipsius
animae partiu dispositione versatur; & in artium omnium, ac
scientiarum ordine; & regnoru, ac rerumpublicarum constitutionibus; &
tandem in his omnibus, quae propriè ad homine pertinent,
inuenitur. Instrumentalen verò illam vocauerunt, quę in vocibus, aut
in Musicis instrumentis, vt in Cithara, & tibijs constituta est. Nos
auten vt hanc Musicae diuisionem non aspernamur, quippe quae magnos
habeat autores, sic etiam alteram, ex ipsius rei natura depromptam, &
ad pręsentem institutionem accommodatiorem afferri posse
censemus. Quae etiam erit trimembris, vt alia Musica sit, quę sensum
tantùm mouet, alia quae intellectum tantùm, alia quae sensum, &
intellectum simul. Quae sensum tantùm mouet, solo auditu percipitur,
neque ab intellectu consideratur; cuiusmodi sunt cantus auium, qui
audiuntur quidem cum voluptate, sed quoniam à nullo mentis sensu
proficiscuntur, non harmonica ratione constant, per quam ab intellectu
valeant considerari. Vnde nullas consonantias, aut dissonantias
efficiunt, verùm innata quadam vocum suauitate delectant. Quod si in
eis aliquando harmonica interualla deprehenduntur, id casu potiùs, aut
ex aptitudine, ad imitandum sibi naturaliter insita, prouenire
censendum est, perquam assuefactae discunt cantus hominum imitari, vt
Psittaci, qui ex nimia audiendi frequentia loquelam imitantur
humanam. Veruntamen haec Musica irrationalis est, vt sensus ipse,
quoniam solùm ab irrationalibus animantibus conficitur, nec propriè
Musica dici potest. non enim aliter aues canere, quàm aquae, &
prataridere dicuntur : & Musica in genere rationalium constituitur, vt
suo loco dicetur. Sed eam inter Musicae genera placuit adnumerare,
propter vsitatissimum loquendi modum, iuxta quem semper apud omnes
nationes Musicae nomen obtinuit. Quę intellectum tantùm mouet,
intelligi quidem potest, audiri verò non potest: sub qua duæe
antiquorum Mundana, & Humana comprehenduntur, cuius harmonia non
aurium voluptate, sed intellectus consideratione percipitur. Siquidem
non in permixtionibus sonorum, sed in rationibus deprehenditur
numerorum. Quanquam enim non inficiamur in maxima disparium motuum
caelestium concordia ratum modulationis ordinem inueniri, vt, exempli
gratia, in signiferi constitutione, consonantiarum, & toni rationes:
id tamen propter harmonicam numeri duodenarij naturam, in quo
signiferum ipsum constitutum est, dicimus euenire. Ob quam Brienius
autor Gręcus eum numerum abAristotele M.να, hoc est, valde musicum
asserit appellari. Neque motus caelestes vllos omnino ciere sonos
opinamur, vel subiecto, vel efficiente causa, vt Phy sicis placet. Nam
praeter Aristotelicas rationes, quas nos huc transferre noluimus, ne
potiùs Physicam, quàm Musicam docere velle videremur, illa certè
probabilis esse videtur, mundanae fabricae conditorem, vt in
necessarijs non defecisse, ita nihil superuacaneum fecisse. Cuiusmodi
futurus erat sonus ille caelestis, qui à nemine posset audiri. Non ab
hominibus, quoniam multis de causis fieri necesse aiunt, vt ad nostras
aures sonus ille non perueniat. Non ab intelligentijs, quae caelos
mouent, quandoquidem neque aures habent, neque auribus
egent. Quamobrem idem iudicium de Musica caelesti, & de elementari
faciendum esse arbitror. Siquidem quae in compage elementorum, & in
temporum varietate perspicitur, non aurium sensu, sed rationis iudicio
perpenditur, qualis est ea, quae in partibus animae inuenitur: in
quibus omnes consonantiarum proportiones inesse dicuntur. Ita vt
facultas rationalis ad irascibilem sesquialteram habeat rationem, in
qua Diapente consonantia constituta demonstratur. Et irascibilis ad
concupiscibilem sesquitertiam, in qua Diatessaron consonantia
reperitur: ex quibus in anima Diapason perfecta consistit. Et
quemadmodum in Musica vocali, siue instrumentali Diapente continet
Diatessaron, & ab ea non continetur, & Diapason habet in se vtramque,
neque ab illis habetur: sic facultas sentiendi continet vegetatricem,
neque ab ea continetur, & facultas rationalis vnica existens habet in
se reliquas duas, neque ab illis habetur: sed in ea tanquam trigonus
in tetragono inesse dicuntur. Praeterea virtutes consonantiae, & vitia
dissonatiae, multis ac iustis de causis ab omnibus communiter
appellantur: quarum rerum cognitio sub auditus sensum cadere non
potest. Non tamen omnino contennenda sunt, quae memoriae consecrauit
antiquitas, quę, quoquo posset modo, semper ad cęlestium rerum amorem,
hominum mentes erigere conata est: quae videndi ac audiendi maximè
delectatione ducuntur. Quae sensum simul, & intellectum mouet, est
inter has media: quia sensu aurium percipitur, & ab intellectu etiam
consideratur. Et haec est, quam antiqui instrumentalem esse dixerunt,
quae non solùm naturali vocum, aut sonorum suauitate auribus est
iucunda: sed etiam harmonica deprehenditur constareratione. Et quia
solus homo inter animantes rationis est particeps, solus etiam omnium
harmoniam intelligit. Quam inter naturalia, & diuina in genere
rationalium reponendam asserit Ptolemaeus. Et soia ea Musica, qua
homines vtuntur, harmonica constat ratione. Ea igitur, quę intellectu
tantùm consideratur, philosophis, & astronomis; &, quae solo au rium
sensu percipitur, vtpote irrationali, irrationalibus animantibus
relicta: hac de Musica, quę sensus & rationis iudicium admittit, & non
solùm propter naturalem vocum, aut sonoru suauitatem, sed propter
consonantias, & reliqua interualla, quae iuxta numerorum harmonicorum
rationes disposita sunt, delectat, ac docet, scribere instituimus, &
ostendere nostri seculi hominibus, vnde tot, ac tam variae sectae
inter eos, qui de Musica scripserunt, ortae sint, vt aliquando tandem
eos, qui eius vsu duntaxat gaudent, cum his, qui ipsius speculationi
dediti sunt, conciliare possimus. Cuius definitionem, ratio atque ordo
doctrinae postulat, vt ante omnia in medium afferre tentemus.

** [Chapter 1.2]
De Musicae instrumentalis definitione, & diuisione.

C A P. II.

AEc ergo Musica, quae sensus, & rationis iudicio perficitur (vt eam
definit Aristides, inter Graecos autor non ignobilis, in principio
suae Musicae) est modulandi, & eorum, quae ad modulandum pertinent,
scientia. Quae definitio non multùm discrepat ab ea, quam tradit
D. Augustinus lib. primo de Musica, vbi illam esse ait, benè modulandi
scientiam. Scientia autem (vt idem asserit Aristides) est, cuius
cognitio firma est, & ab omni errore prorsus aliena: qualia sunt
principia Musicae, quę à Mathematicis (vt ipse ait) apotelesmata
dicuntur, neque alterationem aut mutationem vllam recipiunt. Dicta
autem Musica fuisse videtur à Musis, quibus omnipotentiam canendi
tribuebat antiquitas. Haec igitur Musica instrumentalis prima sui
diuisione diuiditur in Theoreticen, & Practicen. Theoretica est, quae
circa rerum musicalium contemplationem versatur, sola earum cognitione
contenta. Practica verò,quae iuxta artis praecepta artificiosè , & cum
delectatione modulatur. Theoretica rursus diuiditur, in Harmonicam, &
Rhythmicam. Harmonica est (vt definitur à Ptolemaeo primo harmonicorum
libro) facultas, differentias sonorum secundum acutum, & graue
perpendens. Quae tota circa instrumentalis harmoniae compositionem
versatur, & lonos ad harmoniam aptos, reiectis ineptis, considerat. Et
interualla harmonica, quae ex eorum permixtionibus fiunt, vt tonos, &
semitonia; & consonantias vt Diapason, & Diapente; & reliqua, quae
sunt ad eam necessaria; & quibus numerorum proportionibus respondeant,
exacto iudicio rationis inquirit. Quorum vsum docet in praxi Musica,
quam vocant planam, siue vniformem, in qua puer vocem ad harmoniam
aptam formare, & eam per harmonica mouere interualla docetur,nihil
curans multumne an parum temporis in sonorum prolatione consumat; sed
quantum eam attollere, aut ponere debeat. Rhythmica est, quae metitur
diuersas pronunciandi moras, temporum ordine in celeritate, &
tarditate seruato. Quae non quantum vox poni, aut tolli debeat in
harmonicis interuallis considerat: sed quantum, in cuiusque soni, aut
vocis enunciatione, morae faciendum sit, maxima cum ratione
perpendit. In quo primùm tempora considerat; & vnius moram, quae
minima est, breui syllabae, aut notae, duorum verò longae
tribuit. Deinde pedes, qui ex syllabis, aut notis tam breuibus, quàm
longis fiunt, ad Rhythmum aptos, explosis ineptis, examinat. Postremò
Rhythmos ipsos inquirit, qui constant ex pedibus ritè copulatis, & in
celerum, ac tardorum motuum ordine constituti reperiuntur. Quę omnia
in cantu, quem figuratum, aut mensuralem Itali vocant, & in
modulationibus, quae in Musicis fiunt instrumentis, ex figurarum
diuersitate auribus percipiuntur. His autem duabus Antiqui Metricam
adiunxerunt, ea verò est teste Cassiodoro, quae mensuras diuersorum
metrorum probabili ratione cognoscit, vt de heroico,iambico. neque
enim , vt Rhythmica, Rhythmum solùm considerat, qui ex pedibus ritè
copulatis (vt dictum est) sine certo fine quantumlibet in longum
protrahitur, vt fit in modulationibus, in quibus nullus est certus
finiendi modus: sed metrum etiam, quod certo fine clauditur, ad quem
cum peruenit, ad caput redit; vt accidit in vulgaribus cantilenis, &
hymnorum ac psalmorum canticis: & diuersorum metrorum diuersos esse
modulandi modos ostendit. Ex qua omnium metrorum genera ortum habuêre,
quae omnibus linguis, & nationibus, si rectè considerentur, sunt
eadem, vt luce clariùs manifestum erit, cum de hac parte tractationem
instituemus. Et has tres Musicae partes (si credimus Aristidi) qui
perfectionem in cantu assequi volet, obseruare debebit: Harmonicam, vt
sciat vocem à loco ad locum mouere, neque eam aut grauiorem, aut
acutiorem faciat, quàm ratio postulat interualli: Rhythmicam, vt
Rhythmos, & eorum plausum intelligat, & canere ad numerum, quem aërem
recentiores vocant, appositè norit: Metricam,vt modulationem
conuenientem metris coniungat, neque trochaicis iambicorum modos
adaptet; sed verba notis, & notae verbis per omnia conueniant. Vtrùm
autem haec diuisio in tres partes, an potiùs in duas ab antiquis fieri
debuerit, sexto libro, cùm de metris agemus, conuenientiùs
examinabimus. Interim de harmonica quoniam harmonia prior est Rhythmo,
prius quàm de Rhythmica nobis habendus est sermo, & qui sint in ea
iudices, quanto breuiùs poterimus, explicandum.

** [Chapter 1.3]
Quòd non solùm sensus, sed rationis etiam iudicium in Harmonica sit necessarium. CAP. III.

Vnt autem in Harmonica iudices sensus, & ratio, sed non eodem
modo. Quia, vt Ptolemaeus ait, sensus iudicat iuxta materiam, &
affectionem, ratio verò iuxta formam, & causam. Ex quibus verbis elici
potest, quòd, sicut materia à forma, sic iudicium sensuale perficitur
à rationali. Est autem sensus proprium, per se quod vero proximum est
inuenire, & à ratione integritatem accipere: rationis autem contrà, à
sensu quod verò proximum est accipere, & per se ipsam integritatem
inuenire. Nam quod ille confuse in ipsa materia fluida instabilique
cognoscit, haec a materia denudatum integrè, vt verè est, exactéque
dijudicat. Quare non solùm aurium, sed rationis etiam iudicium in
harmonica necessariu est, neque vnum sine altero potest esse
perfectum. Aurium namque iudicium necessarium est; quia prius est
tempore; ac nisi illud praecedat, ratio munere suo fungi non potest:
imperfectum verò, quia, nisi à ratione adiuuetur, mancum omnino, &
debile reperitur. Rationis autem contrà, videtur enim quodam modo esse
imperfectum, quia ratio pars est intellectus, neque hic cognoscere,
neque illa iudicare quicquam potest: nisi quod per sensus tanquam per
fenestras introierit. sed valde necessarium, quia ad minutissimas
vsque differentias pertingit, quas sensus nequaquam valet
dijudicare. Sensus tamen & ratio sic se habent in harmonica, vt,
quicquid ille probat in sonis, haec ita se habere ostendat in numeris:
ne quicquam auribus, rationique possit esse contrarium. Cum ergo
auditus circa sonos versetur, ratio verò maximè vim suam ostendat in
numeris: priùs, quàm sonos numeris comparemus, ostendamusque, &
numeris sonos, & numerorum proportionibus consonantias, ac reliqua
interualla respondere , aliqua de numeris, ac de eorum inter se
comparationibus necessariò praemittenda sunt. Quandoquidem (vt Boëtius
Seuerinus ait primo de Arithmetica libro) omnia quaecunque a primaeua
rerum natura constructa sunt, numerorum videntur ratione formata. Et,
vt asserit Aristot. 2. physicorum libro, ipsae proportiones sunt
formae, aut causę formales interuallorum, & consonantiarum. Nam, vt
illic ait, illius concentus, qui omnes sonos complectitur, hoc est,
Diapason causa formalis, est ratio duorum ad vnum. Haec autem omnia
latè prosequemur, si priùs breuiter, quod sit ipsius Musicae
subiectum, cuius cognitio valdè necessaria videtur, ostenderimus.

** [Chapter 1.3]
Quod sit Musice facultatis subiectum, & Dtrùm media an Mathematica dicenda sit, & eam Arithmeticae subalternari.

CAP. IIII.

EX his quae dicta sunt, facilè perspicitur, Musicae subiectum esse non
posse numerum tantùm per se sumptum; cuius iudicium ad rationem, & non
ad sensum spectare videtur: neque sonum seorsùm consideratum, qui
sensus, & non intellectus obiectum est: sed quoddam tertium ex vtroque
conflatum, quod numerus sonorus appellatur. Est autem numerus sonorus,
numerus partium corporis sonori, quod rationem discreti accipiens, &
per numeros in partes diuisum, ducit nos in cognitionem quantitatis
tam soni ab eo producti, quàm diuersorum sonorum ex partibus ipsius
cum eo, & inter se comparatis prouenientium. Vocamus autem corpus
sonorum, siue spatium in Musica chordam, aut neruum, aut cannam, aut
aes tinnulum, & quicquid reperitur, ex quo sonus harmonicus elici
potest. Variatur autem sonus ex variatione numeri, qui chordam, aut
cannam metitur. alius namque sonus est cannae trium palmorum, & alius
sex. Et si chorda ita tensa sit, vt sonum harmonicum efficiat, & in
quinque partes diuidatur aequales, eiusque portio, quae est vt tria, &
ea, quae est vt duo, per ponticulum distinctae simul percutiantur:
sonus partis, quae est vt duo, erit acutior sono partis, quae est vt
tria, in Diapente consonantia. Et si in duas diuidatur medietates, &
primum tota percutiatur; deinde posito in medio digito, vel
ponticulo,altera pulsetur medietas; experiemur ad sensum, sonum
prouenienten ex totius percussione grauiorem esse sono, quem reddet
medietas, & alterum ab altero per Diapason consonantiam distare. Vnde,
cognita per numerum secundum longitudinem quantitate chordae, quae sit
vniformis, ac regularis, statim possunt à nobis soni, iuxta certas ac
determinatas grauis, & acuti differentias, inuicem comparari. quibus
eo modo, quo dictum est, inuestigatis, & à nobis sic primò cognitis,
varias postea de illis demonstramus affectiones. Et quia haec omnia, &
quaecunque alia à Musicis considerantur, ad perfectam potissimùm
numeri sonori cognitionem diriguntur: manifestè apparet, eum esse
verum Musicae facultatis subiectum. Iuxta quam positionem
Aristoteles 2. physicorum, & omnes, qui eum secuti sunt, asserunt,
Musicam nec Mathematicam tantùm, neque Physicam esse; sed mediam inter
vtramque dici oportere. Nam quatenus sonum considerat, ad physicam
spectare videtur: quandoquidem sonus nisi in materia, & sine motu nec
esse,nec definiri potest. vnde ipsius considerationem necesse est, ad
Physicum pertinere. Numerus autem & abstractus à materia, & sine motu
definiri potest, & considerari, quod mathematicarum est
proprium. Nihilominus tamen mathematica videtur esse dicenda; tum quia
Musicus non considerat sonum, quatenus est res naturalis, sed quatenus
est principium cantus, & vt soni sunt elementa, ex quibus harmonia
constat: neque eorum naturas, vt Physicus, sed differentias, quae
inter eos in acumine, & grauitate consistunt, examinat; quod potiùs
est harmonici, quàm Physici. tum etiam quia soni habent se in Musica
vt materia, & in ratione mensurati; & numeri vt forma,& in ratione
mensurantis. Quare à nobiliori, hoc est, à forma nomen accepit; atque
vna ex mathematicis semper est habita. Et cum ex eis quaeda dicantur
subalternantes, vt Arithmetica, & Geometria; quędam subalternatae, vt
Musica, & Astronomia: Musica dicitur Arithmeticae
subalternari. Quoniam Arithmetica considerat numerum absolutè, &
numerus sic acceptus est eius subiectum: Musica verò considerat eum
contractum, vt est in materia sensibili, hoc est, in corpore sonoro
accepto sub ratione discreti. Et dicitur Arithmeticae subalternari,
non solùm quia subiecti sui partem accipit ab ea, sed quia etiam ab ea
sumit omnia principia, & media suarum demonstrationum. Quae quidem
principia non existimare debemus esse omnes conclusiones, quae in
Arithmetica demonstrantur, neque omnes quae in numeris inueniuntur
proportiones: sed eas tantùm conclusiones, per quas omnes de numero
sonoro passiones possunt demonstrari. Et ex proportionibus numerorum
solùm eas assumit, quae ad generationem consonantiarum, & musicalium
interuallorum sunt aptae: quae sunt paucissimae. Quanquam ineptas
nonnunquam considerat, vt reijciat, quod suis locis
demonstrabimus. Sed priùs de priori subiecti parte, quae numerus est,
quam de posteriori videtur agendum. Et de numero tam simplici, quàm
relato breuiter ea, quae ad praesentem attinent institutionem dicenda,
sine quibus Musicae doctrina claudicaret omnino.

** [Chapter 1.5]
De numeri acceptione, & definitione.

CAP. V.

ETquoniam tum naturae ratio certa demonstrat, tum doctissimorum
virorum praecepta nos monent, vt, de quo disputare instituimus, priùs
diligenter exquiramus, quid sit; quàm id, quale sit, explicare
tentemus: de numero harmonico scripturi, ordinem & vi rationis
ostensum, & autoritatum grauitate praescriptum sequemur. Verùm ne in
primo statim limine lector offendat, eum admonendum putauimus, numeri
nomen apud Latinos ambiguum esse. nunc enim quicquid ad numerandi
rationem pertinet, signifieat, yt cum centum, aut decem viros dicimus:
nunc verò per Methaphoram acceptum ad modulandi peritiam, & pedes, &
metra conficienda pertinet: vt cum numerum lambicum, aut Trochaicum
appellamus. In qua significatione accepit eum Maro, cum dixit: numeros
memini, si verba tenerem. Et alibi: Multa vi brachia tollunt in
numerum. Et vox quidem vnica est, notiones vero duae, quas Latini sola
definitione secernere possunt; Graeci verò diuersa etiam appellatione
distinguunt: nam priorem illum Arithmop, posteriorem hunc Rhythmon,
appellare consueuerunt. Et quandoquidem vtriusque consideratio Musico
necessaria est, de priori illo, qui vniuersalior est, priùs erit
considerandum; qui sic à Boëtio definitur: Numerus est vnitatum
collectio. Ex qua definitione ostenditur manifestè, vnitatem non esse
numerum, sed numerandi principium, & ex pluribus vnitatibus numerum
constare. Quae si erunt duae, constituent binarium, qui nil est aliud,
quàm duarum vnitatum nexus, & ternarius trium; ita vt ab vnitate omnis
numerus habeat quod sit vnusqua sublata nullus erit numerus: sublato
tamen numero, non desinit esse vnitas. Diuiditur autem numerus prima
sui diuisione in Parem, & Imparem. Numerus par est, qui potest in duo
aequalia, & duo inaequalia partiri; vt 10. qui potest diuidi,
in 5. & 5. & in 4. & 6. Imparautem est, qui non potest in duo aequalia
partiri: quod accidit propter vnitatis interuentum, quae naturaliter
indiuisa est: & semper in duo inaequalia partitur,
vt 7. in 4. & 3. & 5. & 2. Habent autem hę duę species valde diuersas
proprietates inter se. Nam paris proprium est, vt quocumque modo, siue
in duo ęqualia, siue in duo inaequalia fiat diuisio, si altera pars
sit par, altera necessariò erit etiam par,et si impar, etiam
necessariò erit impar; ita vt nec parilitas imparilitati, neque
imparilitas parilitati misceatur. vt 8. diuiditur in 4. & 4: & 5. & 3:
& in 6. & 2: & 7. & 1. In quibus diuisionibus aut vterque numerus est
par, aut vterque impar. contrà verò imparis proprium est, vt,
quocunque modo diuidatur, necessariò pars aitera sit par, & altera
impar: vt 7. diuiditur in 4. & 3. in 5. & 2. & in 6. & 1. in quibus
diuisionibus neque vtraque pars est impar, sed altera par, altera
impar inuenitur.

** [Chapter 1.6]
De numeri Paris speciebus.

CAP. VI.

RVrsus numeri Paris tres inueniuntur species: quidam enim est pariter
par, quidam pariter impar, & quidam impariter par. Sunt autem pariter
par, & pariter impar veluti oppositi, & impariter par inter eos
medius. Numerus ergo pariter par est, qui pluries in duo aequalia
diuidi potest, donec ad vnitatem naturaliter indiuisam diuisio
perueniat, vt 16. in 8. & 8:8. in 4. & 4:4. in 2. & 2:
& 2. in 1. & 1. Et hi numeri sunt, qui ab vnitate ortum habentes per
duplam progressionem vsque in infinitum procedunt, vt
1.2.4.8. 16.32.64. Pariter impar est ille, qui semel in duo aequa
diuidi potest, vt 6. in 3. & 3. quiam plius in duo aequà diuidi non
possunt. Et hi numeri sunt, qui proueniunt ex duplatione omnium
imparium sine vllo statu in infinitum progredientes. Quod facilè
perspicietur. si disponantur per ordinem ex vna parte omnes impares, &
ex altera omnes pariter impares, vt in hoc typo videre licebit.

|--------------+---+---+----+----+----+----+----+----|
| Impares.     | 1 | 3 |  5 |  7 |  9 | 11 | 13 | 15 |
|--------------+---+---+----+----+----+----+----+----|
| Horum dupli. | 2 | 6 | 10 | 14 | 18 | 22 | 26 | 30 |
|--------------+---+---+----+----+----+----+----+----|

Et sciendum est, quod, quemadmodum pariter pares ortum habent ab
vnitate, quae est omnium numerorum principium; sic pariter impares
oriuntur à binario, qui est omnium parium origo. Et hi omnes semper
inter se vnus post alium quaternario distabunt, vt 2.6. 10.14. In quo
etiam est animaduertendum, quòd sicut vnitas omnes in se continet
virtute numerorum species, & figuras, & diuersis rationibus potest
par, & impar, & quodammodo omnia dici: ita etiam binarius, qui est
illi proximus propter respectus diuersos poterit dici pariter par, &
pariter impar: nam quia eius diuisio vsque ad vnitatem peruenit, & per
duplam progressionem ab vnitate procedit, meritò pariter par
appellatur: et quatenus vnitatis imparis duplus est, & semel in duo
ęqua diuidi potest, inter pariter impares reponi debet. Primus autem
pariter impar sine mistione impariter paris, aut pariter paris
inuenitur esse senarius. Quanquam si propriè loquamur, vnitas neque
par est, neque impar quandoquidem non est numerus, sed omnium
numerorum principium, tam parium quànimparium. Binarius etiam quoniam
est parium origo, impropriè dicetur par. vnde neque erit propriè
pariter par, aut pariter impar: quia neutrius illi conuenit definitio;
sed erit vtriusque principium, & vtrique poterit adaptari. Vocatur
autem vnitas à D. Augustino, principium à quo, & binarius principium
per quod, primo suae Musicae libro. Quibus addit, ternarium primum,
propriè numerum dici debere, & perfectum esse: quoniam principio &
medio & fine constat; in quo valde conuenit cum Aristot. qui primo
li. de celo, Magnitudinum, ait, ea quae in vnum diuidi potest, linea;
quae in duo, extremitas aut planum quae in tria, corpus dicitur. Nec
verò praeter has alia est magnitudo: propterea quòd tribus omnia
continentur, & ter omni ex parte dicitur. Vniuersum enim, & omnia,
tribus, quemadmodum Pythagoraei tradunt, determinata sunt;
quandoquidem finis, medium ac principium vniuersi ac totius numerum
complectuntur, quae eadem illum ternionis continent. Itaque quod à
natura quasi leges illius accepimus in Deorum etiam sacrificijs hoc
numero vtimur. Quin etiam appellandirationes eodem modo attribuimus;
nam duo ambo, duosque ambos, vel vtrumque dicimus, omnes non dicimus,
sed hoc nomen ad tres primum accommodamus. Impariter par est ille, qui
pluries in duo ęqua diuidi potest: sed non toties vt vsque ad vnitatem
perueniat eius diuisio, vt 12. qui potest diuidi in 6. & 6: &
iterum 6. in 3. & 3: sed 3. in duo ęqua ampliùs diuidi non potest. Est
autem hic numerus medius inter pariter parem , & pariter imparem: quia
cum vtroque communicat, & ab vtroque discrepat: communicat quidem cum
pariter pari, quatenus pluries in duo ęqua, sicut ille diuiditur:
discrepat autem ab eo, quia eius in duo aequa diuisio non ad vnitatem
vsque perducitur. cum pariter impari communicat quidem in hoc, quod
non potest vsque ad vnitatem in duo aequa partiri: sed discrepat in
eo, quod pluries, & non semel vt ille in duo aequa diuidi potest. Sunt
autem impariter paris numeri multiplices species: nam quidam bis
tantùm diuidi possunt, vt 12. in 6. & 6: & 6. in 3. & 3. Et hi sunt
omnes dupli omnium pariter imparium. Quod manifestum erit, si
disponantur duae lineae, in quarum altera sint omnes pariter impares,
& in altera omnes primi impariter pares, qui erunt eorum dupli
incipiendo à senario, qui, vt dictum est, est primus pariter impar, vt
hic typus ostendit.

|-----------------------+----+----+----+----+----+----+----|
| Pariter impares.      |  6 | 10 | 14 | 18 | 22 | 26 | 30 |
|-----------------------+----+----+----+----+----+----+----|
| Primi imparit. pares. | 12 | 20 | 28 | 36 | 44 | 52 | 60 |
|-----------------------+----+----+----+----+----+----+----|

Et aduertendum est, omnes hos octonario inter se numero distare, sicut
pariter impares quaternario. Secundi autem ter diuiduntur, et sunt
primorum dupli: vt 24.40.80. & sic sine statu; et ex his quae dicta
sunt, liquidò constabit, ex pariter paribus primum esse quaternarium,
& in infinitum per duplam progressionem protendi; ex pariter imparibus
primum esse senarium, & per additionem quaternarij ad infinitum vsque
procedere: Et ex impariter paribus primum esse duodenarium, & per
additionem octonarij sine statu posse reperiri. &, vt paucis vniuersa
complectamur, quoties quisque vel pariter imparium, vel impariter
parium diuidi potest, totus a ternario duplus, erit eius ordinis
primus, & per toti à ternario dupli additionem procreatur. Et hoc de
Paris numeri speciebus dixisse sufficiat.

** [Chapter 1.7]
De Imparis numeri speciebus. CAP. VII.

SVnt etiam Imparium numerorum tres species: nam quidam eorum sunt
primi & incompositi, quidam secundi & compositi, alij verò inter hos
medij, qui per se quidem accepti sunt secundi & compositi, & cum
altero comparati sunt primi & incompositi, & vocantur contra se
primi. Primus ergo & incompositus numerus est ille, quem sola metitur
vnitas, vt ternarius, & quinarius, quorum sola vnitas est pars
numeratiua, aut multiplicatiua, vel, vt recentiores dicunt,
aliquota. Et ea pars dicitur esse numeratiua, vel aliquota, quae
aliquoties sumpta, ipsum totum restituit: vt binarius est pars
numeratiua senarij: quia ter sumptus senarium restituit: & non est
pars ternarij, aut quinarij, quia bis sumptus ternarium superat, & à
quinario deficit; constituit enim quaternarium, qui ternario maior, &
quinario minor est: ter autem sumptus senarium reddit, qui maior est
quinario. Vnitas vero omnium numerorum est mensura communis; quia in
quemcunque numerum ducatur, ipsum reddit, vt in decem ducta decem, in
centum centum. Et sciendum est, idem esse metiri, quod numerare. Sunt
autem primi & incompositi omnes impares, praeter binarium, qui primus
est parium; ideoque sola ab vnitate numerari potest. Secundus &
compositus est ille, quem praeter vnitatem alius etiam numerus
metitur; vt 9. & 15. quorum priorem praeter vnitatem metitur etiam
ternarius; ter enim sumptus facit nouem, & posteriorem metiuntur idem
ternarius, & quinarius: ille quinquies, & hic ter acceptus. Qui autem
scire volet, quonam pacto hi numeri secundi quasi diuino quodam
artificio generentur à primis, & quam mirabili ab illis ordine
procedant; legat Boëtium priori suae Arithmeticae libro, & Iordanum,
cui plurimùm Arithmeticam omnes debere fatentur. Nos enim Musicam, &
non Arithmeticam profitemur, & ad eius institutionem
properamus. Numeri contra se primi sunt illi, qui (vt dictum est) per
se considerati inueniuntur esse secundi & compositi: & ad alterutrum
collati primi & incompositi naturam participant. cuiusmodi
sunt 9. & 25. quorum priorem metitur ternarius, & posteriorem
quinarius; sed neuter eorum metitur vtrumque. Nam 5. metitur 25. non
tamen 9: & 3. metitur 9. & non 25. Quod non ita euenit in nouenario, &
quindenario: nam vtrumque ternarius metitur, vt superius ostensum
est: 9. & 25. sola vnitas metiri potest, quę, vt dictum est, omnes
metitur numeros. Artem autem, qua hoc demonstrari poterit, trademus
inferius: cum modum docebimus, per quem proportiones ad minimos
numeros, in quibus inueniri possunt, valeant reduci.

** [Chapter 1.8]
De alia divisione numeri Paris digna consideratione, & valde scitu necessaria.

CAP. VIII.

ESt etiam alia numeri Paris diuisio, quae non minima consideratione
digna videtur. nam parium numerorum quidam inueniuntur esse superflui,
quidam diminuti, quidam autem omnino perfecti. Numerus superfluus est
ille, cuius partes numeratiuae simul sumptae ipsius summam superare
deprehenduntur; vt duodenarius, cuius partes numeratiuae sunt
1.2.3.4.6. quae omnes in summam redactae producunt 16: qui numerus
duodenarium quaternario superat. Diminutus autem est ille, cuius
partes in vnum collectae, à totius summa deficiunt, vt denarius, cuius
partes numeratiuae sunt 1.2.5. qua simul sumptae constitunnt
octonarium, qui denario minor est. Perfectus verò est ille, cuius
partes numeratiuae simul acceptae ipsum restituunt, vt senarius, cuius
partes sunt 1.2. & 3: quae simul sumptae faciunt 6. Et infra decem
vnus senarius reperitur esse perfectus: & infra centum alter, qui
est 28. & infra mille solus 496. & infra decem millia item vnus 8128:
& nullus alius inuenitur vsque ad 130816. In quibus numeris
animaduertendum est, eos ita consequenter dispositos esse, vt primus
in 6.secundus in 8. desinere reperiantur: & sic vnus post alium in his
duobus numeris sunt constituti. Est etiam admirabilis horum numerorum
generatio, atque progressio: nam dispositis ab vnitate, pariter
paribus, qui coniuncti primum fecerint, si in illum extremus ducatur,
perfectum creabunt; vt ex vnitate & binario quia fit ternarius,
binario in illum ducto senarius creatur, ijsdem addito quaternario fit
septenarius, in que ducto quaternario, producitur 28. & quoniam
adiuncto octonario fit 15. qui primus non est, procedendum est
ad 16. & fiet 31. in
